#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Expansion 4: ~2000 concepts for the OverUnder deck.
Every concept passes the test: "Per me [X] è sopravvalutato/sottovalutato"
"""

MEGA_EXPANSION_4 = [
    # ═══════════════════════════════════════════════════════════════
    # 1. MARCHE E PRODOTTI SPECIFICI (~200)
    # ═══════════════════════════════════════════════════════════════
    "Rolex","Omega","TAG Heuer","Patek Philippe","Audemars Piguet",
    "Breitling","IWC Schaffhausen","Cartier orologi","Tissot","Longines",
    "Seiko","Citizen","Hublot","Zenith orologi","Panerai",
    "Gucci","Prada","Balenciaga","Valentino","Bottega Veneta",
    "Fendi","Dolce & Gabbana","Versace","Givenchy","Burberry",
    "Moncler","Stone Island","Canada Goose","The North Face","Patagonia",
    "Columbia","Arc'teryx","Napapijri","K-Way","Woolrich",
    "Pandora gioielli","Swarovski","Tiffany & Co.","Bvlgari","Damiani",
    "Pomellato","Morellato","Breil","Fossil","Daniel Wellington",
    "Samsung Galaxy","Huawei","Xiaomi","OnePlus","Google Pixel",
    "Oppo","Realme","Motorola","Sony Xperia","Nothing Phone",
    "Dyson aspirapolvere","Dyson asciugacapelli","De'Longhi macchine caffè","Smeg elettrodomestici","KitchenAid",
    "Weber barbecue","iRobot Roomba","Bosch elettrodomestici","Miele","Liebherr frigoriferi",
    "Bialetti","Alessi","Lagostina","Tefal","Moulinex",
    "Rowenta","Braun","Philips Sonicare","Oral-B elettrico","Gillette",
    "L'Oréal","Nivea","Dove","Kiehl's","Clinique",
    "MAC Cosmetics","NARS","Urban Decay","Charlotte Tilbury","Fenty Beauty",
    "Rare Beauty","Glossier","The Ordinary skincare","CeraVe","La Roche-Posay",
    "Samsung TV","LG TV","Sony TV","Hisense TV","TCL TV",
    "Sonos speakers","Bose cuffie","Marshall speaker","JBL portatili","Bang & Olufsen",
    "Technics giradischi","Audio-Technica","Sennheiser","Shure","AKG",
    "Canon fotocamere","Nikon","Sony Alpha","Fujifilm","Leica",
    "Tesla","Rivian","Lucid Motors","Polaris","BYD auto elettriche",
    "Xiaomi monopattini","Segway","Brompton bici pieghevoli","Bianchi biciclette","Specialized bici",
    "Trek biciclette","Cannondale","Scott bici","Giant bici","Garmin ciclocomputer",
    "Fitbit","Whoop fitness","Suunto","Polar orologi sportivi","Amazfit",
    "Nike Training Club","Under Armour","Lululemon","Gymshark","Reebok",
    "Puma","Fila","Diadora","Kappa","Ellesse",
    "Ray-Ban","Oakley","Persol","Maui Jim","Moscot",
    "Moleskine","Leuchtturm1917","Parker penne","Montblanc penne","Lamy",

    # ═══════════════════════════════════════════════════════════════
    # 2. PIATTI REGIONALI MONDIALI (~200)
    # ═══════════════════════════════════════════════════════════════
    "I pierogi polacchi ripieni","Le empanadas argentine","La moussaka greca",
    "Lo tzatziki","Il souvlaki greco","Il borscht ucraino",
    "I pelmeni russi","Gli xiaolongbao cinesi","I dan dan noodles",
    "Il rendang indonesiano","Il satay malese","Il bibimbap coreano riscaldato",
    "Il bulgogi coreano","Il jollof rice africano","L'injera etiope",
    "Il bunny chow sudafricano","La poutine canadese","Il butter chicken indiano",
    "Il vindaloo indiano","Il biryani indiano","Il tikka masala",
    "Il pad thai","Il som tam tailandese","Il massaman curry",
    "Il yellow curry tailandese","Il panang curry","Il larb tailandese",
    "Il ramen giapponese","Il miso ramen","Il tonkotsu ramen",
    "Lo shoyu ramen","Il tsukemen giapponese","L'udon giapponese",
    "La soba giapponese","Il sashimi giapponese","Il chirashi giapponese",
    "Il temaki giapponese","L'onigiri giapponese","Il bento giapponese",
    "Il katsu curry giapponese","Il karaage giapponese","L'edamame",
    "Il kimchi coreano","Il tteokbokki coreano","Il japchae coreano",
    "Il samgyeopsal coreano","Il kimbap coreano","Il hotpot cinese",
    "Il mapo tofu","Il kung pao chicken","Il char siu cantonese",
    "Il chow mein","Lo spring roll vietnamita","Il bún chả vietnamita",
    "Il cao lầu vietnamita","Il gỏi cuốn vietnamita","Il bobotie sudafricano",
    "Il tagine di agnello marocchino","La harira marocchina","Il falafel",
    "L'hummus","Il baba ganoush","Il tabbouleh libanese",
    "Il fattoush libanese","Il kibbeh libanese","Il mansaf giordano",
    "Il koshari egiziano","Il ful medames egiziano","L'acarajé brasiliano",
    "Il moqueca brasiliano","Il pão de queijo brasiliano","Il coxinha brasiliano",
    "Il churrasco brasiliano","Il lomo saltado peruviano","L'ají de gallina peruviano",
    "Il causa limeña peruviano","La bandeja paisa colombiana","Le pupusas salvadoregne",
    "Il gallo pinto costaricano","Il ropa vieja cubano","Il mofongo portoricano",
    "Il chili con carne texano","Il clam chowder di Boston","Il lobster roll americano",
    "Il jambalaya cajun","Il gumbo della Louisiana","Il po' boy di New Orleans",
    "I biscuits and gravy americani","Il chicken and waffles","Il cornbread americano",
    "La key lime pie","Il pecan pie","Il banana bread",
    "Lo scone britannico","Il meat pie australiano","Il pavlova neozelandese",
    "Il fish and chips britannico","Il bangers and mash","Il cottage pie",
    "Il tikka kebab","Il doner kebab","L'adana kebab turco",
    "Il börek turco","Il simit turco","Il baklava turco",
    "Il lokum turco","I churros spagnoli","Le patatas bravas spagnole",
    "La tortilla española","Il gazpacho andaluso","La paella valenciana",
    "Il pulpo a la gallega","Le tapas spagnole","Il bacalhau à brás portoghese",
    "Il pastel de nata portoghese","La francesinha portoghese","Il caldo verde portoghese",
    "Lo stamppot olandese","Il bitterballen olandese","Lo stroopwafel olandese",
    "Le moules-frites belghe","La carbonnade belga","Lo stoemp belga",
    "Il rösti svizzero","Le Spätzle tedeschi","Il currywurst tedesco",
    "Il pretzel tedesco","Il Sauerbraten tedesco","Il Käsespätzle",
    "La Sachertorte viennese","Lo Strudel di mele","Il Kaiserschmarrn austriaco",
    "Il Smörgåsbord svedese","Le polpette svedesi","Il gravlax scandinavo",
    "Il surströmming svedese","Il rakfisk norvegese","Lo skyr islandese",
    "L'hákarl islandese","Il Cevapi balcanico","Il burek balcanico",
    "Il sarma balcanico","La musaka serba","Il banitza bulgaro",
    "Il bigos polacco","Il żurek polacco","Il langos ungherese",
    "Il lángos con panna acida","Il kürtős kalács ungherese","Il trdelník ceco",
    "Il svíčková ceco","Il khachapuri georgiano","Il khinkali georgiano",
    "L'olivier russa","Il syrniki russo","Il plov uzbeko",
    "Il manti turco-centroasiatico","I momos tibetani","Il thali indiano",
    "Il dhal indiano","Il paneer tikka","Il naan indiano",
    "Il roti indiano","Il paratha indiano","Il chaat indiano",
    "Il pani puri indiano","Il lassi indiano","Il mango sticky rice tailandese",
    "Il hainanese chicken rice","Il nasi lemak malese","Il laksa di Singapore",
    "Il bak kut teh malese","Il lumpia filippino","L'adobo filippino",
    "Il sinigang filippino","Il sisig filippino",

    # ═══════════════════════════════════════════════════════════════
    # 3. CITTÀ E REGIONI DEL MONDO (~200)
    # ═══════════════════════════════════════════════════════════════
    "Portland","Seattle","Austin","Nashville","New Orleans",
    "Denver","Philadelphia","Boston","San Diego","Chicago",
    "Washington D.C.","Houston","Dallas","Detroit","Minneapolis",
    "Salt Lake City","Pittsburgh","Charlotte","Memphis","Savannah",
    "Tucson","Albuquerque","Honolulu","Anchorage","Boise",
    "Vancouver","Montreal","Calgary","Ottawa","Quebec City",
    "Halifax","Winnipeg","Victoria BC","Edmonton",
    "Edinburgh","Glasgow","Cardiff","Manchester","Birmingham UK",
    "Liverpool","Bristol","Brighton","Oxford","Cambridge",
    "Bath","York","Belfast","Leeds","Nottingham",
    "Lione","Marsiglia","Bordeaux","Toulouse","Nizza",
    "Strasburgo","Nantes","Montpellier","Lille","Avignone",
    "Aix-en-Provence","Cannes","Saint-Tropez","Biarritz",
    "Monaco di Baviera","Amburgo","Dresda","Colonia","Francoforte",
    "Lipsia","Stoccarda","Düsseldorf","Norimberga","Heidelberg",
    "Bruges","Gand","Anversa","Bruxelles come città",
    "Rotterdam","L'Aia","Utrecht","Amsterdam quartiere a luci rosse",
    "Göteborg","Stoccolma","Malmö","Stavanger","Bergen in Norvegia",
    "Oslo","Copenaghen","Aarhus","Helsinki","Tampere",
    "Tallinn","Riga","Vilnius","Varsavia","Danzica",
    "Breslavia","Lubiana","Zagabria","Spalato","Dubrovnik centro storico",
    "Belgrado","Tirana","Salonicco","Tbilisi","Yerevan",
    "Baku","Casablanca","Tunisi","Il Cairo come città","Nairobi",
    "Città del Capo","Johannesburg","Lagos","Accra","Dakar",
    "Dar es Salaam","Addis Abeba","Kigali","Zanzibar come destinazione",
    "Marrakech centro","Fez","Essaouira","Chefchaouen",
    "Mumbai","Delhi","Bangalore","Goa","Jaipur",
    "Varanasi","Udaipur","Kerala","Kathmandu","Colombo",
    "Hanoi","Ho Chi Minh City","Chiang Mai","Luang Prabang",
    "Phnom Penh","Bali come destinazione","Kuala Lumpur",
    "Jakarta","Manila","Taipei","Busan","Osaka",
    "Hiroshima","Hokkaido","Shanghai","Pechino","Chengdu",
    "Xi'an","Hangzhou","Shenzhen","Guangzhou",
    "Città del Messico","Guadalajara","Oaxaca","Cancún centro",
    "Playa del Carmen","Medellín","Bogotá","Cartagena de Indias",
    "Lima","Cusco","La Paz","Santiago del Cile","Valparaíso",
    "Montevideo","San José Costa Rica","Panama City",
    "L'Avana","San Juan Porto Rico","Beirut","Amman",
    "Muscat","Abu Dhabi","Doha","Riyadh",
    "Melbourne","Brisbane","Perth","Adelaide","Auckland",
    "Wellington","Queenstown Nuova Zelanda","Fiji come destinazione",

    # ═══════════════════════════════════════════════════════════════
    # 4. ARTISTI CONTEMPORANEI E DESIGNER (~100)
    # ═══════════════════════════════════════════════════════════════
    "Virgil Abloh come designer","Raf Simons","Alexander McQueen come brand",
    "Vivienne Westwood come icona","Giorgio Armani","Valentino Garavani",
    "Donatella Versace","Miuccia Prada","Tom Ford","Karl Lagerfeld come icona",
    "Coco Chanel come icona","Stella McCartney","Marc Jacobs","Demna Gvasalia",
    "Pierpaolo Piccioli","Alessandro Michele","Daniel Lee per Burberry",
    "Hedi Slimane","Phoebe Philo","Rick Owens","Rei Kawakubo",
    "Issey Miyake","Yohji Yamamoto","Jil Sander","Dries Van Noten",
    "Martin Margiela","Thom Browne","Manolo Blahnik","Jimmy Choo",
    "Christian Louboutin","Salvatore Ferragamo","Tod's","Brunello Cucinelli",
    "Ermenegildo Zegna","Loro Piana","Max Mara","Alberta Ferretti",
    "Missoni","Etro","Marni","Sergio Rossi","Giuseppe Zanotti",
    "Aquazzura","Philippe Starck come designer","Karim Rashid",
    "Patricia Urquiola","Gaetano Pesce","Stefano Giovannoni",
    "Marcel Wanders","Tom Dixon","Jonathan Ive","Dieter Rams come influenza",
    "Massimo Vignelli come influenza","Bruno Munari come influenza",
    "Achille Castiglioni","Gio Ponti come influenza","Renzo Piano come architetto",
    "Zaha Hadid come influenza","Bjarke Ingels","Norman Foster",
    "Frank Gehry","Tadao Ando","Kengo Kuma","Santiago Calatrava",
    "Jean Nouvel","David Chipperfield","Rem Koolhaas",
    "Jeff Koons","Damien Hirst","Takashi Murakami","KAWS come artista",
    "Ai Weiwei","Marina Abramović","Olafur Eliasson","Anish Kapoor",
    "Maurizio Cattelan","Michelangelo Pistoletto","Francesco Vezzoli",
    "Vanessa Beecroft","JR l'artista","Daniel Arsham",
    "Shepard Fairey","Invader street artist","Os Gemeos",
    "Futura come artista","Retna","Felipe Pantone",
    "Nigo come designer","Hiroshi Fujiwara","Pharrell Williams come designer",
    "Kanye West come designer","Rihanna come imprenditrice moda",
    "Beyoncé come brand","Victoria Beckham come designer",

    # ═══════════════════════════════════════════════════════════════
    # 5. PODCAST E MEDIA SPECIFICI (~100)
    # ═══════════════════════════════════════════════════════════════
    "Il podcast di Joe Rogan","Il podcast di Lex Fridman","Serial podcast",
    "This American Life","My Favorite Murder","Muschio Selvaggio",
    "Passa dal BSMT","2024 di Francesco Costa","Da Costa a Costa",
    "Veleno di Pablo Trincia","Indagini di Stefano Ferro","La Zanzara",
    "Tintoria podcast","Cachemire podcast","Il Podcast di Alessandro Barbero",
    "Barbero come divulgatore","Power Pizza podcast","Morgana podcast",
    "Chiedilo a Barbero","Stories di Cecilia Sala","Daily Cogito",
    "Tutti i colori del giallo","Un libro tira l'altro","Comodino podcast",
    "The Daily del New York Times","Hardcore History di Dan Carlin",
    "Radiolab","99% Invisible","Freakonomics Radio",
    "How I Built This","TED Talks Daily","The Tim Ferriss Show",
    "Huberman Lab podcast","Diary of a CEO","SmartLess",
    "Armchair Expert con Dax Shepard","Conan O'Brien Needs a Friend",
    "Call Her Daddy","Crime Junkie","Casefile True Crime",
    "Sword and Scale","Last Podcast on the Left","Science Vs",
    "Stuff You Should Know","The Moth","Invisibilia",
    "Il Sole 24 Ore podcast","Limes podcast di geopolitica",
    "Il podcast di Will Media","Breaking Italy di Shy",
    "Will Media come progetto","Factanza","Torcha media",
    "MasterClass come piattaforma","Skillshare","LinkedIn Learning",
    "YouTube come piattaforma educativa","YouTube Premium",
    "YouTube Shorts vs TikTok","Twitch come piattaforma","Kick come piattaforma",
    "Substack come piattaforma","Medium come piattaforma","Patreon come modello",
    "Ko-fi","Buy Me a Coffee","OnlyFans come business model",
    "Fansly","Cameo","Reddit come fonte di informazioni",
    "4chan","Quora","Wikipedia come fonte","Hacker News",
    "Product Hunt","Pitchfork come rivista musicale","Rolling Stone Italia",
    "NME","Vogue Italia","GQ Italia","Esquire Italia",
    "Rivista Studio","Il Post come testata","Domani giornale",
    "Open di Mentana","Fanpage come testata","Vice Italia",
    "The Vision","Linkiesta","Ansa","AGI notizie",
    "Sky TG24","TgCom24","RaiNews24",

    # ═══════════════════════════════════════════════════════════════
    # 6. TIPI DI ESERCIZI FITNESS (~100)
    # ═══════════════════════════════════════════════════════════════
    "Lo squat con bilanciere","Lo stacco da terra","La panca piana",
    "Il plank","I burpees","Le trazioni alla sbarra",
    "I dip alle parallele","Il crunch addominale","Lo shoulder press",
    "Il rowing con bilanciere","Le flessioni","Gli affondi",
    "Il leg press","Il curl per bicipiti","Le estensioni per tricipiti",
    "Il french press per tricipiti","Le alzate laterali","Le alzate frontali",
    "Il pulley basso","Il lat machine","La pressa per le gambe",
    "Il leg curl","Il leg extension","Il calf raise",
    "Lo squat bulgaro","Lo squat frontale","Il goblet squat",
    "Lo stacco rumeno","L'hip thrust","Il glute bridge",
    "Il Russian twist","I mountain climbers","I jumping jack",
    "Lo squat jump","Il box jump","Il wall sit",
    "Il plank laterale","I V-up addominali","Il bicycle crunch",
    "La hollow body hold","Il superman a terra","Il bird dog",
    "Il face pull","Lo shrug con manubri","Il pull-over con manubrio",
    "Le croci ai cavi","Le croci con manubri","I piegamenti a diamante",
    "Le trazioni a presa larga","Le trazioni a presa stretta","I chin-up",
    "Il muscle-up","L'handstand push-up","Il pistol squat",
    "L'L-sit","Il dragon flag","Il front lever",
    "La bandiera umana","Il rope climb","Il battle rope",
    "Gli swing con kettlebell","Il Turkish get-up","Il clean and press",
    "Lo snatch con kettlebell","Il farmer walk","Il sled push",
    "Il tire flip","Il wall ball","Il thruster",
    "Il rowing su ergometro","Lo ski erg","L'assault bike",
    "La corsa sul tapis roulant con inclinazione","La camminata in salita sul tapis roulant",
    "Lo stretching statico","Lo stretching dinamico","Il foam rolling come recupero",
    "Lo yoga come complemento al fitness","Il Pilates matwork","Il Pilates reformer",
    "La sbarra per trazioni a casa","Le parallettes","Gli anelli da ginnastica",
    "L'allenamento a circuito","L'HIIT","Il tabata",
    "L'EMOM","L'AMRAP","Il drop set",
    "Il super set","Il giant set","Il rest-pause",
    "L'allenamento in monofrequenza","L'allenamento in multifrequenza",
    "La periodizzazione dell'allenamento","Il deload settimanale",

    # ═══════════════════════════════════════════════════════════════
    # 7. PIATTAFORME E SERVIZI STREAMING (~100)
    # ═══════════════════════════════════════════════════════════════
    "Crunchyroll","Paramount+","Apple TV+","HBO Max","Hulu",
    "Peacock","Discovery+","MUBI","Criterion Channel","Amazon Music",
    "Tidal","Deezer","SoundCloud","Bandcamp","Qobuz",
    "Apple Music","YouTube Music","Spotify Free vs Premium",
    "Amazon Prime Video","Netflix con pubblicità","Disney+ con pubblicità",
    "Funimation","Hidive come piattaforma anime","Wakanim",
    "Rakuten TV","Chili cinema","TimVision","Infinity+","NOW TV",
    "RaiPlay","Mediaset Infinity","DAZN Standard vs Plus",
    "Amazon Luna","GeForce Now","Xbox Cloud Gaming","PlayStation Now",
    "Steam Deck come piattaforma","Epic Games Store","GOG",
    "Humble Bundle","Xbox Game Pass","PlayStation Plus Premium",
    "EA Play","Ubisoft+","Apple Arcade",
    "Google Stadia come esperimento","Shadow cloud PC","Boosteroid",
    "Kindle come piattaforma","Kobo come e-reader","Storytel",
    "Spotify per podcast","Apple Podcasts","Google Podcasts",
    "Amazon Audible vs libri fisici","Blinkist per riassunti","Headway app",
    "Masterclass vs corsi universitari","Domestika","Platzi",
    "Twitch Prime","Amazon Photos","Google One",
    "Dropbox vs Google Drive","WeTransfer","Mega cloud storage",
    "1Password","Bitwarden","LastPass",
    "NordVPN","ExpressVPN","Surfshark","ProtonVPN",
    "ProtonMail","Tutanota","Signal vs WhatsApp",
    "Telegram vs WhatsApp","iMessage","Viber",
    "Skype nel 2025","Webex","Google Workspace vs Microsoft 365",
    "Miro","ClickUp","Asana","Monday.com","Jira",
    "Airtable","Coda","Obsidian per appunti","Roam Research","Logseq",
    "Readwise","Pocket app","Instapaper","Flipboard","Feedly",
    "Inoreader","Apple News","Google News",

    # ═══════════════════════════════════════════════════════════════
    # 8. GIOCHI MOBILE E CASUAL (~100)
    # ═══════════════════════════════════════════════════════════════
    "Candy Crush Saga","Angry Birds","Temple Run","Subway Surfers",
    "Fruit Ninja","Flappy Bird","2048","Wordle quotidiano",
    "Pokémon GO","Clash of Clans","Hay Day","Township",
    "Gardenscapes","Homescapes","Merge Dragons","Merge Mansion",
    "Royal Match","Coin Master","Among Us su mobile","Fall Guys mobile",
    "Genshin Impact mobile","Honkai Star Rail","PUBG Mobile",
    "Call of Duty Mobile","Fortnite mobile","Diablo Immortal",
    "Monument Valley","Alto's Odyssey","Florence il gioco",
    "Journey su mobile","Sky Children of the Light","Oceanhorn",
    "Plants vs Zombies","Cut the Rope","Where's My Water",
    "Doodle Jump","Jetpack Joyride","Crossy Road",
    "Geometry Dash","Stack Ball","Helix Jump",
    "Color Switch","Piano Tiles","Tiles Hop",
    "Trivia Crack","QuizDuello","Brain Out",
    "Toon Blast","Toy Blast","Lily's Garden",
    "Fishdom","Bingo Blitz","Solitaire classico su telefono",
    "Scacchi su Chess.com","Sudoku su telefono","Le parole crociate sul telefono",
    "Ruzzle","Wordscapes","Word Connect",
    "Hay Day come simulatore","SimCity BuildIt","TheoTown",
    "Plague Inc.","Rebel Inc.","Mini Metro",
    "Civilization VI mobile","XCOM su mobile","Football Manager Mobile",
    "FIFA Mobile","eFootball mobile","Real Racing",
    "Asphalt 9","Mario Kart Tour","Dr. Mario World",
    "Animal Crossing Pocket Camp","Fire Emblem Heroes","Dragalia Lost",
    "AFK Arena","Raid Shadow Legends","Summoners War",
    "Rise of Kingdoms","Lords Mobile","Empires & Puzzles",
    "Mobile Legends","Wild Rift su mobile","Arena of Valor",
    "Hearthstone mobile","Legends of Runeterra","Marvel Snap",
    "Clash Royale su ladder","Brawl Stars competitivo",
    "Le notifiche dei giochi mobile","Le microtransazioni nei giochi mobile",
    "I giochi pay-to-win","I giochi free-to-play","I gacha game",
    "Le pubblicità nei giochi gratuiti","I giochi offline su telefono",
    "I giochi indie su mobile","I giochi nostalgici riediti su mobile",

    # ═══════════════════════════════════════════════════════════════
    # 9. CONCETTI DI VIAGGIO SPECIFICI (~100)
    # ═══════════════════════════════════════════════════════════════
    "Il jet lag","La cena con vista panoramica","Il tour guidato",
    "L'audioguida del museo","Il free walking tour","Il souvenir tipico",
    "La cartolina dal viaggio","La foto con il monumento","La guida Lonely Planet",
    "I blogger di viaggi","I travel influencer","Le recensioni su TripAdvisor",
    "Le stelle degli hotel su Booking","La colazione inclusa nell'hotel",
    "Il minibar dell'hotel","L'accappatoio dell'hotel","Le pantofole dell'hotel",
    "Il room service","Il late check-out","L'early check-in",
    "La vista mare dalla camera","La camera con balcone","La suite d'albergo",
    "L'upgrade gratuito in hotel","Il programma fedeltà degli hotel",
    "Le miglia aeree","Il programma frequent flyer","La business class",
    "La prima classe in treno","Il vagone letto","L'Orient Express come mito",
    "Il treno panoramico svizzero","Il Glacier Express","Il Transiberiana",
    "Il viaggio in treno notturno europeo","Il pass Eurail","L'Interrail per over 27",
    "Il viaggio in solitaria","Il viaggio di gruppo organizzato","Il viaggio di nozze",
    "Il gap year","L'anno sabbatico","Il sabbatical dal lavoro",
    "Il viaggio come crescita personale","Il viaggio zaino in spalla in Asia",
    "Il viaggio in camper attraverso l'Europa","Il road trip sulla Route 66",
    "Il road trip lungo la costa californiana","La Great Ocean Road australiana",
    "Il viaggio in Islanda in auto","Il viaggio in Scozia",
    "La guida a sinistra in UK","Il pedaggio autostradale in Italia",
    "La vignetta autostradale svizzera","I caselli autostradali francesi",
    "Le code al Brennero in estate","Le code in Liguria il sabato",
    "L'assicurazione di viaggio","Il passaporto biometrico",
    "Il visto per gli USA","L'ESTA per gli USA","Il visto per l'Australia",
    "Le vaccinazioni per i tropici","La farmacia da viaggio",
    "Il kit di primo soccorso in viaggio","La borraccia filtrante in viaggio",
    "Il pranzo al sacco in montagna","Il rifugio alpino","La malga con degustazione",
    "Il trekking di più giorni","Il cammino portoghese","Il cammino dei Balcani",
    "Le guide Routard","Le guide DK Eyewitness","Google Translate in viaggio",
    "Il roaming dati all'estero","La eSIM da viaggio",
    "La SIM locale all'estero","Il WiFi pocket da viaggio",
    "Cambiare valuta in aeroporto","La carta Revolut in viaggio",
    "Il bancomat all'estero","Le commissioni bancarie all'estero",
    "L'adattatore di corrente universale","La presa elettrica diversa all'estero",
    "Il fuso orario","L'orologio biologico dopo un volo lungo",
    "Il mal d'altitudine","Il mal di mare","Le compresse per il mal d'auto",

    # ═══════════════════════════════════════════════════════════════
    # 10. SPORT E ATLETI SPECIFICI (~200)
    # ═══════════════════════════════════════════════════════════════
    "La pallavolo femminile italiana","La nazionale di rugby italiana",
    "Il fioretto italiano","La sciabola italiana","La spada italiana",
    "L'arrampicata sportiva olimpica","Lo skateboard olimpico","Il breaking come sport olimpico",
    "Il padel come fenomeno","Il crossfit come cultura","Le palestre boutique",
    "Il SoulCycle","L'F45 Training","L'OrangeTheory Fitness",
    "Le Spartan Race come evento","Le Tough Mudder","Le Hyrox",
    "Il triathlon Ironman","La maratona di New York","La maratona di Boston",
    "La maratona di Berlino","La maratona di Roma","La mezza maratona",
    "La corsa dei 5 km come obiettivo","Il parkrun settimanale",
    "Il trail running","L'ultra trail","L'UTMB di Chamonix",
    "Kilian Jornet","Eliud Kipchoge","Mo Farah","Jakob Ingebrigtsen",
    "Usain Bolt come leggenda","Marcell Jacobs","Gianmarco Tamberi",
    "Filippo Tortu","Jannik Sinner","Matteo Berrettini",
    "Lorenzo Musetti","Jasmine Paolini","Camila Giorgi",
    "Carlos Alcaraz","Novak Djokovic","Rafael Nadal come leggenda",
    "Roger Federer come leggenda","Serena Williams come leggenda",
    "Iga Świątek","Coco Gauff","Naomi Osaka",
    "Francesco Bagnaia","Marc Márquez","Valentino Rossi come leggenda",
    "Max Verstappen","Lewis Hamilton","Charles Leclerc",
    "Lando Norris","Oscar Piastri","Carlos Sainz",
    "La Scuderia Ferrari in Formula 1","La Red Bull Racing","La Mercedes in F1",
    "La McLaren in F1","La Formula E","Il WRC rally",
    "La MotoGP vs la Formula 1","La Superbike","Il motocross",
    "LeBron James","Stephen Curry","Luka Dončić",
    "Giannis Antetokounmpo","Kevin Durant","Nikola Jokić",
    "L'NBA come spettacolo","L'Eurolega di basket","La Serie A di basket italiana",
    "L'Olimpia Milano basket","La Virtus Bologna basket",
    "Il nuoto artistico","I tuffi olimpici","Il pentathlon moderno",
    "Il tiro a segno olimpico","Il sollevamento pesi olimpico","La lotta libera olimpica",
    "La boxe professionistica","L'UFC","Conor McGregor","Khabib Nurmagomedov",
    "Israel Adesanya","Alex Pereira","Jon Jones",
    "Il sumo giapponese","Il wrestling WWE","La AEW",
    "Il golf come sport","Tiger Woods come leggenda","Rory McIlroy",
    "Il polo come sport d'élite","L'ippica","Le corse di cavalli",
    "La Formula E come futuro","Le gare di endurance 24 ore di Le Mans",
    "Il rally Dakar","Il Giro d'Italia","Il Tour de France",
    "La Vuelta a España","Tadej Pogačar","Jonas Vingegaard",
    "Remco Evenepoel","Primož Roglič","Filippo Ganna",
    "Mathieu van der Poel","Wout van Aert","La Parigi-Roubaix",
    "Il Giro delle Fiandre","La Milano-Sanremo",
    "Lo sci alpino discesa libera","Lo sci di fondo","Il biathlon",
    "Il salto con gli sci","Lo slittino olimpico","Il bob olimpico",
    "Lo skeleton","Il freestyle skiing","Lo snowboard halfpipe",
    "Lo snowboard slopestyle","Il curling come sport televisivo",
    "L'hockey su ghiaccio NHL","Il rugby Sei Nazioni","Il rugby neozelandese All Blacks",
    "Il cricket internazionale","Il baseball MLB","La NFL americana",
    "Il Super Bowl","Il calcio australiano AFL","Il Gaelic football irlandese",
    "L'hurling irlandese","Il kabaddi indiano","Il sepak takraw asiatico",
    "Il lacrosse","Il softball","Il beach soccer",
    "Il futsal","La pallamano","La pallanuoto olimpica",
    "Il canottaggio olimpico","La vela olimpica","Il surf olimpico",
    "La ginnastica ritmica","La ginnastica artistica maschile",
    "Simone Biles","La danza sportiva","Il pattinaggio artistico sul ghiaccio",

    # ═══════════════════════════════════════════════════════════════
    # 11. FENOMENI DI COSTUME (~200)
    # ═══════════════════════════════════════════════════════════════
    "La dieta Dukan","La dieta zona","Il digiuno di 16 ore",
    "L'intermittent fasting","Il biohacking","Il grounding camminare scalzi",
    "La cold plunge","Il bagno nel ghiaccio","L'ice bath come routine",
    "Il micro-dosing","Il journaling della gratitudine","La vision board",
    "La manifesting culture","La legge di attrazione su TikTok",
    "I cerchi delle donne","I ritiri spirituali","I ritiri di silenzio",
    "La digital detox","Lo smartphone detox per un weekend",
    "Il dopamine detox","Il no-fap movement","Il self-improvement culture",
    "Il sigma male grindset","La hustle culture","Il rise and grind",
    "La sveglia alle 5 del mattino","La morning routine da CEO",
    "Le cold shower mattutine","Il diario dei sogni",
    "La dieta chetogenica","La dieta paleo","La dieta carnivora",
    "La dieta a base vegetale","Il raw food","Il juicing",
    "I centrifugati detox","Le acque aromatizzate detox",
    "Il carbone attivo nel cibo","La curcuma in tutto",
    "Lo zenzero in tutto","Il matcha come superfood","La spirulina",
    "La clorella","L'ashwagandha","Il fungo reishi","Il lion's mane",
    "I nootropici","Gli adattogeni","Il collagene da bere",
    "Gli integratori di vitamina D","Gli integratori di magnesio",
    "Gli integratori di omega 3","Le proteine in polvere","I BCAA",
    "La creatina","La caffeina come integratore","I pre-workout",
    "I meal prep della domenica","Le meal prep container","Il batch cooking",
    "Il tracking delle calorie","Il conteggio dei macro","Il food scale",
    "Il digiuno prolungato","La restrizione calorica","Il deficit calorico",
    "La reverse diet","Il refeed day","Il cheat meal del weekend",
    "Il body recomposition","Il lean bulk","Il dirty bulk","Il cutting",
    "La body positivity estrema","Il fitness come identità",
    "Le trasformazioni fisiche su Instagram","I before and after",
    "Il wellness come industria","Il self-care come marketing",
    "Le candele profumate come self-care","I bagni caldi con sali",
    "Le maschere per il viso la domenica","Il rituale della skincare serale",
    "La slow living","Lo slow food come movimento","Lo slow fashion",
    "Il consumo consapevole","La moda circolare","Il vintage come scelta etica",
    "Il thrifting","Lo swap party","Il guardaroba minimalista",
    "Il metodo Marie Kondo","Il decluttering radicale","Il feng shui",
    "Lo wabi-sabi giapponese","Il kintsugi come filosofia",
    "Il lagom svedese","Il niksen olandese","Il friluftsliv norvegese",
    "Il forest bathing","Lo shinrin-yoku","I bagni nella foresta",
    "L'earthing","La terapia del suono","Le campane tibetane",
    "I gong bath","La sound healing","Le frequenze 432 Hz",
    "Le frequenze binaurali","Il journaling libero","Il bullet journal",
    "Il brain dump","La pagine del mattino di Julia Cameron",
    "La ruota della vita","L'intenzione del giorno",
    "Il goal setting","Lo SMART goal","L'OKR personale",
    "Il time blocking","La tecnica dell'eat that frog","La regola dei due minuti",
    "La regola 80/20 nella vita","Il principio di Pareto applicato",
    "Il minimalismo digitale","Le app di screen time","Il grayscale sul telefono",
    "Il telefono in bianco e nero","La notifica disattivata",
    "Il telefono in modalità aereo la sera","La sveglia analogica vs il telefono",
    "Il diario cartaceo vs digitale","La to-do list cartacea",
    "Il planner settimanale","L'agenda Moleskine","L'agenda Hobonichi",
    "Gli sticker per l'agenda","Il washi tape","Lo scrapbooking",
    "Il lettering a mano","Il brush lettering","La calligrafia moderna",
    "Il diamond painting","Il paint by numbers","Il puzzle da 1000 pezzi",
    "I LEGO per adulti","I set LEGO Architecture","I set LEGO Technic",
    "Il modellismo ferroviario","Il Gunpla","Le miniature Warhammer",
    "Il Dungeons & Dragons","I giochi di ruolo da tavolo","Le escape room a casa",
    "Le murder mystery dinner","I quiz in pub","Il trivia night",
    "La serata cinema con proiettore","Il binge watching","Il comfort rewatch",
    "Il rewatch di serie vecchie","Il guilty pleasure televisivo",
    "Le serie true crime","I documentari true crime","I documentari sulla natura",

    # ═══════════════════════════════════════════════════════════════
    # 12. COSE CHE SI MANGIANO A MERENDA (~100)
    # ═══════════════════════════════════════════════════════════════
    "Le merendine del Mulino Bianco","Il Buondì Motta","La Fiesta Ferrero",
    "Il Soldino","Lo Yo-Yo Motta","Il Kinder Cereali",
    "Il Kinder Pinguì","Il Kinder Fetta al Latte","La Girella Motta",
    "Il Tegolino Mulino Bianco","Il Croissant confezionato","Il Plumcake Mulino Bianco",
    "Il Kinder Brioss","Il Kinder Delice","Il Kinder Paradiso",
    "La Merendina Pan di Stelle","Il Grisbì","Il Kinder Colazione Più",
    "La Brioche Mulino Bianco","Il Cornetto Algida a merenda","Il Maxibon",
    "Il Calippo","Il Cremino","Il Winner Taco",
    "Il Twister Algida","La Coppa del Nonno","Il Fior di Fragola",
    "Il Biscotto gelato","Il Sorbettone","Il ghiacciolo alla frutta fatto in casa",
    "La merenda pane e Nutella","La merenda pane e marmellata",
    "La merenda pane burro e zucchero","La merenda pane e olio",
    "La merenda pane e pomodoro","La merenda pane e salame",
    "Le fette biscottate con miele","I cracker col formaggio",
    "I grissini col prosciutto","Le gallette di riso",
    "Le barrette di cereali","Le barrette proteiche","Le barrette Kinder",
    "I Fonzies","I Tuc","Le Ritz crackers",
    "Le Cipster","I Croccantelle","I Pop Corn microonde",
    "Le patatine San Carlo","Le patatine Amica Chips","I taralli pugliesi",
    "I lupini al bar","Le noccioline al bar","Le olive all'ascolana",
    "I supplì","Le crocchette di patate","I mini pizzette surgelate",
    "I salatini misti","Le focaccine surgelate","I bastoncini Findus",
    "Il pane e cioccolato","La fetta di torta della nonna",
    "La crostata fatta in casa","I biscotti fatti in casa",
    "Lo yogurt con i cereali","La frutta a pezzi con limone",
    "La macedonia di frutta","Le fragole con la panna",
    "Le pesche sciroppate","La banana come merenda veloce",
    "La mela come merenda sana","Le carote e hummus",
    "Il sedano col burro di arachidi","I datteri come snack",
    "La frutta secca mista come merenda","Le mandorle tostate",

    # ═══════════════════════════════════════════════════════════════
    # 13. COSE LEGATE AL CALCIO (~100)
    # ═══════════════════════════════════════════════════════════════
    "Il calciatore più pagato del mondo","I procuratori sportivi",
    "Le mogli dei calciatori","Le WAGs","Il Ballon d'Or",
    "La Scarpa d'Oro","La maglia della nazionale",
    "Gli ultras","Le coreografie allo stadio","Il terzo tempo dopo la partita",
    "Il dopopartita al bar","Le conferenze stampa dei mister",
    "Le interviste nel tunnel","Il flash interview dopo il gol",
    "La moviola in TV","Il VAR e le polemiche","La goal line technology",
    "Il fuorigioco semiautomatico","Il fallo tattico","Il cartellino giallo strategico",
    "Il cartellino rosso diretto","Il rigore al 90°","Il gol al 95°",
    "La rimonta da 0-3","La papera del portiere","Il colpo di testa in tuffo",
    "Il gol in rovesciata","Il gol dalla distanza","Il gol olimpico da calcio d'angolo",
    "La punizione alla Del Piero","Il tiro a giro","La trivela alla Quaresma",
    "Il dribbling alla Messi","Lo step over alla Ronaldo","La rabona",
    "Il cucchiaio su rigore","La parata impossibile","Il clean sheet",
    "Il modulo 4-3-3","Il modulo 3-5-2","Il tiki-taka come filosofia",
    "Il catenaccio italiano","Il gegenpressing","Il calcio champagne",
    "Il calcio verticale","Il possesso palla sterile","Il contropiede letale",
    "Il calciomercato di gennaio","La sessione estiva di mercato",
    "Le clausole rescissorie","I prestiti con diritto di riscatto",
    "I giovani delle giovanili","La Primavera come vivaio","Il settore giovanile",
    "Lo scout calcistico","L'agente FIFA","La commissione dell'agente",
    "La Serie B come campionato","La Serie C","La Lega Pro",
    "La Champions League come business","La Conference League",
    "La Europa League","La Supercoppa Italiana","La Coppa Italia",
    "Il Mondiale per Club","Il sorteggio dei gironi","La fase a gruppi",
    "Gli ottavi di finale","La semifinale","La finale ai supplementari",
    "La finale ai rigori","La Supercoppa Europea",
    "La FIFA come organizzazione","La UEFA come organizzazione",
    "Il Fair Play Finanziario","Il salary cap nel calcio",
    "I diritti TV del calcio","L'abbonamento allo stadio",
    "Il biglietto per la curva","Il biglietto per la tribuna",
    "La skybox allo stadio","I seggiolini riscaldati",
    "Lo stadio di proprietà","Lo stadio comunale","Il nuovo stadio di Milano",
    "Il nuovo stadio della Roma","La Serie A femminile",
    "Il campionato femminile mondiale","Le calciatrici come modello",

    # ═══════════════════════════════════════════════════════════════
    # 14. CONCETTI MUSICALI (~100)
    # ═══════════════════════════════════════════════════════════════
    "Il vinile come formato","Il CD come formato","Lo streaming vs il vinile",
    "I concerti nei club piccoli vs i festival","Le prime file al concerto",
    "Il backstage pass","Il meet and greet","Il merchandise dei concerti",
    "La maglietta della band","Il poster del concerto","Il biglietto del concerto come ricordo",
    "Il concerto sotto la pioggia","Il concerto all'aperto d'estate",
    "Il concerto in arena","Il concerto allo stadio","Il concerto al teatro",
    "Il concerto acustico intimo","Il concerto unplugged","Il DJ set al tramonto",
    "Il DJ set in spiaggia","Il festival musicale di tre giorni",
    "Il Coachella","Il Glastonbury","Il Primavera Sound",
    "Il Sonar di Barcellona","Il Tomorrowland come esperienza",
    "Il Rock in Roma","Il Firenze Rocks","Il Lucca Summer Festival",
    "L'Arena di Verona come venue","Il Mediolanum Forum","Il Pala Alpitour",
    "Il concerto sold out","La fila per i biglietti","La prevendita Ticketmaster",
    "I bagarini dei biglietti","Il secondary ticket market","Il biglietto nominale",
    "Il dynamic pricing dei concerti","Il VIP package del concerto",
    "La fossa sotto il palco","Il pit al concerto","Il pogo",
    "Il mosh pit","Il crowd surfing","Lo stage diving",
    "Le canzoni suonate dal vivo diverse dal disco","L'assolo di chitarra dal vivo",
    "Il bis finale del concerto","Il richiamo del pubblico per il bis",
    "Le canzoni vecchie vs le canzoni nuove al concerto",
    "Il fan che conosce tutte le parole","Il fan che filma tutto col telefono",
    "Il divieto di cellulare ai concerti","La busta Yondr per il telefono",
    "I tappi per le orecchie al concerto","L'acufene dopo il concerto",
    "L'audiofilia come hobby","Le cuffie da 500 euro","L'amplificatore valvolare",
    "I diffusori hi-fi","Il DAC portatile","L'equalizzazione del suono",
    "Il suono lossless","Il suono Dolby Atmos nella musica",
    "La spatial audio","Il suono surround in casa","L'home theater",
    "Il giradischi vintage restaurato","I 45 giri","Il 33 giri",
    "La copertina dell'album come arte","Il booklet del CD","Le edizioni deluxe",
    "I box set da collezione","Le ristampe in vinile colorato",
    "Il Record Store Day","Il negozio di dischi indipendente",
    "La colonna sonora del film preferito","La musica nei credits finali",
    "La canzone che rimane in testa","Il tormentone che non sopporti",
    "La canzone della propria infanzia","La canzone del primo amore",
    "La canzone del matrimonio","La prima canzone del DJ al matrimonio",
    "La playlist del matrimonio","La playlist per la palestra",
    "La playlist per cucinare","La playlist per la doccia",
    "La playlist per il viaggio in auto","La playlist discover weekly di Spotify",
    "L'algoritmo di Spotify","Le Spotify Wrapped di fine anno",
]
