#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Expansion 3: Another ~3000+ concepts for the OverUnder deck.
"""

MEGA_EXPANSION_3 = [
    # ─── OGGETTI CHE TUTTI HANNO IN CASA ───
    "Le ciabatte di spugna dell'hotel","Il telecomando della TV",
    "Le pile stilo AA","Il caricatore del telefono","Il cavo USB-C",
    "L'adattatore universale da viaggio","La multipresa con USB",
    "La prolunga elettrica","Il timer per le luci",
    "Il ventilatore da soffitto","Il ventilatore portatile",
    "Il condizionatore portatile","Il deumidificatore",
    "L'umidificatore d'inverno","Il purificatore d'aria",
    "La stufa a pellet","Il camino a bioetanolo",
    "La coperta elettrica","Lo scaldaletto",
    "Il termoventilatore da bagno","L'asciugacapelli",
    "La piastra per capelli","L'arricciacapelli",
    "Il rasoio elettrico","Il regolabarba","L'epilatore elettrico",
    "La bilancia digitale da cucina","La bilancia pesapersone smart",
    "Il termometro digitale","Il misuratore di pressione",
    "Il saturimetro","L'aerosol",

    # ─── COSE DA UFFICIO ───
    "La stampante che non funziona mai","Il toner che finisce sempre",
    "La connessione WiFi instabile","Il monitor esterno",
    "La docking station","Lo standing desk elettrico",
    "La sedia Herman Miller","La sedia Ikea Markus",
    "La lampada da scrivania","Il portapenne","Il post-it colorato",
    "L'evidenziatore giallo","La graffetta","La spillatrice",
    "Lo scotch","La forbice","Il tagliacarte","Il timbro aziendale",
    "La lavagna magnetica","La lavagna cancellabile","Il flip chart",

    # ─── COSE DA VIAGGIO ───
    "Il beauty case da viaggio","L'adattatore di corrente",
    "Il cuscino da viaggio per il collo","La mascherina per dormire",
    "I tappi per le orecchie in aereo","Le calze a compressione per il volo",
    "La borsa porta scarpe","Il portadocumenti da viaggio",
    "La cintura portasoldi","Lo zaino antifurto","La borsa frigo",
    "Il telo mare microbiber","La crema solare SPF 50",
    "Il doposole","L'antizanzare","La citronella",

    # ─── TIPOLOGIE DI FESTE ───
    "Le feste in casa","Le feste in discoteca","Le feste all'aperto",
    "Le feste in piscina","Le feste a tema","Le feste in costume",
    "Le feste anni '80","Le feste anni '90",
    "Le feste di fine anno scolastico","Le feste di fine stagione sportiva",
    "Le feste di quartiere","Le feste patronali",
    "Le feste di paese con fuochi d'artificio",
    "I falò di San Giovanni","La notte di San Lorenzo",
    "Le stelle cadenti di agosto","I desideri espressi sulle stelle",

    # ─── FENOMENI METEO DISCUSSI ───
    "Il temporale estivo","Il temporale con grandine",
    "L'allerta meteo arancione","L'allerta meteo rossa",
    "La nebbia padana","La foschia mattutina",
    "L'umidità soffocante","Il caldo secco del deserto",
    "Il vento forte in montagna","La brezza marina serale",
    "L'arcobaleno dopo la pioggia","Il cielo stellato in montagna",
    "L'alba sul mare","Il tramonto in campagna",

    # ─── CONCETTI DI BENESSERE MENTALE ───
    "La terapia cognitivo-comportamentale","La psicanalisi",
    "Lo psicologo online vs in presenza","Le app di salute mentale",
    "La meditazione guidata","La mindfulness","Il breathwork",
    "Lo yoga kundalini","Lo yoga vinyasa","Lo yoga yin",
    "Il tai chi","Il qi gong","La riflessologia plantare",
    "La cristalloterapia","L'aromaterapia",
    "I fiori di Bach","La naturopatia",
    "L'ayurveda","La medicina tradizionale cinese",

    # ─── TIPI DI SPORT CHE PUOI FARE ───
    "La camminata veloce","La camminata nordica",
    "Il nordic walking","L'escursionismo","Il trekking urbano",
    "La corsa in pista","La corsa campestre",
    "Il nuoto in acque libere","Il triathlon sprint",
    "La bici da strada","La mountain bike elettrica",
    "La gravel bike","La bici pieghevole in città",
    "Il pattinaggio in linea","Il roller derby",
    "Lo skateboard street","Lo skateboard vert",
    "Il longboard per cruising","La tavola da surf",
    "Il bodyboard","Il SUP (Stand Up Paddle)",
    "Il SUP yoga","La canoa kayak","Il rafting",
    "Il canyoning","l'hydrospeed","il coasteering",

    # ─── CONCETTI DI MODA SPECIFICI ───
    "Il total look Gucci","Le borse tote bag",
    "Le tote bag in tela con scritte","Gli shopper di marca",
    "Le borse a tracolla piccole","Le mini bag",
    "Le maxi bag","I portafogli da uomo","I portafogli da donna",
    "Le cinture di marca","Le cinture in cuoio artigianale",
    "Le cravatte","I papillon","Le pochette da sera",
    "I foulard di seta","Le sciarpe Burberry",
    "I cappelli Panama","I berretti","Le coppole siciliane",
    "I cappellini da baseball","I bucket hat","Le fascette per capelli",
    "I fermagli vintage","Le fasce per capelli sportive",

    # ─── COSE CHE CAPITANO IN AUTO ───
    "Il traffico del venerdì sera","La coda in tangenziale",
    "Il semaforo che diventa rosso appena arrivi",
    "Il parcheggio trovato al primo giro",
    "La multa per divieto di sosta","La multa dell'autovelox",
    "Il graffio sulla macchina nuova","Il lavaggio auto a mano",
    "L'autolavaggio automatico","L'albero magico al retrovisore",
    "La musica a tutto volume in macchina",
    "Cantare in macchina da soli","Il carpool con i colleghi",
    "L'autista che non supera mai","L'autista che supera tutti",
    "Guidare con il finestrino abbassato","Il navigatore che sbaglia strada",

    # ─── CIBI DA FAST FOOD ───
    "Il Big Mac","Il Whopper","Il panino del McDonald's",
    "Le McNuggets","Le patatine del McDonald's",
    "Il McFlurry","L'Happy Meal","Il McChicken",
    "Il panino di Five Guys","L'hamburger gourmet da 18 euro",
    "L'hamburger classico con ketchup","L'hamburger con avocado",
    "L'hamburger vegetariano","L'hamburger impossibile",
    "Il beyond burger","L'hot dog americano","L'hot dog danese",
    "Le ali di pollo fritte","Le chicken wings piccanti",
    "Le onion rings","I mozzarella sticks",
    "La Caesar salad","L'insalata mista dal fast food",

    # ─── PIATTI DELLA DOMENICA ───
    "Il ragù della domenica","Le polpette al sugo della nonna",
    "L'arrosto con patate","Il pollo arrosto della domenica",
    "Le lasagne della domenica","I cannelloni ripieni",
    "I tortellini in brodo della domenica","La pasta al forno",
    "Il timballo di pasta","La teglia di verdure al forno",
    "Le melanzane alla parmigiana","Le zucchine alla scapece",
    "Le patate al forno croccanti","L'insalata russa",
    "Il vitello tonnato della domenica","Il bollito misto con mostarda",
    "Il brasato al Barolo","Lo stracotto","Il gulash",
    "L'ossobuco alla milanese","La cotoletta alla milanese",
    "La costoletta alla milanese alta",

    # ─── DOLCI DELLA TRADIZIONE ───
    "Il tiramisù della nonna","Il budino della mensa",
    "La torta della nonna con crema e pinoli",
    "La torta paradiso","La torta Margherita",
    "La sbrisolona mantovana","La torta Barozzi",
    "Il panforte senese","I ricciarelli","I cavallucci",
    "Le frittelle veneziane","Le fritole","I krapfen",
    "Le castagnole","Le chiacchiere di Carnevale",
    "La crostata ricotta e visciole","La pastiera","Il babà",
    "Il rum babà mignon","La sfogliatella riccia",
    "La sfogliatella frolla","Il cornetto napoletano",
    "Il graffa napoletana","La zeppola fritta",

    # ─── PERSONAGGI DEI SOCIAL ───
    "Gli chef che cucinano su TikTok","I fitness influencer",
    "Le beauty guru","Gli influencer di viaggi",
    "I book influencer su Instagram","I booktoker su TikTok",
    "I gamer su YouTube","Gli speedrunner","I pro player di esports",
    "I commentatori di calcio su YouTube","I giornalisti sportivi su Twitter",
    "I meme page admin","Gli artisti digitali su Instagram",
    "I musicisti indipendenti su Spotify","Gli artisti su SoundCloud",
    "I creator su Patreon","Gli streamer su Twitch italiani",

    # ─── CONCETTI EDUCATIVI ───
    "Il metodo di studio","Le mappe concettuali",
    "I riassunti scritti a mano","Gli appunti digitali su tablet",
    "Le flashcard per studiare","Anki per la memorizzazione",
    "Il metodo Pomodoro","Il deep work","La tecnica Feynman",
    "Lo studio di gruppo vs lo studio individuale",
    "Studiare in biblioteca","Studiare al bar",
    "Studiare con la musica","Studiare in silenzio",
    "Studiare la notte prima dell'esame",
    "La sessione d'esami di gennaio","La sessione estiva",
    "La sessione autunnale di recupero","I 30 e lode",
    "Il 18 politico","La media del 27","La lode alla laurea",

    # ─── ANIMALI DOMESTICI E CURA ───
    "Il gatto che dorme sul letto","Il gatto che graffia il divano",
    "Il cane che abbaia ai passanti","Il cane che tira al guinzaglio",
    "Il cane che aspetta alla porta","Il gatto che porta topi in regalo",
    "Il cane che ruba il cibo dalla tavola","Il gatto indifferente",
    "Il cane festoso","Le coccole al gatto","Le passeggiate col cane",
    "Il veterinario di fiducia","Le vaccinazioni dei pet",
    "Il cibo per animali premium","Il cibo per animali del supermercato",
    "I giochi per gatti","I giochi per cani",
    "Le cucce morbide","I tiragraffi per gatti",
    "Il guinzaglio retrattile","Le pettorine per cani",
    "Il microchip per animali","L'assicurazione per animali",

    # ─── COSE DI CONDOMINIO ───
    "L'assemblea di condominio","L'amministratore di condominio",
    "Le spese condominiali","Il riscaldamento centralizzato",
    "Il portiere dello stabile","L'ascensore del palazzo",
    "Le scale a piedi vs l'ascensore","I bidoni della differenziata",
    "Il garage condominiale","Il posto auto assegnato",
    "Le piante nel giardino condominiale","La piscina condominiale",
    "Il campo da tennis condominiale","La sala hobby del condominio",
    "Il regolamento condominiale","Le liti tra vicini",
    "Il rumore dei vicini di sopra","La musica alta del vicino",
    "Il cane del vicino che abbaia","L'odore di cucina del vicino",

    # ─── SHOPPING SPECIFICO ───
    "I saldi Zara","I saldi H&M","Le offerte Amazon Prime Day",
    "Le offerte del Black Friday","I coupon sconto",
    "Le app di cashback","Uala per prenotare trattamenti beauty",
    "Le gift card","I buoni regalo Amazon",
    "I buoni regalo Decathlon","I buoni regalo Ikea",
    "Le carte regalo Spotify","Le carte regalo Netflix",
    "Le carte regalo PlayStation Store","Le carte regalo Steam",
    "Le carte regalo App Store","Le carte regalo Google Play",

    # ─── CONCETTI DI TRASPORTO PUBBLICO ───
    "L'abbonamento mensile dei mezzi","Il biglietto singolo del bus",
    "La metro affollata all'ora di punta","Il bus in ritardo",
    "Il treno regionale affollato","Il treno alta velocità Frecciarossa",
    "Il Frecciarossa vs l'Italo","L'Italo","Trenitalia vs Italo",
    "Il posto prenotato occupato","Il vagone silenzio",
    "La prima classe del treno vs la seconda",
    "Il bar del treno","La carrozza ristorante",
    "Le coincidenze perse","Il treno cancellato per sciopero",
    "Lo sciopero dei trasporti","Il servizio sostitutivo con bus",

    # ─── COSE CHE SUCCEDONO ONLINE ───
    "La password dimenticata","Il codice OTP che non arriva",
    "Il sito che va in crash","Il caricamento infinito",
    "La connessione lenta","Il WiFi dell'hotel che non funziona",
    "Il WiFi gratuito del bar","L'hotspot dal telefono",
    "La batteria del telefono al 1%","Il caricatore portatile scarico",
    "L'aggiornamento del telefono che rallenta tutto",
    "Lo spazio esaurito sul telefono","Le foto da cancellare per fare spazio",
    "Il backup del telefono","Cambiare telefono e perdere le chat",
    "Le chat WhatsApp archiviate","I messaggi non letti",

    # ─── TIPI DI CAFFÈ ───
    "Il caffè espresso al banco","Il caffè al tavolo che costa il doppio",
    "Il caffè doppio","Il caffè macchiato caldo",
    "Il caffè macchiato freddo","Il caffè con ghiaccio",
    "Il caffè shakerato estivo","Il caffè in vetro",
    "Il caffè al volo in stazione","Il caffè da 1 euro del bar sport",
    "Il caffè da 6 euro di Starbucks","Il caffè specialty",
    "Il caffè filtro americano","Il caffè turco",
    "Il caffè vietnamita col latte condensato",

    # ─── TIPI DI PIZZA ───
    "La pizza margherita classica","La pizza marinara","La pizza quattro stagioni",
    "La pizza quattro formaggi","La pizza diavola","La pizza capricciosa",
    "La pizza prosciutto e funghi","La pizza bufala e pomodorini",
    "La pizza con la burrata","La pizza con il tartufo",
    "La pizza con le patatine fritte sopra","La pizza con le wurstel",
    "La pizza bianca","La pizza focaccia","La pizza al metro",
    "La pizza gourmet da 18 euro","La pizza da asporto",
    "La pizza surgelata","La pizza fatta in casa",
    "La pizza col cornicione ripieno","La pizza a portafoglio napoletana",
    "La pizza a canotto","La pizza col lievito madre",

    # ─── TIPI DI PASTA ───
    "Gli spaghetti","Le penne rigate","I rigatoni",
    "I fusilli","Le farfalle","Le orecchiette",
    "I paccheri","Le mezze maniche","I bucatini",
    "Le tagliatelle","Le pappardelle","I tortellini",
    "I ravioli","Gli gnocchi","Le lasagne",
    "I cannelloni","Le trofie","I pici",
    "La pasta fresca vs la pasta secca","La pasta integrale",
    "La pasta di legumi","La pasta senza glutine",
    "La pasta di riso","La pasta di farro",
    "La pasta con la cottura al dente vs scotta",
    "La pasta risottata","La pasta mantecata",

    # ─── PERSONAGGI ICONICI DELLA CULTURA POP ───
    "Mario (Nintendo)","Pikachu","Pac-Man","Sonic",
    "Mickey Mouse","Homer Simpson","SpongeBob","Goku",
    "Naruto Uzumaki","Luffy di One Piece",
    "Harry Potter come personaggio","Gandalf","Frodo",
    "Darth Vader","Yoda","Indiana Jones come personaggio",
    "James Bond come personaggio","Batman come personaggio",
    "Spider-Man come personaggio","Wolverine",
    "Wonder Woman","Superman come personaggio",
    "Joker come personaggio","Thanos","Deadpool come personaggio",
    "Sherlock Holmes","Don Vito Corleone","Tony Montana",
    "Tyler Durden","Walter White","Tony Soprano",

    # ─── GENERI MUSICALI SPECIFICI ───
    "L'indie rock","L'indie pop","Il dream pop",
    "Lo shoegaze","Il post-punk","Il synth-pop",
    "Il new wave","L'electropop","La vaporwave",
    "Il lo-fi hip hop","Il boom bap","Il drill",
    "La dark trap","Il cloud rap","Il phonk",
    "L'hyperpop","Il bedroom pop","L'emo rap",
    "Il nu metal","Il metalcore","Il deathcore",
    "Il progressive metal","Il djent","Il math rock",
    "Il post-rock","L'ambient music","Il drone music",
    "La psytrance","l'hardstyle","La hardcore techno",
    "La gabber","L'eurodance","L'italo disco",

    # ─── COSE CHE FAI AL COMPUTER ───
    "Avere 50 tab aperte nel browser","La cronologia di navigazione",
    "La modalità incognito","Il dark mode su tutto",
    "Le scorciatoie da tastiera","Il copia-incolla",
    "Il CTRL+Z (annulla)","L'Alt+Tab","Il doppio schermo",
    "Il desktop organizzato","Il desktop pieno di file",
    "La cartella Download mai svuotata","I file sul desktop",
    "L'aggiornamento di Windows nel momento peggiore",
    "Il riavvio forzato del computer","La schermata blu di Windows",
    "Il Mac vs il PC","Chrome vs Firefox vs Safari vs Edge",

    # ─── COSE CHE FAI COL TELEFONO ───
    "I filtri di Instagram sulle foto","Le foto ritoccate",
    "Le foto in modalità ritratto","Le foto panoramiche",
    "I time-lapse col telefono","Gli slow motion","Le live photo",
    "Le foto al cibo prima di mangiare","Le foto in palestra",
    "I selfie allo specchio","I selfie di gruppo",
    "Le foto al tramonto","Le foto in aereo dal finestrino",
    "Le foto delle vacanze","Le foto del viaggio per i social",

    # ─── CONCETTI DI DESIGN E ARCHITETTURA ───
    "L'architettura brutalista","L'architettura gotica",
    "L'architettura barocca","L'architettura rinascimentale",
    "L'architettura moderna","L'architettura contemporanea",
    "I grattacieli","Le case di vetro","Le case passive",
    "Le case ecologiche","Le case prefabbricate",
    "Le case modulari","I container abitativi",
    "Le tiny house","Le case galleggianti","Le case sotterranee",
    "Il design scandinavo","Il design italiano","Il design giapponese",
    "Il design industrial","Il design Memphis","Il design Art Deco",

    # ─── FENOMENI NATURALI IMPRESSIONANTI ───
    "L'aurora boreale in Norvegia","L'aurora australe",
    "I geyser in Islanda","Le cascate del Niagara",
    "Le cascate dell'Iguazú","Le cascate Vittoria",
    "Il Gran Canyon dall'alto","La Great Blue Hole",
    "Il Mar Morto","I laghi rosa","Le grotte di ghiaccio",
    "Le grotte luminose della Nuova Zelanda","I fiori di ciliegio in Giappone",
    "La fioritura dei tulipani in Olanda","La fioritura della lavanda in Provenza",
    "I campi di girasole","Il foliage autunnale",

    # ─── ATTIVITÀ PER BAMBINI ───
    "I parchi giochi","Gli scivoli acquatici",
    "Le piscine a palline","I trampolini elastici",
    "Le feste di compleanno al McDonald's","Le feste al parco giochi",
    "Le feste con l'animatore","Le feste con il mago",
    "I laboratori creativi per bambini","I corsi di nuoto per bambini",
    "I corsi di musica per bambini","I corsi di inglese per bambini",
    "I cartoni animati della Disney","I cartoni Pixar per bambini",
    "Le fiabe della buonanotte","I libri pop-up",

    # ─── COSE DEGLI ANNI 2000 ───
    "I jeans a vita bassa anni 2000","Le felpe Abercrombie",
    "Le Converse basse scritte","Le All Star alte",
    "I braccialetti dell'amicizia","I braccialetti in gomma colorati",
    "Le collane con il ciondolo a cuore spezzato",
    "I piercing all'ombelico","I capelli colorati a ciocche",
    "I capelli con le meches","Le treccine rasta in vacanza",
    "I tatuaggi tribali","Le farfalle come simbolo",
    "Il glitter sugli occhi","Il lipgloss lucido",
    "Le MySpace pages","I blog su Splinder",
    "Windows XP","Il suono di avvio di Windows XP",
    "L'ICQ","IRC","I forum phpBB",
    "eMule per scaricare musica","Napster","LimeWire",
    "I masterizzatori di CD","I lettori MP3 cinesi",
    "Le suonerie polifoniche","Gli sfondi animati del telefono",
    "I Nokia indistruttibili","Il T9 per scrivere messaggi",
    "Gli SMS da 160 caratteri","Gli MMS",

    # ─── COSE DEGLI ANNI '90 ───
    "Le Spice Girls","I Backstreet Boys","NSYNC",
    "I Tamagotchi","I Furby","Le Polly Pocket",
    "Le Barbie","I soldatini","Le Micro Machines",
    "I Power Rangers","Le Tartarughe Ninja","Dragon Ball Z in TV",
    "Pokémon in TV","I Digimon","Le figurine Panini",
    "L'album dei Pokémon","Lo yo-yo","Il frisbee",
    "I pattini a rotelle","Il Gameboy","Il Super Nintendo",
    "Il Sega Mega Drive","La PlayStation 1","Il Nintendo 64",
    "Crash Bandicoot","Spyro il drago","Tekken",
    "Street Fighter","Mortal Kombat","Tomb Raider",
    "Final Fantasy VII nel '97","Metal Gear Solid nel '98",
    "I film di Disney rinascimentale","Il Re Leone","Aladdin",
    "La Sirenetta","La Bella e la Bestia","Hercules",
    "Mulan","Il Gobbo di Notre-Dame",

    # ─── COSE DEGLI ANNI '80 ───
    "Gli anni '80 come decennio","La musica synth-pop degli '80",
    "Michael Jackson negli '80","Madonna negli '80",
    "I film di John Hughes","I Goonies","Ritorno al Futuro",
    "E.T. l'extra-terrestre","Ghostbusters","Top Gun originale",
    "Rambo negli '80","Rocky negli '80","Indiana Jones negli '80",
    "Le VHS e i videonoleggi","Il walkman Sony","Le audiocassette",
    "I capelli cotonati","Le spalline nei vestiti","I leggins fluorescenti",
    "Le scaldamuscoli","L'aerobica di Jane Fonda",
    "Il cubo di Rubik","Il Pac-Man arcade",
    "Il Commodore 64","Lo ZX Spectrum","L'Atari",
    "I Drive-In","Le sale giochi arcade",

    # ─── MUSICA ITALIANA SPECIFICA ───
    "La canzone dell'estate","Il tormentone estivo",
    "Il vinile di Battisti","Il vinile di De André",
    "Il concerto di Vasco a Modena Park","Il concerto di Ligabue a Campovolo",
    "La canzone di Sanremo che vince","La canzone di Sanremo che doveva vincere",
    "Il televoto a Sanremo","La giuria di qualità a Sanremo",
    "Le polemiche post-Sanremo","Il vincitore di Sanremo all'Eurovision",
    "L'Italia all'Eurovision","I Måneskin all'Eurovision",
    "La trap italiana vs il rap italiano","Il rap old school vs il nuovo rap",
    "La musica italiana vs la musica americana",
    "Il karaoke con le canzoni italiane","Le canzoni per il falò in spiaggia",
    "Le canzoni da viaggio in macchina",

    # ─── COSE RELIGIOSE E SPIRITUALI ───
    "Il Natale come festa religiosa vs commerciale",
    "La Pasqua come festa religiosa vs commerciale",
    "Il Ramadan","Hanukkah","Il Diwali",
    "Lo yoga come pratica spirituale","La meditazione trascendentale",
    "Il buddismo zen","Il taoismo come filosofia di vita",
    "L'astrologia come guida di vita","I tarocchi",
    "La lettura della mano","La sfera di cristallo",
    "I sogni premonitori","Le coincidenze significative",
    "La legge dell'attrazione","Il pensiero positivo",
    "La visualizzazione creativa","Le affermazioni positive",

    # ─── CONCETTI DI BELLEZZA ───
    "La skincare routine in 10 step","La skincare minimalista",
    "Il siero alla vitamina C","L'acido ialuronico per il viso",
    "La crema contorno occhi","La crema antirughe",
    "Il retinolo","La protezione solare quotidiana",
    "Il trucco naturale","Il trucco pesante per la sera",
    "Il trucco no makeup look","Le sopracciglia laminate",
    "La micropigmentazione delle sopracciglia",
    "Le ciglia finte","Le extension ciglia",
    "Il mascara waterproof","Il rossetto rosso",
    "Il rossetto nude","Il lip liner over-lined",
    "Il contouring","lo strobing","l'highlighting",
    "Le unghie corte e naturali","Le unghie lunghe e decorate",
    "Le unghie French manicure","Le unghie gel semipermanente",
    "I profumi di nicchia","I profumi commerciali",
    "I profumi da uomo","I profumi unisex",
    "Il deodorante spray vs roll-on vs stick",
    "I capelli naturali vs trattati",
    "La tinta per capelli","Le schiariture naturali",
    "Il balayage","Lo shatush","Le punte colorate",
    "I capelli platino","I capelli rosa","I capelli blu",

    # ─── SUPERSTIZIONI ITALIANE ───
    "Il malocchio","Il corno portafortuna",
    "Il numero 13 sfortunato","Il numero 17 sfortunato in Italia",
    "Passare sotto una scala","Il gatto nero che attraversa la strada",
    "Rompere uno specchio sette anni di sfortuna",
    "Il sale versato sulla tavola","L'ombrello aperto in casa",
    "Il tredici a tavola","Venerdì 17","Toccare ferro",
    "Il ferro di cavallo appeso sulla porta","Il quadrifoglio",
    "La coccinella portafortuna","Le stelle cadenti e i desideri",

    # ─── COSE CHE CAPITANO IN TRENO ───
    "Il posto finestrino in treno","Il posto corridoio",
    "Il sedile al contrario della marcia","Il tavolino in treno",
    "La presa elettrica che non funziona","Il WiFi del treno lentissimo",
    "Il vagone silenzio dove parlano tutti",
    "Il controllore che passa tre volte","Il biglietto non validato",
    "Il treno in ritardo di 30 minuti","Il treno cancellato",
    "Il cambio binario all'ultimo momento","La coincidenza persa per 2 minuti",
    "Lo sciopero dei treni il venerdì",

    # ─── COSE CHE CAPITANO IN AEREO ───
    "Il check-in online","Il self check-in in aeroporto",
    "La carta d'imbarco digitale","I controlli di sicurezza",
    "Il duty free dell'aeroporto","L'attesa al gate",
    "Il gate cambiato all'ultimo","L'imbarco prioritario",
    "La valigia nel vano sopra la testa","La valigia sotto il sedile",
    "Il decollo","L'atterraggio","La turbolenza",
    "Il pasto in aereo","L'applauso all'atterraggio in Italia",
    "L'attesa del bagaglio al nastro","La valigia persa",
]
