MEGA_EXPANSION_6 = [
    # ============================================================
    # 1. TIPI DI MUSICA E ARTISTI (~200)
    # ============================================================
    "Il disco funk",
    "Il smooth jazz",
    "Il latin jazz",
    "Il bossa nova",
    "La samba brasiliana",
    "Il tango argentino",
    "Il flamenco nuevo",
    "La world music",
    "L'afrobeat nigeriano",
    "Il highlife ghanese",
    "L'amapiano sudafricano",
    "Il dancehall giamaicano",
    "Il roots reggae",
    "Lo dub",
    "Il dubstep",
    "Il drum and bass",
    "La jungle",
    "Il garage UK",
    "Il grime",
    "Il trap UK",
    "Il neo soul",
    "Il contemporary R&B",
    "Il quiet storm",
    "La motown classica",
    "Il philly soul",
    "Il northern soul",
    "Il southern soul",
    "Il gospel contemporaneo",
    "Lo spiritual tradizionale",
    "Il blues del Delta",
    "Il Chicago blues",
    "Il Texas blues",
    "Il boogie woogie",
    "Il rockabilly",
    "Il surf rock",
    "Il garage rock",
    "Lo stoner rock",
    "Il doom metal",
    "Il black metal norvegese",
    "Il death metal svedese",
    "Il thrash metal",
    "Il power metal",
    "Il symphonic metal",
    "Il folk metal",
    "Il viking metal",
    "Il metalcore",
    "Il deathcore",
    "Il post-hardcore",
    "Lo screamo",
    "L'emo revival",
    "Il math rock",
    "Il noise rock",
    "Lo shoegaze",
    "Il dream pop",
    "Il chillwave",
    "Il vaporwave",
    "Il synthwave",
    "Il retrowave",
    "Il darkwave",
    "L'EBM",
    "L'industrial",
    "La techno di Detroit",
    "La techno di Berlino",
    "La minimal techno",
    "L'acid house",
    "La deep house",
    "La progressive house",
    "La tech house",
    "L'Afro house",
    "La melodic techno",
    "Il trance",
    "Il psytrance",
    "L'uplifting trance",
    "L'hardstyle",
    "La gabber",
    "L'happy hardcore",
    "Il breakbeat",
    "Il trip hop",
    "Il downtempo",
    "L'ambient",
    "Il dark ambient",
    "La musica drone",
    "Il glitch",
    "L'IDM",
    "Il footwork di Chicago",
    "Il baile funk brasiliano",
    "Il cumbia digitale",
    "La cumbia villera",
    "Il reggaeton classico",
    "Il dembow",
    "Il trap latino",
    "Il latin pop",
    "La bachata moderna",
    "Il merengue",
    "La salsa cubana",
    "Il son cubano",
    "La timba",
    "Il mariachi",
    "Il norteño",
    "La banda sinaloense",
    "Il corrido tumbado",
    "La musica tejana",
    "Il K-pop",
    "Il J-pop",
    "Il J-rock",
    "Il visual kei",
    "Il city pop giapponese",
    "Il Cantopop",
    "Il Mandopop",
    "La musica indiana Bollywood",
    "Il bhangra",
    "Il qawwali pakistano",
    "La musica rai algerina",
    "Il chaabi marocchino",
    "La musica gnawa",
    "Il mbalax senegalese",
    "Il soukous congolese",
    "Il kizomba angolana",
    "Il semba",
    "Il kuduro",
    "Il fado portoghese",
    "Il rebetiko greco",
    "Il turbofolk",
    "Il chalga bulgaro",
    "La manele rumena",
    "Il klezmer",
    "La musica celtica",
    "Il folk irlandese",
    "Il country alternativo",
    "L'americana",
    "Il bluegrass",
    "Il country pop",
    "Il country tradizionale",
    "L'outlaw country",
    "Il cantautorato francese",
    "La chanson française",
    "Il Neue Deutsche Welle",
    "Il Krautrock",
    "Lo Schlager tedesco",
    "La musica neomelodica",
    "Il liscio romagnolo",
    "La pizzica salentina",
    "La taranta",
    "Il canto a tenore sardo",
    "La musica popolare napoletana",
    "Il cantautorato genovese",
    "Il cantautorato bolognese",
    "Il cantautorato romano",
    "L'indie italiano anni 2000",
    "L'indie italiano contemporaneo",
    "Il rap napoletano",
    "Il rap romano",
    "Il rap milanese",
    "Il rap torinese",
    "Il rap siciliano",
    "La scena trap italiana",
    "Il pop punk italiano",
    "L'hardcore punk italiano",
    "Lo ska italiano",
    "Il reggae italiano",
    "L'italo disco",
    "L'Eurodance anni '90",
    "La dance commerciale",
    "Le hit da villaggio turistico",
    "Le canzoni dei tormentoni estivi",
    "Le sigle dei cartoni animati",
    "Le canzoni dello Zecchino d'Oro",
    "Le canzoni di Sanremo anni '60",
    "Le canzoni di Sanremo anni '70",
    "Le canzoni di Sanremo anni '80",
    "Le canzoni di Sanremo anni '90",
    "Il nuovo cantautorato italiano",
    "La scena bedroom pop italiana",
    "Il lo-fi hip hop per studiare",
    "La musica da meditazione",
    "I suoni della natura per dormire",
    "L'ASMR musicale",
    "Le playlist algoritmiche",
    "Il Discover Weekly di Spotify",
    "Le playlist collaborative",
    "Il vinile da collezione",
    "Le cassette in edizione limitata",
    "I concerti unplugged",
    "I live session in studio",
    "Le Tiny Desk Concert",
    "I battle rap freestyle",
    "Le cypher rap",
    "Il beatmaking casalingo",
    "I beat lo-fi",
    "I beat drill",
    "La phonk music",
    "L'hyperpop",
    "Il digicore",
    "Il pluggnb",
    "La Jersey club music",
    "Il bounce di New Orleans",
    "La crunk music",
    "Lo snap music",
    "Il cloud rap",
    "Il mumble rap",
    "Il conscious rap",
    "Il rap politico",
    "Il jazz rap",
    "L'abstract hip hop",
    "Il boom bap classico",
    "Il G-funk",

    # ============================================================
    # 2. COSE DELL'UFFICIO POSTALE E BUROCRAZIA (~100)
    # ============================================================
    "Lo SPID",
    "La PEC",
    "La firma digitale",
    "La carta d'identità elettronica",
    "Il passaporto elettronico",
    "La patente digitale",
    "Il fascicolo sanitario elettronico",
    "L'ISEE",
    "La DSU",
    "Il CAF",
    "Il patronato",
    "L'INPS online",
    "L'Agenzia delle Entrate",
    "L'F24",
    "Il modello 730",
    "Il CUD",
    "La busta paga",
    "I contributi pensionistici",
    "La raccomandata con ricevuta di ritorno",
    "Il pacco postale",
    "La lettera raccomandata",
    "La posta prioritaria",
    "Il telegramma",
    "Il bollettino postale",
    "Il conto corrente postale",
    "La PostePay",
    "La PostePay Evolution",
    "Il libretto postale",
    "I buoni fruttiferi postali",
    "L'ufficio postale del paese",
    "La coda all'ufficio postale",
    "Il numeretto per la fila",
    "Lo sportello dedicato agli anziani",
    "Il ritiro pacco in giacenza",
    "L'avviso di giacenza nella buca",
    "Il portalettere",
    "Il postino di quartiere",
    "La cassetta delle lettere condominiale",
    "Il cambio di residenza",
    "L'anagrafe comunale",
    "Lo stato di famiglia",
    "Il certificato di residenza",
    "Il certificato di nascita",
    "Il certificato penale",
    "L'autocertificazione",
    "La dichiarazione sostitutiva",
    "Il bollo da 16 euro",
    "La marca da bollo digitale",
    "Il protocollo informatico",
    "La posta certificata della PA",
    "Il portale INPS",
    "La domanda di disoccupazione",
    "La NASpI",
    "Il reddito di cittadinanza",
    "L'assegno unico universale",
    "Il bonus 18enni",
    "Il bonus cultura",
    "I bonus edilizi",
    "Il Superbonus 110%",
    "La cessione del credito fiscale",
    "Lo sconto in fattura",
    "La detrazione fiscale",
    "La deduzione fiscale",
    "La dichiarazione dei redditi precompilata",
    "Il cassetto fiscale",
    "La fattura elettronica",
    "Lo SDI (Sistema di Interscambio)",
    "La partita IVA",
    "Il regime forfettario",
    "Il regime ordinario",
    "La visura camerale",
    "La visura catastale",
    "Il catasto digitale",
    "L'atto notarile",
    "La voltura catastale",
    "La SCIA (Segnalazione Certificata di Inizio Attività)",
    "Il permesso di costruire",
    "La DIA edilizia",
    "Il condono edilizio",
    "L'APE (Attestato Prestazione Energetica)",
    "Il codice fiscale",
    "La tessera sanitaria",
    "Il medico di base",
    "La scelta del pediatra",
    "La ricetta medica elettronica",
    "Il ticket sanitario",
    "L'esenzione dal ticket",
    "La lista d'attesa in sanità pubblica",
    "Il CUP (Centro Unico Prenotazioni)",
    "La prenotazione online al SSN",
    "Il fascicolo del cittadino digitale",
    "L'app IO della pubblica amministrazione",
    "La piattaforma PagoPA",
    "Il sistema ANPR",
    "La carta dei servizi",
    "Il difensore civico",
    "Il ricorso al TAR",
    "L'accesso agli atti pubblici",
    "Il FOIA italiano",
    "La trasparenza amministrativa",
    "L'albo pretorio online",
    "Il DURC (Documento Unico di Regolarità Contributiva)",

    # ============================================================
    # 3. TIPI DI DOLCI E GELATI (~150)
    # ============================================================
    "Il gelato alla crema",
    "Il gelato alla vaniglia",
    "Il gelato al cioccolato fondente extra",
    "Il gelato al cocco",
    "Il gelato alla menta con scaglie",
    "Il gelato al torroncino",
    "Il gelato al bacio",
    "Il gelato al tiramisù",
    "Il gelato alla Nutella",
    "Il cono vs la coppetta",
    "La panna sul gelato",
    "Il gelato con la brioche",
    "Il biscotto gelato",
    "Il Calippo",
    "Il Cornetto Algida classico",
    "Il Magnum classico",
    "Il Magnum mandorle",
    "Il Solero",
    "La Coppa del Nonno",
    "Il Tartufo gelato",
    "Lo stecco ricoperto di cioccolato",
    "Il ghiacciolo alla frutta",
    "Il sorbetto al limone",
    "Il sorbetto al mango",
    "Il sorbetto alla fragola",
    "La granita siciliana al caffè",
    "La granita siciliana alla mandorla",
    "La granita con panna e brioche",
    "La grattachecca romana",
    "Il gelato artigianale vs industriale",
    "La gelateria di quartiere",
    "Il gelato alla stracciatella",
    "Il gelato alla nocciola piemontese",
    "Il gelato al pistacchio di Bronte",
    "Il gelato alla ricotta e fichi",
    "Il gelato al caramello salato",
    "Il gelato ai frutti di bosco",
    "Il gelato al mango",
    "Il gelato allo yogurt",
    "Il gelato alla liquirizia",
    "Il gelato al caffè",
    "Il gelato alla panna cotta",
    "Il gelato al malaga",
    "Il gelato allo zabaione",
    "Il tiramisù classico",
    "Il tiramisù alle fragole",
    "Il tiramisù al pistacchio",
    "La panna cotta",
    "La panna cotta ai frutti di bosco",
    "Il budino al cioccolato",
    "Il budino alla vaniglia",
    "Il crème caramel",
    "Il crème brûlée",
    "La mousse al cioccolato",
    "La mousse al caffè",
    "Lo zabaione caldo",
    "La zuppa inglese",
    "Il semifreddo al torroncino",
    "Il semifreddo al caffè",
    "La cassata siciliana",
    "Il cannolo siciliano",
    "I cannoli mignon",
    "La sfogliatella riccia",
    "La sfogliatella frolla",
    "Il babà napoletano",
    "Il babà al rum",
    "La pastiera napoletana",
    "La delizia al limone",
    "Il profitterol",
    "La millefoglie",
    "La crostata alla frutta",
    "La crostata alla marmellata",
    "La crostata alla Nutella",
    "La torta della nonna",
    "La torta di mele classica",
    "La torta caprese",
    "La torta Sacher",
    "La torta Dobos",
    "La torta al cioccolato fondente",
    "La cheesecake classica",
    "La cheesecake ai frutti di bosco",
    "La cheesecake giapponese",
    "Il macarons francese",
    "L'éclair al cioccolato",
    "Il pain au chocolat",
    "Il croissant alla crema",
    "Il croissant al pistacchio",
    "La brioche siciliana col tuppo",
    "I bignè alla crema",
    "Le zeppole di San Giuseppe",
    "I maritozzi con la panna",
    "Le castagnole di Carnevale",
    "Le frappe di Carnevale",
    "Gli struffoli napoletani",
    "Il panforte senese",
    "Il ricciarello di Siena",
    "I cavallucci toscani",
    "Il cantucci col Vin Santo",
    "I biscotti della Mulino Bianco",
    "Il Pan di Stelle",
    "I Gocciole",
    "I Galletti",
    "I Ringo",
    "Gli Oreo",
    "I wafer alla nocciola",
    "Il Kinder Fetta al Latte",
    "Il Kinder Bueno",
    "Il Kinder Pinguì",
    "Il Kinder Delice",
    "La merendina del Mulino Bianco",
    "La Fiesta Ferrero",
    "La Girella Motta",
    "Il Tegolino",
    "La torta Paradiso",
    "Il salame di cioccolato",
    "I tartufi al cioccolato",
    "Le praline assortite",
    "I cioccolatini artigianali",
    "Il fondente 70% cacao",
    "Il fondente 85% cacao",
    "Il cioccolato al latte",
    "Il cioccolato bianco",
    "Il cioccolato ruby",
    "La Nutella vs la crema Novi",
    "La crema spalmabile al pistacchio",
    "Il miele sul formaggio",
    "La marmellata di arance amare",
    "La confettura di fichi",
    "La composta di frutti di bosco",
    "Lo strudel di mele",
    "Il kaiserschmarrn",
    "I krapfen alla crema",
    "Le frittelle veneziane",
    "Il baklava",
    "I loukoumades greci",
    "Il mochi giapponese",
    "Il dorayaki",
    "I churros con cioccolata calda",
    "Il dulce de leche",
    "Il flan argentino",
    "La torta tres leches",
    "Il brownie al cioccolato",
    "I cookies americani",
    "Il carrot cake",
    "Il red velvet cake",
    "La banana bread",
    "I pancake americani",
    "I pancake giapponesi soffici",
    "Il French toast",
    "Le crêpes alla Nutella",
    "Le crêpes suzette",
    "I waffles belgi",

    # ============================================================
    # 4. FENOMENI SOCIALI MODERNI (~200)
    # ============================================================
    "Lo sharenting",
    "Il quiet firing",
    "Il rage applying",
    "Il bare minimum Monday",
    "La grande stanchezza",
    "La hustle culture",
    "Il girl boss",
    "Il manifesting",
    "La toxic positivity",
    "L'echo chamber",
    "Il filter bubble",
    "Lo slacktivism",
    "Il clicktivism",
    "La JOMO (joy of missing out)",
    "La FOMO (fear of missing out)",
    "Il doomscrolling",
    "Il phubbing (ignorare per il telefono)",
    "Il ghosting",
    "Il breadcrumbing",
    "Il benching",
    "Lo zombieing",
    "Il catfishing",
    "Il love bombing",
    "Il gaslighting relazionale",
    "La situationship",
    "Il quiet quitting",
    "Il loud quitting",
    "Il career cushioning",
    "Il polywork",
    "La great resignation",
    "Il boomerang employee",
    "Il returnship",
    "Lo skill gap",
    "L'upskilling continuo",
    "Il reskilling professionale",
    "Il lifelong learning",
    "I micro-credentials",
    "Le certificazioni online",
    "Il personal branding",
    "Il networking su LinkedIn",
    "L'influencer marketing",
    "Il deinfluencing",
    "Il content creator come lavoro",
    "La creator economy",
    "Il side hustle",
    "La gig economy",
    "Il lavoro su piattaforma",
    "Il capitalismo della sorveglianza",
    "La privacy digitale",
    "Il diritto all'oblio",
    "Il digital detox",
    "Il dopamine detox",
    "Il screen time dei bambini",
    "La dipendenza da smartphone",
    "La dipendenza da social media",
    "Il cyberbullismo",
    "Il revenge porn",
    "Il body shaming online",
    "Il fat shaming",
    "Lo skinny shaming",
    "Il diet culture",
    "L'ortoressia",
    "Il clean eating estremo",
    "Il biohacking",
    "Il self-tracking ossessivo",
    "La quantified self",
    "L'ottimizzazione del sonno",
    "Il cold plunge trend",
    "Le docce fredde come trend",
    "Il microdosing",
    "Il journaling quotidiano",
    "La morning routine da influencer",
    "La 5 AM club",
    "Il that girl aesthetic",
    "Il clean girl aesthetic",
    "Il cottagecore",
    "Il dark academia",
    "Il light academia",
    "Il goblincore",
    "Il coastal grandmother",
    "Il quiet luxury",
    "Lo stealth wealth",
    "Il loud budgeting",
    "Il no buy challenge",
    "Il decluttering estremo",
    "Il metodo KonMari",
    "Il minimalismo come stile di vita",
    "Il van life",
    "Il digital nomad",
    "Il workation",
    "Il bleisure travel",
    "Lo slow travel",
    "Il turismo di prossimità",
    "Il turismo esperienziale",
    "L'overtourism",
    "Il turismo sostenibile",
    "Il greenwashing aziendale",
    "Il pinkwashing",
    "Il rainbow washing",
    "Il woke washing",
    "La cancel culture",
    "La call-out culture",
    "Il virtue signaling",
    "La polarizzazione politica online",
    "Le fake news come fenomeno",
    "I deepfake",
    "L'intelligenza artificiale generativa",
    "Il prompt engineering",
    "La paura di essere sostituiti dall'IA",
    "Il techlash",
    "Il diritto alla disconnessione",
    "Lo smart working permanente",
    "Il lavoro ibrido",
    "Il coworking",
    "Il coliving",
    "Il co-housing",
    "La gentrificazione dei quartieri",
    "Gli affitti brevi come problema",
    "L'emergenza abitativa",
    "I prezzi delle case impazziti",
    "La generazione affitto",
    "Il ritorno a casa dei genitori",
    "I boomerang kids",
    "La famiglia multigenerazionale",
    "Il calo demografico italiano",
    "L'inverno demografico",
    "La denatalità",
    "Il child-free per scelta",
    "Il pet parenting",
    "Gli animali come sostituti dei figli",
    "L'umanizzazione degli animali domestici",
    "Il gender reveal party",
    "Il baby shower all'americana",
    "Il wedding content sui social",
    "Le proposte di matrimonio virali",
    "Il micro-wedding",
    "L'elopement",
    "Il matrimonio destinazione",
    "La subscription fatigue",
    "L'economia dell'attenzione",
    "La shrinkflation",
    "La greedflation",
    "Lo skimpflation",
    "Il buy now pay later",
    "Il trading online da retail",
    "Le meme stock",
    "Le crypto come cultura",
    "Gli NFT come status symbol",
    "Il metaverso fallito",
    "La gamification di tutto",
    "Le app di dating come stile di vita",
    "La paralisi della scelta",
    "L'overparenting",
    "Il helicopter parenting",
    "Il lawnmower parenting",
    "Il gentle parenting",
    "L'attachment parenting",
    "La pedagogia Montessori a casa",
    "L'homeschooling",
    "Il gap year",
    "L'anno sabbatico",
    "La YOLO economy",
    "L'effetto nostalgia",
    "Il retromania",
    "Il vintage come identità",
    "Il thrifting come trend",
    "Il second hand di lusso",
    "Il reselling come business",
    "Lo sneaker reselling",
    "Le limited edition come ossessione",
    "Il drop marketing",
    "La coda per le sneaker",
    "Il fast fashion vs slow fashion",
    "La moda circolare",
    "Il capsule wardrobe",
    "Il project 333",
    "Il no makeup movement",
    "La skinimalism",
    "Il glass skin coreano",
    "La skincare routine da 10 step",
    "La skincare maschile",
    "Il grooming maschile",
    "La mascolinità tossica nel dibattito",
    "Il red pill / blue pill",
    "Le echo chamber maschiliste",
    "Il femminismo intersezionale",
    "L'attivismo digitale",
    "Le petizioni online",
    "Il crowdfunding sociale",
    "Il crowdfunding creativo",
    "La beneficenza sui social",
    "Il volontariato come trend",
    "La dieta social media",

    # ============================================================
    # 5. COSE DA AEROPORTO E VOLO (~100)
    # ============================================================
    "La sala d'attesa VIP",
    "La Priority boarding",
    "Il fast track per i controlli",
    "Il ritardo del volo",
    "La cancellazione del volo",
    "Il rimborso del volo",
    "I diritti del passeggero",
    "Le low cost vs le compagnie tradizionali",
    "Wizz Air",
    "EasyJet",
    "Vueling",
    "ITA Airways",
    "Lufthansa",
    "Air France",
    "British Airways",
    "Emirates",
    "Qatar Airways",
    "Turkish Airlines",
    "Singapore Airlines",
    "Ryanair",
    "Norwegian Air",
    "Volotea",
    "Iberia",
    "KLM",
    "Swiss International",
    "Austrian Airlines",
    "TAP Portugal",
    "Etihad Airways",
    "Japan Airlines",
    "ANA giapponese",
    "Il bagaglio a mano",
    "Il bagaglio da stiva",
    "Il peso del bagaglio a mano",
    "Il trolley da cabina",
    "Lo zaino come bagaglio a mano",
    "Il duty free in aeroporto",
    "Lo shopping in aeroporto",
    "I profumi al duty free",
    "Gli alcolici al duty free",
    "Il cibo in aeroporto",
    "I panini carissimi in aeroporto",
    "Il caffè in aeroporto",
    "L'acqua dopo i controlli",
    "I controlli di sicurezza",
    "Il metal detector",
    "Il body scanner",
    "Togliersi le scarpe ai controlli",
    "I liquidi nel sacchetto trasparente",
    "Il gate lontanissimo",
    "Il bus per raggiungere l'aereo",
    "La passerella per salire sull'aereo",
    "Il posto finestrino",
    "Il posto corridoio",
    "Il posto centrale",
    "La fila per salire sull'aereo",
    "Il volo notturno",
    "Il volo all'alba",
    "Il volo intercontinentale",
    "Il volo low cost di 2 ore",
    "Lo scalo intermedio",
    "Il cambio aereo",
    "La coincidenza persa",
    "Il check-in online",
    "Il check-in al banco",
    "Il self check-in in aeroporto",
    "Il posto extra legroom",
    "L'uscita di emergenza con più spazio",
    "Il cibo servito in aereo",
    "Il pasto speciale in aereo",
    "Le bibite gratuite in volo",
    "Il carrello delle bevande",
    "L'intrattenimento a bordo",
    "Lo schermo nel sedile",
    "Il Wi-Fi in aereo",
    "La turbolenza in volo",
    "L'atterraggio movimentato",
    "Il pilota che applaudi all'atterraggio",
    "Il jet lag",
    "La classe economy",
    "La classe business",
    "La prima classe",
    "La premium economy",
    "Le miglia frequent flyer",
    "Il programma fedeltà della compagnia",
    "La Star Alliance",
    "La Oneworld Alliance",
    "La SkyTeam Alliance",
    "L'upgrade gratuito",
    "L'overbooking del volo",
    "Il volontario per rinunciare al posto",
    "La carta d'imbarco digitale",
    "Il nastro bagagli",
    "L'attesa al nastro bagagli",
    "Il bagaglio smarrito",
    "Il bagaglio danneggiato",
    "La valigia che arriva per ultima",
    "Il parcheggio in aeroporto",
    "Il treno per l'aeroporto",
    "Il bus navetta per l'aeroporto",
    "Il taxi dall'aeroporto",
    "Il transfer privato",
    "Il noleggio auto in aeroporto",

    # ============================================================
    # 6. TIPI DI PANE E PRODOTTI DA FORNO (~100)
    # ============================================================
    "Il pane integrale",
    "Il pane ai cereali",
    "Il pane di segale",
    "Il pane nero",
    "La ciabatta",
    "Il filone",
    "La rosetta",
    "Il panino all'olio",
    "La michetta",
    "La mantovana",
    "Il pane cafone napoletano",
    "Il pane di Matera",
    "Il pane di Laterza",
    "Il pane di Altamura",
    "Il pane Ferrara",
    "La pita",
    "Il naan",
    "Il pane azzimo",
    "La focaccia genovese",
    "La focaccia barese",
    "La focaccia di Recco",
    "La schiacciata toscana",
    "La piadina romagnola",
    "Il gnocco fritto emiliano",
    "La crescentina modenese",
    "Il borlengo",
    "La tigella",
    "Il pane carasau sardo",
    "Il pane frattau",
    "Il pistoccu sardo",
    "La frisella pugliese",
    "I taralli pugliesi",
    "I taralli napoletani sugna e pepe",
    "I grissini torinesi",
    "I grissini stirati a mano",
    "Le lingue di suocera",
    "Il pan bauletto",
    "Il pancarrè",
    "Il pane per tramezzini",
    "Il pane in cassetta",
    "Il pane toscano senza sale",
    "Il pane pugliese a lievitazione naturale",
    "La ciabatta con lievito madre",
    "Il pane con le olive",
    "Il pane alle noci",
    "Il pane al rosmarino",
    "Il pane con i semi di lino",
    "Il pane con semi di girasole",
    "Il pane di kamut",
    "Il pane di farro",
    "Il pane senza glutine",
    "Il pane proteico",
    "Il pane a lievitazione naturale",
    "Il pane con pasta madre",
    "Il panettone come prodotto da forno",
    "Il pandoro come prodotto da forno",
    "La colomba pasquale",
    "Il pan brioche",
    "Il pan brioche al cioccolato",
    "La treccia di pan brioche",
    "Il cornetto da bar",
    "Il cornetto vuoto",
    "Il cornetto alla crema",
    "Il cornetto al cioccolato",
    "Il cornetto alla marmellata",
    "Il cornetto integrale",
    "Il cornetto vegano",
    "Il croissant francese vero",
    "Il pain aux raisins",
    "La baguette francese",
    "Il bagel americano",
    "Il pretzel tedesco",
    "Il pumpernickel",
    "Il pane di Eger",
    "Il chapati indiano",
    "Il roti",
    "La tortilla di mais",
    "La tortilla di farina",
    "Il pane etiope injera",
    "Il lavash armeno",
    "Il pane arabo",
    "La manakish libanese",
    "Il simit turco",
    "La focaccina del bar",
    "Il toast del bar",
    "Il tramezzino del bar",
    "La bruschetta classica",
    "La fettunta toscana",
    "Il crostino toscano",
    "Le fette biscottate",
    "Le fette biscottate integrali",
    "I crackers",
    "I crackers integrali",
    "Le gallette di riso",
    "Le gallette di mais",
    "I crostini per zuppe",
    "Il pane raffermo riciclato",
    "La panzanella col pane vecchio",
    "La ribollita col pane",
    "La zuppa di pane",

    # ============================================================
    # 7. TIPI DI FORMAGGIO (~100)
    # ============================================================
    "La mozzarella fiordilatte",
    "La scamorza affumicata",
    "La provola",
    "Il caciocavallo silano",
    "Il pecorino sardo",
    "Il pecorino toscano",
    "La feta greca",
    "L'emmental svizzero",
    "Il gruyère",
    "Il brie francese",
    "Il camembert",
    "Il roquefort",
    "Lo stilton inglese",
    "Il gouda olandese",
    "L'edamer",
    "Il cheddar",
    "Il manchego spagnolo",
    "Il parmigiano reggiano",
    "Il grana padano",
    "Il parmigiano vs il grana",
    "La mozzarella di bufala campana",
    "La burrata pugliese",
    "La stracciatella di burrata",
    "Il primo sale",
    "La ricotta fresca",
    "La ricotta di pecora",
    "La ricotta salata",
    "La ricotta affumicata",
    "Il mascarpone",
    "Il gorgonzola dolce",
    "Il gorgonzola piccante",
    "Il taleggio",
    "La fontina valdostana",
    "Il raschera piemontese",
    "Il castelmagno",
    "La toma piemontese",
    "Il montasio friulano",
    "L'asiago fresco",
    "L'asiago stagionato",
    "Il provolone dolce",
    "Il provolone piccante",
    "Il provolone del Monaco",
    "La caciotta toscana",
    "Il pecorino di Pienza",
    "Il pecorino romano",
    "Il fiore sardo",
    "Il canestrato pugliese",
    "Il ragusano",
    "Il piacentinu ennese",
    "La vastedda del Belìce",
    "La provola dei Nebrodi",
    "Il caciocavallo podolico",
    "La mozzarella in carrozza",
    "I bocconcini di mozzarella",
    "Le ciliegine di mozzarella",
    "La treccia di mozzarella",
    "Il formaggio spalmabile",
    "La Philadelphia",
    "Il Bel Paese",
    "La sottiletta",
    "Il formaggio fuso per hamburger",
    "Il formaggio di capra fresco",
    "Il formaggio di capra stagionato",
    "Il chèvre francese",
    "Il Comté",
    "Il Reblochon",
    "L'Époisses",
    "Il Morbier",
    "Il Beaufort",
    "Il Raclette",
    "Il Gruyère d'Alpage",
    "L'Appenzeller svizzero",
    "Il Tilsiter",
    "Il Limburger",
    "Il Munster",
    "L'Ossau-Iraty",
    "Il Pecorino con tartufo",
    "Il formaggio alle erbe",
    "Il formaggio al peperoncino",
    "Il formaggio ubriaco al vino",
    "Il formaggio in foglie di noce",
    "Il formaggio di fossa",
    "Il formaggio in crosta di cenere",
    "Il Brillat-Savarin",
    "Il Saint-André",
    "Il Délice de Bourgogne",
    "Il Halloumi cipriota",
    "Il paneer indiano",
    "Il queso fresco messicano",
    "La cagliata fresca",
    "Il formaggio vegano",
    "Il formaggio di anacardi",
    "Il formaggio di mandorle",
    "La fonduta di formaggio",
    "Il tagliere di formaggi misti",
    "Il formaggio con il miele",
    "Il formaggio con la mostarda",
    "Il formaggio con le confetture",
    "Il formaggio con le noci",

    # ============================================================
    # 8. CONCETTI DI GIARDINAGGIO E NATURA (~100)
    # ============================================================
    "L'orto urbano",
    "L'orto verticale",
    "Il compostaggio domestico",
    "I lombrichi per il compost",
    "Le serre domestiche",
    "L'idroponica",
    "L'acquaponica",
    "Le piante carnivore",
    "Le succulente",
    "I bonsai come hobby",
    "Le orchidee",
    "Le rose rampicanti",
    "I girasoli",
    "La lavanda",
    "Il rosmarino sul balcone",
    "Il basilico fresco",
    "La menta sul balcone",
    "Il peperoncino coltivato in casa",
    "I pomodori sul terrazzo",
    "Le fragole in vaso",
    "L'albero di limoni in giardino",
    "L'ulivo ornamentale",
    "Il fico in giardino",
    "Il melograno ornamentale",
    "Le piante aromatiche sul davanzale",
    "Il timo in vaso",
    "La salvia in vaso",
    "L'origano coltivato",
    "Il prezzemolo fresco",
    "L'erba cipollina",
    "Il giardino zen",
    "Il giardino all'inglese",
    "Il giardino all'italiana",
    "Il giardino giapponese",
    "Il prato all'inglese perfetto",
    "Il robot tagliaerba",
    "Il tagliaerba manuale",
    "Il decespugliatore",
    "La potatura delle siepi",
    "La siepe di alloro",
    "La siepe di bosso",
    "La siepe di cipresso",
    "Il gelsomino rampicante",
    "La bouganville",
    "Il glicine",
    "L'edera rampicante",
    "La vite americana",
    "Le piante da appartamento",
    "Il pothos",
    "La monstera deliciosa",
    "Il ficus benjamin",
    "La sansevieria",
    "Lo spatifillo",
    "L'aloe vera in casa",
    "Il cactus da scrivania",
    "Le piante grasse da collezione",
    "Il terrario chiuso",
    "Il terrario aperto",
    "Il muschio stabilizzato",
    "Le pareti verdi",
    "Il verde verticale in casa",
    "Il guerrilla gardening",
    "Il seed bombing",
    "L'orto condiviso",
    "L'orto didattico",
    "Il frutteto familiare",
    "La permacultura",
    "L'agricoltura sinergica",
    "La pacciamatura",
    "Il sovescio",
    "La rotazione delle colture",
    "La consociazione delle piante",
    "Le piante anti zanzare",
    "La citronella in giardino",
    "I gerani anti insetti",
    "Le coccinelle come pesticida naturale",
    "L'hotel per insetti",
    "Le casette per uccellini",
    "Le mangiatoie per uccelli",
    "Il birdwatching da giardino",
    "Lo stagno da giardino",
    "Le ninfee nello stagno",
    "I pesci rossi nel laghetto",
    "Le farfalle nel giardino",
    "Il giardino delle farfalle",
    "Le api da giardino",
    "L'apicoltura urbana",
    "Il miele del proprio alveare",
    "Il compost maturo",
    "Il terriccio universale",
    "L'argilla espansa per i vasi",
    "Il concime organico",
    "Il concime chimico vs biologico",
    "L'irrigazione a goccia",
    "L'irrigazione automatica",
    "Il timer per l'irrigazione",
    "La raccolta dell'acqua piovana",
    "Il rain garden",
    "Il giardino xerofilo",
    "Le piante resistenti alla siccità",
    "Il giardinaggio terapeutico",

    # ============================================================
    # 9. TIPI DI ALLENAMENTO SPECIFICI (~100)
    # ============================================================
    "L'HIIT",
    "Il tabata",
    "L'allenamento funzionale",
    "Il TRX",
    "Il battle rope",
    "Il sled push",
    "Il box jump",
    "Il wall ball",
    "Il kettlebell swing",
    "Il clean and jerk",
    "Lo snatch olimpico",
    "Il muscle up",
    "L'handstand pushup",
    "Il pistol squat",
    "Il Turkish get up",
    "Il burpee",
    "Il mountain climber",
    "Il jumping jack",
    "Il plank",
    "Il plank laterale",
    "Il dead hang",
    "Le trazioni alla sbarra",
    "Le trazioni supine",
    "I dips alle parallele",
    "Le flessioni diamante",
    "Le flessioni esplosive",
    "Gli squat a corpo libero",
    "Il goblet squat",
    "Il front squat",
    "Il back squat",
    "Lo stacco da terra",
    "Lo stacco rumeno",
    "La panca piana",
    "La panca inclinata",
    "Il military press",
    "L'Arnold press",
    "Le alzate laterali",
    "Il rematore con bilanciere",
    "Il lat pulldown",
    "Il cable crossover",
    "La leg press",
    "Il leg curl",
    "Il leg extension",
    "L'hip thrust",
    "Il calf raise",
    "Il farmer's walk",
    "Il bear crawl",
    "Il duck walk",
    "L'allenamento calistenico",
    "Il calisthenics al parco",
    "La ginnastica artistica per adulti",
    "L'arrampicata sportiva indoor",
    "Il bouldering",
    "L'allenamento per la maratona",
    "L'interval training per la corsa",
    "Le ripetute in salita",
    "Il fartlek",
    "Il tempo run",
    "La corsa lenta e lunga",
    "Lo stretching statico",
    "Lo stretching dinamico",
    "Il foam rolling",
    "Il self-myofascial release",
    "La mobilità articolare",
    "Il riscaldamento attivo",
    "Il defaticamento post allenamento",
    "L'allenamento della fascia",
    "Lo yoga power",
    "Lo yoga hot",
    "Lo yoga restaurativo",
    "Lo yin yoga",
    "L'ashtanga yoga",
    "Il vinyasa flow",
    "Il pilates matwork",
    "Il pilates reformer",
    "La sbarra di danza fitness",
    "Il barre workout",
    "L'allenamento con gli elastici",
    "L'allenamento con le mini band",
    "L'allenamento con la palla medica",
    "L'allenamento con il sandbag",
    "L'allenamento con la corda",
    "Il salto della corda come cardio",
    "Il vogatore come cardio",
    "L'assault bike",
    "Lo ski erg",
    "L'ellittica in palestra",
    "Il tapis roulant inclinato",
    "La camminata in pendenza",
    "La camminata veloce",
    "Il nordic walking",
    "L'aquagym",
    "L'hydrobike",
    "Il nuoto a stile libero",
    "Il nuoto a rana",
    "Il nuoto a dorso",
    "Il nuoto a farfalla",
    "L'allenamento dei Navy SEAL",
    "L'allenamento dei pompieri",
    "L'allenamento spartano",
    "La Spartan Race",
    "La Tough Mudder",

    # ============================================================
    # 10. CONCETTI DI ARCHITETTURA ITALIANA (~100)
    # ============================================================
    "Il Colosseo",
    "La Torre di Pisa",
    "Il Duomo di Milano",
    "La Basilica di San Pietro",
    "Il Pantheon",
    "La Fontana di Trevi",
    "Piazza San Marco",
    "Ponte Vecchio",
    "La Reggia di Caserta",
    "La Villa Rotonda di Palladio",
    "I Trulli di Alberobello",
    "I Nuraghi sardi",
    "La Basilica di San Marco",
    "Il Campanile di Giotto",
    "La Cupola del Brunelleschi",
    "Il Battistero di Firenze",
    "La Galleria degli Uffizi come edificio",
    "Palazzo Pitti",
    "Il Palazzo Ducale di Venezia",
    "Il Ponte dei Sospiri",
    "Il Ponte di Rialto",
    "La Ca' d'Oro",
    "La Basilica di Superga",
    "La Mole Antonelliana",
    "Il Lingotto di Torino",
    "La Galleria Vittorio Emanuele II",
    "Il Castello Sforzesco",
    "Il Palazzo della Ragione a Padova",
    "La Basilica di Sant'Antonio a Padova",
    "L'Arena di Verona",
    "La Basilica di San Vitale a Ravenna",
    "Il Mausoleo di Galla Placidia",
    "Le Torri di Bologna",
    "La Piazza del Campo a Siena",
    "Il Palazzo dei Priori a Perugia",
    "Il Duomo di Orvieto",
    "La Basilica di San Francesco ad Assisi",
    "Il Palazzo dei Normanni a Palermo",
    "La Cappella Palatina",
    "Il Duomo di Monreale",
    "Il Teatro Massimo di Palermo",
    "Il Teatro San Carlo di Napoli",
    "La Certosa di Pavia",
    "Il Palazzo Te di Mantova",
    "Il Tempio Malatestiano di Rimini",
    "La Villa d'Este a Tivoli",
    "Villa Adriana a Tivoli",
    "La Reggia di Venaria Reale",
    "Il Palazzo Reale di Torino",
    "Il Palazzo Reale di Napoli",
    "La Villa Borghese come parco",
    "Il Foro Romano",
    "I Fori Imperiali",
    "Le Terme di Caracalla",
    "Il Castel del Monte di Federico II",
    "La Rocca di Gradara",
    "Il Castello di Miramare",
    "Il Castello di Fénis",
    "Il Castello Aragonese di Ischia",
    "Il Maschio Angioino",
    "Castel Sant'Angelo",
    "La Scala di Milano come edificio",
    "Il MAXXI di Roma",
    "L'Auditorium Parco della Musica",
    "Il MUSE di Trento",
    "Il grattacielo Pirelli",
    "La Torre UniCredit",
    "Il Bosco Verticale di Milano",
    "CityLife Milano",
    "Il quartiere EUR a Roma",
    "Il Palazzo della Civiltà Italiana",
    "Le Vele di Scampia",
    "Il Corviale a Roma",
    "Le case popolari di Zingonia",
    "I Sassi di Matera",
    "Le case torri di San Gimignano",
    "I borghi medievali italiani",
    "Le ville palladiane del Veneto",
    "I palazzi barocchi di Lecce",
    "Le architetture liberty di Torino",
    "Il razionalismo italiano",
    "L'architettura fascista",
    "Le stazioni di Calatrava in Italia",
    "La stazione di Napoli Afragola",
    "La stazione di Reggio Emilia AV Mediopadana",
    "Le chiese moderne di Renzo Piano",
    "Le opere di Carlo Scarpa",
    "Le opere di Gio Ponti",
    "Le opere di Pier Luigi Nervi",
    "Le architetture di Mario Botta in Italia",
    "L'architettura rurale italiana",
    "I terrazzamenti delle Cinque Terre",
    "Le cascine lombarde",
    "I masi del Trentino",
    "Le masserie pugliesi",
    "I dammusi di Pantelleria",
    "Le torri costiere del Sud Italia",
    "I fari italiani",

    # ============================================================
    # 11. BRAND DI LUSSO E MODA (~100)
    # ============================================================
    "Bottega Veneta",
    "Brunello Cucinelli",
    "Loro Piana",
    "Max Mara",
    "Dolce & Gabbana",
    "Versace",
    "Fendi",
    "Salvatore Ferragamo",
    "Tod's",
    "Hogan",
    "Ermenegildo Zegna",
    "Brioni",
    "Canali",
    "Etro",
    "Missoni",
    "Moschino",
    "Roberto Cavalli",
    "Valentino",
    "Givenchy",
    "Balenciaga",
    "Saint Laurent",
    "Celine",
    "Loewe",
    "Burberry",
    "Alexander McQueen",
    "Stella McCartney",
    "Vivienne Westwood",
    "Moncler",
    "Stone Island",
    "CP Company",
    "Aspesi",
    "Woolrich",
    "Barbour",
    "Colmar",
    "K-Way",
    "Napapijri",
    "Paul Smith",
    "Hugo Boss",
    "Ralph Lauren",
    "Calvin Klein",
    "Tommy Hilfiger",
    "Michael Kors",
    "Coach",
    "Kate Spade",
    "Tiffany & Co.",
    "Cartier",
    "Bulgari",
    "Van Cleef & Arpels",
    "Chopard",
    "Piaget",
    "Rolex",
    "Omega",
    "Patek Philippe",
    "Audemars Piguet",
    "Richard Mille",
    "IWC Schaffhausen",
    "Jaeger-LeCoultre",
    "Breitling",
    "Tag Heuer",
    "Hublot",
    "Panerai",
    "Longines",
    "Tissot",
    "Swatch",
    "Casio G-Shock",
    "Hermès",
    "Louis Vuitton",
    "Chanel",
    "Dior",
    "Prada",
    "Gucci",
    "Armani",
    "Emporio Armani",
    "Armani Exchange",
    "Diesel",
    "Marni",
    "Jil Sander",
    "Maison Margiela",
    "Acne Studios",
    "Off-White",
    "Palm Angels",
    "Amiri",
    "Fear of God",
    "Essentials di Fear of God",
    "Rick Owens",
    "Comme des Garçons",
    "Issey Miyake",
    "Kenzo",
    "Balmain",
    "Lanvin",
    "Chloe",
    "Zimmermann",
    "Miu Miu",
    "Jimmy Choo",
    "Christian Louboutin",
    "Manolo Blahnik",
    "Roger Vivier",
    "Aquazzura",
    "Golden Goose",
    "Common Projects",
    "Maison Kitsuné",
    "A.P.C.",

    # ============================================================
    # 12. TIPI DI VINO SPECIFICI (~100)
    # ============================================================
    "Il Pinot Grigio",
    "Il Sauvignon Blanc",
    "Lo Chardonnay",
    "Il Riesling",
    "Il Moscato d'Asti",
    "Il Verdicchio",
    "Il Falanghina",
    "Il Greco di Tufo",
    "Il Fiano di Avellino",
    "Il Pecorino abruzzese",
    "Il Trebbiano",
    "La Ribolla Gialla",
    "Il Refosco",
    "Il Sagrantino di Montefalco",
    "Il Brunello di Montalcino",
    "Il Barolo",
    "Il Barbaresco",
    "Il Nebbiolo delle Langhe",
    "Il Dolcetto d'Alba",
    "La Barbera d'Asti",
    "Il Grignolino",
    "Il Freisa",
    "Il Ruché di Castagnole",
    "Il Gattinara",
    "Il Ghemme",
    "Il Chianti Classico",
    "Il Vino Nobile di Montepulciano",
    "Il Rosso di Montalcino",
    "Il Morellino di Scansano",
    "Il Bolgheri Sassicaia",
    "Il Bolgheri Ornellaia",
    "Il Tignanello",
    "Il Supertoscano",
    "L'Amarone della Valpolicella",
    "Il Ripasso della Valpolicella",
    "Il Valpolicella Classico",
    "Il Bardolino",
    "Il Soave Classico",
    "Il Lugana",
    "Il Franciacorta",
    "Il Prosecco di Valdobbiadene",
    "Il Prosecco di Conegliano",
    "Il Prosecco del Collio",
    "Il Lambrusco di Sorbara",
    "Il Lambrusco Grasparossa",
    "Il Sangiovese di Romagna",
    "L'Albana di Romagna",
    "Il Vermentino di Sardegna",
    "Il Cannonau di Sardegna",
    "Il Carignano del Sulcis",
    "Il Vermentino di Gallura",
    "Il Nero d'Avola",
    "Il Cerasuolo di Vittoria",
    "L'Etna Rosso",
    "L'Etna Bianco",
    "Il Marsala",
    "Il Passito di Pantelleria",
    "La Malvasia delle Lipari",
    "Il Moscato di Noto",
    "Il Primitivo di Manduria",
    "Il Negroamaro salentino",
    "Il Salice Salentino",
    "Il Susumaniello",
    "L'Aglianico del Vulture",
    "Il Taurasi",
    "La Lacryma Christi del Vesuvio",
    "Il Piedirosso",
    "Il Cesanese del Piglio",
    "Il Frascati",
    "Il Montepulciano d'Abruzzo",
    "Il Trebbiano d'Abruzzo",
    "Il Pecorino d'Abruzzo",
    "Il Verdicchio dei Castelli di Jesi",
    "Il Lacrima di Morro d'Alba",
    "Il Rosso Conero",
    "Il Gewürztraminer altoatesino",
    "Il Pinot Nero altoatesino",
    "Lo Schiava dell'Alto Adige",
    "Il Lagrein",
    "Il Teroldego Rotaliano",
    "Il Müller-Thurgau trentino",
    "Il Nosiola",
    "Il Marzemino",
    "Lo Champagne vs il Prosecco",
    "Il Crémant d'Alsace",
    "Il Cava spagnolo",
    "Il Sekt tedesco",
    "Lo spumante metodo classico",
    "Lo spumante metodo Charmat",
    "Il rosé di Provenza",
    "Il rosato pugliese",
    "Il Cerasuolo d'Abruzzo",
    "Il Chiaretto del Garda",
    "Il vino orange",
    "Il vino naturale",
    "Il vino biodinamico",
    "Il vino biologico",
    "Il vino senza solfiti",
    "Il vino in bag in box",
    "Il vino sfuso",
    "Il vino della casa al ristorante",

    # ============================================================
    # 13. PERSONAGGI DI VIDEOGIOCHI SPECIFICI (~100)
    # ============================================================
    "Link di Zelda",
    "Kirby",
    "Samus Aran di Metroid",
    "Master Chief di Halo",
    "Kratos di God of War",
    "Aloy di Horizon",
    "Ellie di The Last of Us",
    "Joel di The Last of Us",
    "Arthur Morgan di Red Dead",
    "Cloud Strife di Final Fantasy",
    "Geralt di Rivia",
    "Solid Snake",
    "Mario",
    "Luigi",
    "Princess Peach",
    "Bowser",
    "Yoshi",
    "Donkey Kong",
    "Pikachu",
    "Charizard",
    "Mewtwo",
    "Eevee",
    "Sonic the Hedgehog",
    "Tails di Sonic",
    "Pac-Man",
    "Mega Man",
    "Ryu di Street Fighter",
    "Chun-Li di Street Fighter",
    "Scorpion di Mortal Kombat",
    "Sub-Zero di Mortal Kombat",
    "Lara Croft",
    "Nathan Drake di Uncharted",
    "Crash Bandicoot",
    "Spyro the Dragon",
    "Dante di Devil May Cry",
    "Bayonetta",
    "Ratchet di Ratchet & Clank",
    "Jak di Jak & Daxter",
    "Sly Cooper",
    "Gordon Freeman di Half-Life",
    "GLaDOS di Portal",
    "Steve di Minecraft",
    "Creeper di Minecraft",
    "Agent 47 di Hitman",
    "Sam Fisher di Splinter Cell",
    "Commander Shepard di Mass Effect",
    "Ezio Auditore di Assassin's Creed",
    "Altair di Assassin's Creed",
    "Edward Kenway di Assassin's Creed",
    "Jin Sakai di Ghost of Tsushima",
    "Sekiro",
    "Il Tarnished di Elden Ring",
    "Il Chosen Undead di Dark Souls",
    "Solaire di Astora",
    "The Knight di Hollow Knight",
    "Ori",
    "Madeline di Celeste",
    "Cuphead",
    "Shovel Knight",
    "Isaac di The Binding of Isaac",
    "Il Bard di Hades",
    "Zagreus di Hades",
    "Red di Transistor",
    "The Kid di Bastion",
    "Senua di Hellblade",
    "Amaterasu di Okami",
    "Phoenix Wright",
    "Professor Layton",
    "Leon Kennedy di Resident Evil",
    "Jill Valentine di Resident Evil",
    "Chris Redfield di Resident Evil",
    "Ada Wong di Resident Evil",
    "Simon Belmont di Castlevania",
    "Alucard di Castlevania",
    "Sora di Kingdom Hearts",
    "Terra di Final Fantasy VI",
    "Tifa Lockhart di Final Fantasy",
    "Aerith di Final Fantasy",
    "Squall di Final Fantasy VIII",
    "Tidus di Final Fantasy X",
    "Noctis di Final Fantasy XV",
    "Clive di Final Fantasy XVI",
    "The Dragonborn di Skyrim",
    "CJ di GTA San Andreas",
    "Tommy Vercetti di GTA Vice City",
    "Trevor di GTA V",
    "John Marston di Red Dead",
    "Marcus Fenix di Gears of War",
    "Captain Price di Call of Duty",
    "Soap di Call of Duty",
    "Alex Mason di Call of Duty",
    "Tracer di Overwatch",
    "Jinx di League of Legends",
    "Ahri di League of Legends",
    "Pudge di Dota 2",
    "Jett di Valorant",
    "The Prince di Prince of Persia",
    "Rayman",
    "Sackboy di LittleBigPlanet",
    "Astro di Astro Bot",
    "Wander di Shadow of the Colossus",

    # ============================================================
    # 14. COSE CHE SI FANNO IN MONTAGNA (~100)
    # ============================================================
    "Lo sci di fondo",
    "Lo sci alpinismo",
    "Le ciaspole",
    "Il fuoripista",
    "La seggiovia",
    "La cabinovia",
    "La funivia",
    "Il rifugio di montagna",
    "La polenta al rifugio",
    "Il bombardino",
    "Il vin brulé sulle piste",
    "L'après ski",
    "La settimana bianca",
    "Il weekend sulla neve",
    "Lo sci alpino",
    "Lo snowboard",
    "Lo snowboard freestyle",
    "Lo slalom gigante",
    "La discesa libera",
    "Il supergigante",
    "Il biathlon",
    "Il salto con gli sci",
    "Il bob",
    "Lo slittino",
    "Lo skeleton",
    "Il curling in montagna",
    "Il pattinaggio su ghiaccio naturale",
    "L'hockey su ghiaccio all'aperto",
    "Le escursioni estive in montagna",
    "Il trekking in alta quota",
    "L'alpinismo",
    "L'arrampicata su roccia",
    "Le vie ferrate",
    "Il canyoning",
    "Il rafting in montagna",
    "Il kayak nei torrenti",
    "La mountain bike in montagna",
    "L'e-bike in montagna",
    "Il downhill in mountain bike",
    "L'enduro in mountain bike",
    "Il trail running in montagna",
    "La corsa in quota",
    "Le sky race",
    "Il vertical kilometer",
    "L'ultra trail di montagna",
    "Il parapendio dalla montagna",
    "Il deltaplano",
    "La zipline in montagna",
    "Il parco avventura in montagna",
    "Il ponte tibetano",
    "L'osservazione delle stelle in quota",
    "L'alba vista dalla vetta",
    "Il tramonto dalla montagna",
    "Le malghe alpine",
    "La vita in malga",
    "La transumanza",
    "Le mucche al pascolo in montagna",
    "Il formaggio d'alpeggio",
    "Il latte fresco di montagna",
    "Lo speck affumicato",
    "I canederli al rifugio",
    "Lo strudel di mele al rifugio",
    "La kaiserschmarrn in baita",
    "La fonduta in montagna",
    "La raclette in montagna",
    "La polenta concia",
    "La polenta taragna",
    "La polenta con i funghi porcini",
    "I funghi porcini raccolti nel bosco",
    "La raccolta dei funghi",
    "Il tesserino per i funghi",
    "Le castagne raccolte nel bosco",
    "La passeggiata nel bosco d'autunno",
    "Il foliage autunnale",
    "Le cascate di montagna",
    "I laghi alpini",
    "Il lago di Braies",
    "Il lago di Carezza",
    "Il bagno nel lago di montagna",
    "Le terme in montagna",
    "Le piscine panoramiche in montagna",
    "La spa con vista sulle Dolomiti",
    "Il wellness alpino",
    "La sauna finlandese in montagna",
    "Il bagno nella neve dopo la sauna",
    "Le Dolomiti",
    "Il Monte Bianco",
    "Il Monte Rosa",
    "Il Gran Paradiso",
    "Il Cervino",
    "Le Tre Cime di Lavaredo",
    "L'Alta Via delle Dolomiti",
    "Il Sentiero Italia",
    "Il Cammino di Santiago partendo dall'Italia",
    "La Via degli Dei",
    "Il Cammino dei Briganti",
    "I rifugi del CAI",
    "La tessera del CAI",
    "Le guide alpine certificate",
    "Il corso di sopravvivenza in montagna",
    "La sicurezza in montagna",

    # ============================================================
    # 15. PARAGONI SENSATI AGGIUNTIVI (~150)
    # ============================================================
    "La margherita vs la marinara",
    "La Coca-Cola vs la Fanta",
    "La birra chiara vs la birra scura",
    "Il vino rosso vs il vino bianco",
    "La colazione dolce vs la colazione salata",
    "La pizza tonda vs la pizza al taglio",
    "Le penne vs i rigatoni",
    "Gli spaghetti vs le linguine",
    "Il pandoro vs il panettone artigianale",
    "Il cappuccino vs il caffè latte",
    "L'espresso vs il caffè americano",
    "Il caffè al bar vs il caffè a casa",
    "La moka vs la macchina a capsule",
    "Il latte vaccino vs il latte di avena",
    "Il burro vs l'olio d'oliva",
    "La pasta al forno vs le lasagne",
    "La carbonara vs la gricia",
    "L'amatriciana vs la cacio e pepe",
    "Il ragù bolognese vs il ragù napoletano",
    "La cotoletta milanese vs la fiorentina",
    "Il fritto misto vs la grigliata mista",
    "La frittura di pesce vs la frittura di verdure",
    "Il pesce al forno vs il pesce alla griglia",
    "La carne rossa vs la carne bianca",
    "Il pollo arrosto vs il pollo fritto",
    "Il sushi vs il sashimi",
    "Il ramen vs l'udon",
    "Il kebab vs il gyros",
    "Il falafel vs l'hummus",
    "Il guacamole vs la salsa",
    "Il pesto genovese vs il pesto siciliano",
    "La maionese vs il ketchup",
    "La senape vs la mostarda",
    "L'aceto balsamico vs l'aceto di mele",
    "Il sale grosso vs il sale fino",
    "Lo zucchero bianco vs lo zucchero di canna",
    "Il miele vs lo sciroppo d'acero",
    "Le fragole vs i lamponi",
    "Le ciliegie vs le amarene",
    "Le pesche vs le nettarine",
    "L'anguria vs il melone",
    "Le arance vs i mandarini",
    "Le mele vs le pere",
    "La banana vs il kiwi",
    "L'avocado vs il mango",
    "Il Netflix vs il Disney+",
    "Spotify vs Apple Music",
    "YouTube Music vs Amazon Music",
    "La PlayStation 5 vs la Xbox Series X",
    "La Nintendo Switch vs lo Steam Deck",
    "Il gaming su PC vs il gaming su console",
    "Il monitor ultrawide vs il doppio monitor",
    "Le cuffie over-ear vs le cuffie in-ear",
    "Gli AirPods vs le Galaxy Buds",
    "Il MacBook vs il ThinkPad",
    "L'iPad vs il tablet Samsung",
    "L'Apple Watch vs il Garmin",
    "Il Fitbit vs il Xiaomi Band",
    "WhatsApp vs Telegram",
    "Instagram vs TikTok",
    "Twitter/X vs Threads",
    "Facebook vs LinkedIn",
    "Reddit vs Quora",
    "Google Maps vs Waze",
    "Google Chrome vs Firefox",
    "Safari vs Edge",
    "Gmail vs Outlook",
    "Google Drive vs OneDrive",
    "Notion vs Obsidian",
    "Zoom vs Teams",
    "Slack vs Discord",
    "La bici da corsa vs la bici gravel",
    "La bici da corsa vs la mountain bike",
    "La corsa vs la camminata veloce",
    "Il nuoto vs il ciclismo",
    "La palestra vs il crossfit",
    "Lo yoga vs il pilates",
    "Il tennis vs il padel",
    "Il calcetto vs il basket",
    "La Serie A vs la Premier League",
    "La Champions League vs il Mondiale",
    "Il Giro d'Italia vs il Tour de France",
    "La Formula 1 vs la MotoGP",
    "La Ferrari vs la Red Bull in F1",
    "Il cinema vs lo streaming",
    "Il libro cartaceo vs l'e-book",
    "Il Kindle vs il Kobo",
    "L'audiolibro vs il podcast",
    "La radio vs il podcast",
    "Il concerto live vs il festival",
    "Il teatro vs il cinema",
    "Il museo vs la mostra temporanea",
    "La spiaggia vs la montagna",
    "Il mare vs il lago",
    "Il campeggio vs il glamping",
    "L'albergo vs il B&B",
    "L'Airbnb vs l'hotel",
    "Il treno vs l'aereo",
    "L'auto vs il treno",
    "La moto vs l'auto",
    "Il monopattino vs la bicicletta",
    "L'auto elettrica vs l'auto ibrida",
    "Il diesel vs il benzina",
    "Il cambio automatico vs il cambio manuale",
    "Il SUV vs la berlina",
    "La city car vs il crossover",
    "IKEA vs Maisons du Monde",
    "Il divano in pelle vs il divano in tessuto",
    "Il letto matrimoniale vs il letto king size",
    "Il materasso a molle vs il materasso in memory",
    "La doccia vs il bagno nella vasca",
    "La vasca idromassaggio vs la sauna",
    "Il condizionatore vs il ventilatore",
    "Il riscaldamento a pavimento vs i termosifoni",
    "La lavastoviglie vs il lavaggio a mano",
    "L'asciugatrice vs lo stendino",
    "Il Bimby vs il robot da cucina normale",
    "La friggitrice ad aria vs il forno",
    "La piastra vs il barbecue",
    "Il barbecue a gas vs il barbecue a carbone",
    "Il caffè decaffeinato vs il caffè normale",
    "Il tè verde vs il tè nero",
    "La tisana vs la camomilla",
    "La spremuta fresca vs il succo confezionato",
    "L'acqua frizzante vs l'acqua naturale",
    "L'acqua del rubinetto vs l'acqua in bottiglia",
    "La pasta secca vs la pasta fresca",
    "Il riso basmati vs il riso arborio",
    "La quinoa vs il cous cous",
    "L'insalata mista vs l'insalata di riso",
    "La pizza margherita vs la pizza quattro formaggi",
    "La pizza con ananas vs la pizza tradizionale",
    "La focaccia vs la pizza bianca",
    "Il gelato al pistacchio vs il gelato alla nocciola",
    "Il tiramisù vs la panna cotta",
    "Il cornetto al bar vs i cereali a casa",
    "Il brunch vs la colazione tradizionale",
    "L'aperitivo vs la cena fuori",
    "Lo spritz vs il Negroni",
    "Il Mojito vs la Caipirinha",
    "Il gin tonic vs il Moscow mule",
    "La birra artigianale vs la birra industriale",
    "Il vino in bottiglia vs il vino al calice",
    "La degustazione vs la bevuta informale",
    "Il ristorante stellato vs la trattoria",
    "Il fast food vs lo street food",
    "La consegna a domicilio vs il ritiro in negozio",
    "Glovo vs Just Eat",
    "Deliveroo vs Uber Eats",
]
