#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Expansion 2: Another ~3000 concepts for the OverUnder deck.
Every concept passes the test: "Per me [X] è sopravvalutato/sottovalutato"
"""

MEGA_EXPANSION_2 = [
    # ─── CIBI SPECIFICI CHE TUTTI CONOSCONO ───
    "Il gelato Magnum al cioccolato bianco","Il ghiacciolo alla frutta",
    "La granita al caffè con panna","Il cornetto vuoto","Il cornetto alla crema",
    "Il cornetto integrale","Il cappuccino con la schiuma","L'espresso macchiato",
    "Il caffè lungo","Il caffè ristretto","Il caffè con il latte freddo a parte",
    "Il caffè del distributore automatico","Il caffè della macchinetta Nespresso",
    "Le fette biscottate con la marmellata","I biscotti del mattino",
    "I cereali con il latte","Il muesli con lo yogurt",
    "Lo yogurt greco","Lo yogurt alla frutta",
    "Il toast caldo del bar","La brioche siciliana col gelato",
    "Il panzerotto pugliese fritto","La focaccina riscaldata",
    "Il pranzo al sacco","Il panino del chiosco in spiaggia",
    "La tavola calda","Il self-service a pranzo",
    "Il menù fisso a pranzo","La pausa pranzo di un'ora",
    "Il pranzo in mensa","Il pranzo portato da casa in tupperware",
    "La schiscetta milanese","L'insalata in barattolo",
    "La pasta con il tonno","La pasta al burro e parmigiano",
    "La pasta al pomodoro e basilico","Il riso in bianco quando stai male",
    "La minestra della nonna","Il brodo di pollo quando hai il raffreddore",
    "Le uova strapazzate","Le uova alla coque","L'uovo alla Benedict",
    "La frittata con le patate","La frittata di cipolle",
    "Il formaggio grigliato","La fonduta di formaggi",
    "La raclette in inverno","La fondue di cioccolato",
    "I marshmallow sul fuoco","I popcorn al cinema",
    "I popcorn al microonde","Le patatine in busta",
    "Le patatine al gusto paprika","I pop corn al burro americani",
    "Il gelato alla stracciatella","Il gelato al cioccolato fondente",
    "Il gelato alla nocciola","Il gelato al limone","Il gelato alla fragola",
    "Il sorbetto al mango","La coppa gelato con panna montata",
    "Le crepe con la Nutella","I pancake americani con sciroppo d'acero",

    # ─── BRAND ALIMENTARI SPECIFICI ───
    "La Barilla","La De Cecco","La Rummo","La Voiello",
    "Il Parmigiano Reggiano 36 mesi","Il pecorino romano",
    "La mozzarella Zizzona di Battipaglia","Il Gorgonzola dolce",
    "Il Gorgonzola piccante","Lo Stracchino","Il Taleggio",
    "La Fontina valdostana","L'Asiago","Il Montasio friulano",
    "La ricotta fresca","La burrata di Andria",
    "Il prosciutto cotto Ferrarini","Il prosciutto crudo San Daniele",
    "Il salame Milano","La 'nduja calabrese",
    "La soppressata","Il capocollo","La guanciale di Amatrice",
    "Lo speck Alto Adige","La bresaola IGP della Valtellina",

    # ─── CATENE DI FAST FOOD ───
    "Burger King","KFC","Subway","Five Guys","Domino's Pizza",
    "Pizza Hut","Taco Bell","Wendy's","Chick-fil-A",
    "Old Wild West","Roadhouse","Alice Pizza",
    "Spontini Milano","La Prosciutteria",
    "200 Gradi","Berberè","Pizzium",

    # ─── CATENE ITALIANE E EUROPEE ───
    "Venchi","Grom","La Bottega del Caffè","Illy Caffè",
    "Lavazza","Caffè Vergnano","Segafredo","Caffè Borbone",

    # ─── APP E SERVIZI DIGITALI ───
    "Google Foto","iCloud","OneDrive","Notion","Trello",
    "Slack","Discord","Zoom","Microsoft Teams","Google Meet",
    "Figma","Canva","Adobe Photoshop","Adobe Premiere",
    "Final Cut Pro","DaVinci Resolve","Lightroom",
    "Shazam","Waze","Citymapper",
    "Moovit","FreeNow","BlaBlaCar",
    "Too Good To Go","TheFork","OpenTable",
    "Calm","Headspace","MyFitnessPal","Strava",
    "Nike Run Club","Peloton","Zwift",
    "Duolingo","Babbel","Memrise",
    "Khan Academy","Coursera","Udemy",
    "Audible","Kindle Unlimited","Scribd",
    "Goodreads","Letterboxd","IMDb",
    "Rotten Tomatoes","Metacritic",

    # ─── TIPOLOGIE DI RISTORANTI ───
    "Le osterie con vino della casa","Le pizzerie al taglio",
    "Le pizzerie con forno a legna","Le hamburgerie gourmet",
    "I ristoranti giapponesi all-you-can-eat","I ristoranti cinesi da asporto",
    "Le poke bowl","Le sushi bar","I ristoranti stellati Michelin",
    "Le trattorie turistiche in centro","I ristoranti panoramici",
    "I rooftop bar","I wine bar","Le birrerie artigianali",
    "I pub irlandesi","Le cantine sociali",
    "Le enoteche con tagliere","I cocktail bar speakeasy",
    "Le gelaterie artigianali","Le pasticcerie storiche",
    "I bar dei circoli sportivi","I chiringuito in spiaggia",
    "I ristoranti galleggianti","Le cene in barca",

    # ─── TIPI DI VACANZA ───
    "Le vacanze zaino in spalla","Le vacanze di lusso",
    "Le vacanze low cost","Le vacanze organizzate da agenzia",
    "Le vacanze fai da te","Il turismo lento",
    "Il turismo enogastronomico","Il turismo culturale",
    "Il turismo religioso","Il turismo sportivo",
    "Il turismo di avventura","Il turismo wellness",
    "Il turismo dentale","Il turismo medico all'estero",
    "Le vacanze in barca a vela","Le crociere nel Mediterraneo",
    "Le crociere nei fiordi","Le crociere ai Caraibi",
    "Le mini crociere del weekend","I viaggi in treno notturno",
    "I voli notturni","Gli scali lunghi in aeroporto",
    "Le lounge degli aeroporti","Il duty free",
    "Le valigie a mano Ryanair","Il bagaglio in stiva",
    "Il posto finestrino vs corridoio in aereo",
    "Il posto con più spazio per le gambe",

    # ─── TIPI DI ALLOGGIO ───
    "Gli ostelli della gioventù","I bed and breakfast",
    "Le pensioni","Gli hotel a 5 stelle","I boutique hotel",
    "I resort con spa","I glamping con bolla trasparente",
    "Le case sull'albero","Le yurte","Le roulotte vintage",
    "Le case vacanza","Gli affitti brevi","Le case scambio",
    "Il couchsurfing","Il campeggio libero",
    "Il campeggio organizzato","I bungalow al mare",

    # ─── COSE CHE SUCCEDONO IN VACANZA ───
    "La scottatura solare del primo giorno",
    "Dimenticare la crema solare","La tintarella perfetta",
    "I sandali dopo la scottatura","Le meduse in mare",
    "I ricci di mare","I granchi sulla spiaggia",
    "Fare il bagno a mezzanotte","Le docce fredde in spiaggia",
    "I castelli di sabbia elaborati","Le racchettoni in spiaggia",
    "Il pedalò","La canoa in mare","Lo sci d'acqua",

    # ─── COSE DI CASA ───
    "Il divano ad angolo","Il divano-letto per gli ospiti",
    "La TV in camera da letto","La TV da 75 pollici in salotto",
    "Il tavolo allungabile","Le sedie in stile scandinavo",
    "I mobili vintage restaurati","I mobili Ikea montati da soli",
    "Le librerie a parete","Il tappeto persiano",
    "Le tende pesanti","Le tende leggere",
    "I quadri alle pareti","Le stampe fotografiche incorniciate",
    "I poster dei film","I poster delle band",
    "I neon decorativi","Le piante grasse sul davanzale",
    "Il bonsai","L'orchidea in soggiorno",
    "Il cactus decorativo","I fiori freschi settimanali",
    "Le piante pendenti","L'edera interna",
    "La cucina a vista","La cucina con isola",
    "La cucina a L","Il bagno con doccia walk-in",
    "La vasca da bagno freestanding","Il terrazzo con vista",
    "Il balcone fiorito","Il giardino condominiale",
    "La piscina condominiale","Il garage doppio",
    "La cantina per i vini","La mansarda ristrutturata",

    # ─── STAGIONI E CLIMA ───
    "L'estate italiana","L'inverno mite del sud",
    "La primavera in Toscana","L'autunno nelle Langhe",
    "L'afa di agosto in città","Il Natale senza neve",
    "La neve a Roma","La pioggia a Milano",
    "Il vento di scirocco","La tramontana",
    "Il maestrale in Sardegna","Il caldo africano di luglio",
    "Le giornate corte d'inverno","Le giornate lunghe d'estate",
    "L'ora legale","L'ora solare","Il cambio dell'ora",

    # ─── MOMENTI DELL'ANNO ───
    "Il Capodanno","L'Epifania","Il Carnevale","Le ceneri",
    "La quaresima","La Pasqua","La Pasquetta",
    "Il 25 Aprile","Il Primo Maggio","Il 2 Giugno",
    "Il Ferragosto","Tutti i Santi","L'Immacolata",
    "La vigilia di Natale","Il pranzo di Natale",
    "Santo Stefano","San Silvestro",
    "Il Black Friday italiano","Il Cyber Monday",
    "I saldi invernali","I saldi estivi",
    "Il back to school di settembre","La riapertura dopo le ferie",

    # ─── MUSICA E CULTURA POP ───
    "Le playlist Spotify curate","Le playlist per studiare",
    "La lo-fi hip hop per concentrarsi","La musica ambient",
    "La musica elettronica da club","La minimal techno",
    "La house music","La deep house","La disco music anni '70",
    "Il funk","Il soul","Il R&B moderno","Il gospel",
    "Il blues","Il rock progressivo","Il metal estremo",
    "Il punk rock","Lo ska","Il reggae","Il dancehall",
    "L'afrobeat","La bossa nova","Il tango argentino",
    "Il flamenco","La musica celtica","La world music",
    "La musica da film","Le colonne sonore dei videogiochi",
    "Le cover delle canzoni famose","I mashup musicali",
    "I remix delle canzoni pop","Le versioni acustiche",
    "I concerti unplugged","I concerti in streaming",
    "I live su Instagram","I DJ set su YouTube",

    # ─── MEME E CULTURA INTERNET ───
    "I meme italiani","I meme di Joker","I meme di SpongeBob",
    "I meme sui gatti","I meme sulla scuola","I meme sul lunedì",
    "Le pagine meme su Instagram","I subreddit di meme",
    "Le pagine satiriche","Le vignette di satira politica",
    "I video virali su TikTok","Gli ASMR eating videos",
    "I mukbang","Le food challenge","I video satisfying",
    "I video fail compilation","I video di animali divertenti",
    "I video reaction","I video essay su YouTube",
    "I documentari su YouTube","Le video lezioni gratuite",

    # ─── COSE DEL CORPO ───
    "Avere i capelli ricci","Avere i capelli lisci",
    "La barba lunga","La barba curata","Il pizzetto",
    "I baffi","Essere alti","Essere bassi",
    "La voce profonda","La voce acuta",
    "Le lentiggini","Le fossette sulle guance",
    "Il sorriso con denti perfetti","Le sopracciglia folte",
    "I capelli bianchi portati con stile",
    "La calvizie accettata","Il trapianto di capelli",

    # ─── ATTIVITÀ DEL WEEKEND ───
    "Il brunch della domenica","La passeggiata al parco",
    "Il mercato rionale della domenica","La visita al museo",
    "Lo shopping in centro","Il cinema al pomeriggio",
    "La maratona di serie TV sul divano","I videogiochi tutto il giorno",
    "La gita fuori porta","La scampagnata con picnic",
    "La grigliata in giardino","Il barbecue con gli amici",
    "La partitella al parco","La corsa nel parco",
    "La bici lungo il fiume","La passeggiata sul lungomare",
    "L'aperitivo in terrazza","La cena a casa con amici",
    "La serata giochi da tavolo","La serata film a casa",
    "La serata karaoke","La serata bowling",
    "La serata escape room","Il concerto live",
    "La mostra d'arte contemporanea","Il teatro dialettale",
    "La fiera di quartiere","Il luna park",
    "Lo zoo","L'acquario","Il planetario",

    # ─── ESPERIENZE CULINARIE ───
    "La degustazione di vini","La visita a un'enoteca",
    "Il tour dei vigneti","La visita a un caseificio",
    "Il tour delle cantine","La visita a un frantoio",
    "Il corso di cucina in vacanza","La cena con delitto",
    "La cena sotto le stelle","Il picnic al tramonto",
    "Il brunch in terrazza","L'afternoon tea in un hotel di lusso",
    "La cena di gala","Il cenone di pesce della vigilia",
    "La grigliata di Ferragosto","La colazione in un B&B in campagna",

    # ─── CONCETTI RELAZIONALI ───
    "Il primo appuntamento","Il terzo appuntamento",
    "Conoscersi tramite app","Conoscersi tramite amici comuni",
    "Il colpo di fulmine","L'amore a prima vista",
    "Le farfalle nello stomaco","La fase della luna di miele",
    "La routine di coppia","I weekend romantici",
    "Le coppie che viaggiano sempre","Le coppie con hobbies diversi",
    "Le coppie che fanno tutto insieme","Le coppie che litigano in pubblico",
    "Le coppie che si vestono uguali","Le coppie con grande differenza d'età",
    "La proposta di matrimonio elaborata","La proposta di matrimonio semplice",
    "Le nozze d'argento","Le nozze d'oro",
    "Le amicizie dopo i 30 anni","Le amicizie di lunga data",
    "Fare nuove amicizie da adulti",

    # ─── COSE CHE DIVIDONO AL LAVORO ───
    "Il capo che manda email alle 23","I colleghi che scaldano il pesce in ufficio",
    "I colleghi che parlano al telefono ad alta voce","L'aria condizionata in ufficio",
    "Chi ruba il cibo dal frigo aziendale","Le riunioni in piedi",
    "Le riunioni da 5 minuti che durano un'ora",
    "Le presentazioni PowerPoint infinite",
    "I colleghi che rispondono a tutti nelle email",
    "Il Reply All accidentale","Le email con 47 persone in CC",
    "Il collega che arriva sempre in ritardo",
    "Il collega super puntuale","Il collega che se ne va sempre prima",
    "La postazione personalizzata","La scrivania sempre in ordine",
    "La scrivania caotica ma produttiva",

    # ─── SUPERMERCATO E SPESA ───
    "La spesa al discount","La spesa al mercato rionale",
    "La spesa dal contadino","La spesa al supermercato biologico",
    "Le marche del supermercato vs le marche famose",
    "I prodotti a marchio del distributore",
    "La frutta e verdura di stagione","La frutta e verdura esotica",
    "Le mele Pink Lady","Le banane Chiquita",
    "Gli avocado maturi al punto giusto","Le fragole fuori stagione",
    "I pomodori del contadino","Le zucchine dell'orto",
    "Le uova del contadino","Il latte fresco vs il latte a lunga conservazione",
    "Il latte vegetale","Il latte di soia","Il latte di mandorla",
    "Il latte d'avena","Il latte di riso","Il latte di cocco",

    # ─── COSE DELLA SCUOLA ───
    "La matematica","L'italiano come materia","La storia",
    "La filosofia al liceo","Il latino","Il greco antico",
    "L'educazione fisica","L'arte","La musica a scuola",
    "L'informatica come materia","Le scienze naturali",
    "La geografia","L'educazione civica","La religione a scuola",
    "Il professore preferito","La prof severa ma giusta",
    "Il prof che fa ridere","La supplenza",
    "L'autogestione scolastica","L'occupazione della scuola",
    "Lo sciopero studentesco","Il giornalino scolastico",
    "La rappresentanza di classe","Il rappresentante d'istituto",
    "La gita a Roma","La gita al museo","La gita in montagna",
    "Lo zaino pesante","I libri scolastici carissimi",
    "I libri di testo digitali","Il registro elettronico",

    # ─── CONCETTI TECNOLOGICI AVANZATI ───
    "La blockchain come tecnologia","Il Web3",
    "Il decentralized finance","I token digitali",
    "Le DAO","Il quantum computing",
    "L'edge computing","Il machine learning",
    "I large language models","Il prompt engineering",
    "L'AI generativa per le immagini","Midjourney",
    "DALL-E","Stable Diffusion","GitHub Copilot",
    "L'automazione del lavoro","I chatbot aziendali",
    "I customer service automatizzati","Le auto a guida autonoma livello 5",
    "I robot camerieri","I robot chirurghi",
    "Le protesi bioniche","Gli esoscheletri",
    "Gli impianti cerebrali","I chip sottocutanei",

    # ─── TIPI DI CONTENUTO ONLINE ───
    "I blog di viaggi","I blog di cucina","I blog di moda",
    "I blog di fitness","I blog di tecnologia",
    "Le newsletter curate","Le newsletter gratuite vs a pagamento",
    "I podcast intervista","I podcast narrativi",
    "I podcast educativi","I podcast comedy",
    "I podcast di cronaca nera","I podcast di storia",
    "Gli streaming live di gaming","Le speedrun di videogiochi",
    "I video GRWM (Get Ready With Me)","I video Day in My Life",
    "I video What I Eat in a Day","I video Room Tour",
    "I video di decluttering","I video di organizzazione casa",
    "I video di pulizia soddisfacenti","I time-lapse",
    "I vlog giornalieri","I travel vlog","I vlog di coppia",

    # ─── COSE DELLA VITA ADULTA ───
    "Pagare l'affitto","Pagare il mutuo",
    "Fare la dichiarazione dei redditi","Andare dal commercialista",
    "Rinnovare i documenti","Fare la fila in comune",
    "Prendere appuntamento dal medico","Andare a votare",
    "Pagare le bollette online","Cambiare operatore telefonico",
    "Cambiare banca","Sottoscrivere un'assicurazione",
    "Comprare un'auto usata","La revisione dell'auto",
    "Il tagliando dell'auto","Cambiare le gomme stagionali",
    "Il cambio gomme invernali estive","Fare benzina",
    "Il pieno di benzina","La benzina al self service vs servito",
    "Guidare in autostrada","Guidare in città nel traffico",
    "Guidare sotto la pioggia","Guidare di notte",
    "Parcheggiare in parallelo","Il parcheggio sotterraneo",

    # ─── DETTAGLI DELLA VITA QUOTIDIANA ───
    "La sveglia alle 6 del mattino","Il caffè appena svegli",
    "La doccia mattutina","La doccia serale",
    "Vestirsi di fretta la mattina","Scegliere cosa mettersi",
    "L'outfit del lunedì","I vestiti comodi per lavorare da casa",
    "Il pigiama tutto il giorno in smart working",
    "La pausa pranzo veloce","La pausa pranzo al parco",
    "Il sonnellino in pausa pranzo","La passeggiata digestiva",
    "La merenda delle 4","Lo spuntino di mezzanotte",
    "Guardare il telefono appena svegli",
    "Guardare il telefono prima di dormire",
    "La routine serale di skincare","La routine mattutina",
    "Il journaling prima di dormire","Leggere prima di dormire",
    "Ascoltare un podcast prima di dormire",
    "L'insonnia","Contare le pecore",
    "Il rumore bianco per dormire","I tappi per le orecchie per dormire",
    "La mascherina per gli occhi per dormire",
    "Il cuscino ergonomico cervicale","Il cuscino tra le ginocchia",

    # ─── ESPERIENZE SENSORIALI ───
    "Il profumo del caffè appena fatto","Il profumo del pane appena sfornato",
    "Il profumo della pioggia sull'asfalto","Il profumo del mare",
    "Il profumo dell'erba appena tagliata","Il profumo del bucato fresco",
    "Il rumore delle onde del mare","Il crepitio del fuoco nel camino",
    "Il rumore della pioggia sul tetto","Il silenzio della neve che cade",
    "Il canto degli uccelli al mattino","Il suono delle campane",
    "La sensazione della sabbia tra i piedi","L'acqua fredda del mare ai piedi",
    "Il sole in faccia dopo l'inverno","L'aria fresca di montagna",

    # ─── COSE NATALIZIE ───
    "Il presepe fatto a mano","L'albero di Natale vero vs finto",
    "Le luci di Natale in casa","Le luci di Natale in città",
    "I mercatini di Natale","Il vin brulé ai mercatini",
    "Le calze della Befana","I regali di Natale","Il Secret Santa",
    "Il calendario dell'avvento","Il calendario dell'avvento gourmet",
    "I film di Natale","I film di Natale americani",
    "Mamma ho perso l'aereo","Una poltrona per due",
    "La tombola napoletana","Il bingo natalizio",
    "Il panettone artigianale","Il pandoro con lo zucchero a velo",
    "Lo spumante a mezzanotte","Il brindisi di Capodanno",
    "I fuochi d'artificio di Capodanno","I botti di Capodanno",
    "I buoni propositi di gennaio",
]
