#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Expansion 5: ~2000 concepts for the OverUnder deck.
Every concept passes the test: "Per me [X] è sopravvalutato/sottovalutato"
"""

MEGA_EXPANSION_5 = [
    # ─── 1. TIPI DI RELAZIONE E CONVIVENZA (~150) ───
    "L'amicizia a distanza","L'amicizia tra colleghi","L'amicizia di coppia",
    "Le amicizie tossiche","Le amicizie di convenienza","Gli ex che restano amici",
    "Il co-parenting","La famiglia allargata","I figli del partner",
    "Le vacanze coi suoceri","I pranzi dalla suocera","I genitori invadenti",
    "I genitori assenti","I genitori elicottero","I genitori spazzaneve",
    "La convivenza prima del matrimonio","La convivenza tra coinquilini",
    "Il coinquilino ideale","Il coinquilino disordinato","Il coinquilino silenzioso",
    "La suocera che si intromette","Il suocero che non parla mai",
    "Il cognato invadente","La cognata competitiva",
    "Le riunioni di famiglia a Natale","Le riunioni di famiglia a Pasqua",
    "I parenti che si vedono solo ai funerali","I parenti che chiedono quando ti sposi",
    "I parenti che chiedono quando fai un figlio","La coppia aperta",
    "La relazione a distanza","La relazione poliamorosa",
    "L'amico di infanzia ritrovato su Facebook","L'amicizia nata in palestra",
    "L'amicizia nata in vacanza","L'amicizia tra vicini di casa",
    "Il gruppo WhatsApp della famiglia","Il gruppo WhatsApp dei genitori della classe",
    "Il gruppo WhatsApp del condominio","Il vicino di casa rumoroso",
    "Il vicino di casa che ti saluta sempre","Il vicino che ti porta le torte",
    "Il vicino che ti spia dalla finestra","La coppia che litiga sempre in pubblico",
    "La coppia che si lascia e si riprende","La coppia che sta insieme da vent'anni",
    "La coppia che fa tutto insieme","La coppia che non fa mai niente insieme",
    "Il fidanzato geloso","La fidanzata gelosa","L'amore platonico",
    "Il matrimonio civile","Il matrimonio in chiesa","Il matrimonio simbolico",
    "Il matrimonio in spiaggia","Il matrimonio in agriturismo",
    "Il matrimonio con pochi intimi","Il matrimonio da 300 invitati",
    "La lista nozze su Amazon","I confetti al matrimonio",
    "Le bomboniere del matrimonio","Il viaggio di nozze ai Caraibi",
    "Il viaggio di nozze in Giappone","L'addio al nubilato",
    "L'addio al celibato","La separazione consensuale",
    "Il divorzio con figli","L'avvocato divorzista",
    "La mediazione familiare","L'affidamento condiviso",
    "L'affidamento esclusivo","Gli alimenti all'ex coniuge",
    "La casa coniugale dopo il divorzio","Rifarsi una vita dopo il divorzio",
    "Il patrigno comprensivo","La matrigna moderna",
    "Il nonno che vizia i nipoti","La nonna che cucina sempre troppo",
    "I nonni che fanno da babysitter","Il fratello maggiore protettivo",
    "La sorella gemella","Il figlio unico","I fratelli che litigano da adulti",
    "L'amicizia tra maschio e femmina","L'amico che sparisce quando si fidanza",
    "L'amica che sparisce quando si fidanza","L'amico che ti cerca solo quando ha bisogno",
    "Il migliore amico del cuore","L'amica del cuore","Il testimone di nozze",
    "La damigella d'onore","Il padrino di battesimo","La madrina di cresima",
    "La cena tra coppie di amici","L'aperitivo tra mamme",
    "Il brunch tra amiche","La chat di gruppo tra amici storici",
    "L'amico che non risponde mai ai messaggi","L'amico che risponde dopo tre giorni",
    "L'amico puntuale","L'amico sempre in ritardo",
    "L'amicizia tra genitori dei compagni di scuola","Il partner che non va d'accordo coi tuoi amici",
    "La suocera che ti adora","La suocera che ti odia",
    "Il pranzo di Natale dai suoceri","Il Capodanno con gli amici vs con la famiglia",
    "I genitori che vivono attraverso i figli","I genitori che postano i figli sui social",
    "I genitori che non danno regole","I genitori troppo severi",
    "La famiglia che non parla dei problemi","La famiglia troppo aperta",
    "Il figlio preferito","Il figlio ribelle","Il figlio responsabile",
    "Le dinamiche tra fratelli e sorelle","L'amicizia che finisce senza un motivo",
    "L'amicizia che dura tutta la vita","L'amico d'infanzia",
    "L'amicizia nata online","L'amico che conosci solo su internet",
    "Il partner che va d'accordo con la tua famiglia","La coppia che convive col gatto",
    "La coppia che convive col cane","La coppia senza figli per scelta",
    "I genitori single","Le mamme tigri","I papà chioccia",
    "La famiglia tradizionale","La famiglia arcobaleno",
    "L'amicizia tra generazioni diverse","Il mentore che ti cambia la vita",

    # ─── 2. TIPI DI ABITAZIONE E ARREDAMENTO (~150) ───
    "Il soppalco","La cucina a isola con sgabelli","Il bagno padronale",
    "La cabina armadio","Il ripostiglio","La lavanderia separata",
    "Il seminterrato ristrutturato","Il sottotetto recuperato",
    "La veranda chiusa","La pergola bioclimatica","Il gazebo in giardino",
    "La casetta degli attrezzi","Il monolocale in centro",
    "Il bilocale con soppalco","Il trilocale con terrazzo",
    "L'attico con vista panoramica","Il loft industriale",
    "La mansarda con travi a vista","Il rustico in campagna",
    "La cascina ristrutturata","La villa con piscina",
    "La villetta a schiera","La casa indipendente",
    "Il condominio anni '70","Il palazzo d'epoca",
    "La casa di ringhiera milanese","La casa cantoniera",
    "Il trullo pugliese","Il dammuso di Pantelleria",
    "La baita di montagna","Lo chalet in legno",
    "La tiny house","La casa container",
    "La casa passiva a risparmio energetico","La casa domotica",
    "Il giardino d'inverno","La serra in giardino",
    "Il patio interno","Il cortile condominiale",
    "Il terrazzo con piante","Il balcone fiorito",
    "Il balcone con vista mare","Il terrazzo panoramico",
    "La cucina a vista sul soggiorno","La cucina separata",
    "La cucina in muratura","La cucina componibile IKEA",
    "La cucina su misura","Il piano cottura a induzione",
    "Il piano cottura a gas","Il forno a incasso",
    "Il frigorifero americano","Il frigorifero a due ante",
    "La lavastoviglie da incasso","La lavasciuga",
    "L'asciugatrice separata","Il robot aspirapolvere",
    "L'aspirapolvere Dyson","Il Roomba","Il Folletto Vorwerk",
    "Il divano ad angolo","Il divano letto","Il divano in pelle",
    "Il divano in tessuto sfoderabile","La poltrona reclinabile",
    "La poltrona massaggiante","Il letto matrimoniale king size",
    "Il letto contenitore","Il letto a castello per adulti",
    "Il materasso in memory foam","Il materasso a molle insacchettate",
    "Il materasso in lattice","Il cuscino ergonomico",
    "Le lenzuola in raso","Le lenzuola in lino","Il piumone d'oca",
    "La libreria a parete","La libreria Billy di IKEA",
    "La scrivania standing desk","La scrivania con doppio monitor",
    "La sedia ergonomica da ufficio","La sedia gaming",
    "Il tavolo allungabile","Il tavolo in legno massello",
    "Il tavolo in cristallo","Le sedie Kartell trasparenti",
    "Il tappeto persiano","Il tappeto moderno geometrico",
    "Le tende oscuranti","Le tende a rullo","Le veneziane",
    "Il parquet in rovere","Il gres porcellanato effetto legno",
    "Il pavimento in resina","Il microcemento","La carta da parati moderna",
    "La boiserie a parete","I pannelli fonoassorbenti",
    "Le luci LED a striscia","Il lampadario di design",
    "La lampada da terra ad arco","Le plafoniere smart",
    "Lo specchio da bagno con luce LED","La vasca freestanding",
    "La doccia walk-in","Il soffione a pioggia","La jacuzzi da interno",
    "Il bidet portatile","Il WC sospeso","Il WC con bidet integrato",
    "Il termoarredo in bagno","Le piastrelle esagonali",
    "Il mosaico in bagno","La porta scorrevole a scomparsa",
    "La porta a vetro satinato","La porta blindata",
    "L'armadio a muro","L'armadio con ante scorrevoli",
    "Lo specchio a figura intera","Il quadro d'autore in casa",
    "Le stampe Ikea alle pareti","Le foto incorniciate",
    "Le piante da interno","Il ficus gigante in salotto",
    "La monstera deliciosa","Le piante grasse sul davanzale",
    "Il giardino verticale indoor","L'orto sul balcone",
    "La cuccia del cane di design","Il tiragraffi a torre per gatti",
    "Il camino a legna tradizionale","La stufa in ghisa",
    "Il riscaldamento a pavimento","I termosifoni in ghisa vintage",
    "L'aria condizionata canalizzata","Lo split a parete",
    "Il ventilatore a colonna","Il deumidificatore portatile",
    "La zanzariera magnetica","Le tapparelle elettriche",
    "Il videocitofono smart","La serratura smart",
    "L'allarme antifurto con telecamere","Le telecamere di sorveglianza esterne",
    "Il garage doppio","Il box auto sotterraneo",
    "Il posto auto condominiale","La cantina nel palazzo",

    # ─── 3. BEVANDE SPECIFICHE (~150) ───
    "Lo Spritz Select","Lo Spritz Campari","Il Bellini",
    "Il Rossini","La Mimosa cocktail","Il Boulevardier",
    "Il Manhattan","L'Old Fashioned","Il Daiquiri",
    "La Piña Colada","La Margarita","Il Cosmopolitan",
    "Il Martini Dry","Il Gin Fizz","Il Tom Collins",
    "Lo Zombie cocktail","Il Long Island Iced Tea","Il Sex on the Beach",
    "Il Tequila Sunrise","Il Moscow Mule","Il Dark 'n' Stormy",
    "Il Mojito alla fragola","Il Mojito al passion fruit",
    "Il Negroni Sbagliato","Il Negroni classico","L'Americano cocktail",
    "Lo Hugo Spritz","Il Limoncello Spritz","Il Gin Tonic premium",
    "Il Gin Tonic con cetriolo","Il Gin Tonic al pompelmo rosa",
    "Il Whiskey Sour","L'Amaretto Sour","Il Penicillin cocktail",
    "Il Paper Plane cocktail","La Caipirinha","La Caipiroska",
    "Il Paloma cocktail","Il Espresso Martini","Il French 75",
    "Il Kir Royale","Lo Champagne brut","Il Prosecco DOC",
    "Il Franciacorta","Il Crémant d'Alsace","Il Cava spagnolo",
    "Il Lambrusco frizzante","Il Pignoletto dei Colli Bolognesi",
    "Il Chianti Classico","Il Brunello di Montalcino",
    "Il Barolo","Il Barbaresco","L'Amarone della Valpolicella",
    "Il Sassicaia","Il Tignanello","Il vino biodinamico",
    "Il vino naturale","Il vino orange","Il pet-nat",
    "La birra artigianale IPA","La birra artigianale stout",
    "La birra artigianale lager","La birra weiss tedesca",
    "La birra trappista belga","La birra alla spina vs in bottiglia",
    "La Guinness alla spina","La Peroni Gran Riserva",
    "La Moretti Baffo d'Oro","L'Ichnusa non filtrata",
    "La Menabrea","La birra Baladin","La birra del Borgo",
    "Il sidro di mele","L'idromele artigianale","Il sake giapponese",
    "Il soju coreano","La grappa barricata","La grappa monovitigno",
    "Il limoncello fatto in casa","Il nocino della nonna",
    "Il mirto sardo","L'amaro Montenegro","L'amaro Averna",
    "Il Fernet Branca","Il Cynar","L'Aperol liscio",
    "Il Campari liscio","Il Rabarbaro Zucca","Lo Strega",
    "Il Sambuca","La Vecchia Romagna","Il brandyStock 84",
    "Il rum invecchiato","Il rum agricole","Il whisky torbato",
    "Il whisky giapponese","Il bourbon americano","Il rye whiskey",
    "Il mezcal","La tequila reposado","La tequila añejo",
    "Il gin artigianale italiano","La vodka premium",
    "Il kombucha","Il kefir d'acqua","Lo smoothie verde",
    "Il centrifugato di frutta","L'estratto di zenzero e curcuma",
    "Il golden milk","Il matcha latte","Il chai latte",
    "Il caffè filtro","Il caffè cold brew","L'Irish Coffee",
    "Il caffè turco","Il caffè vietnamita","Il flat white",
    "Il cortado","L'affogato al caffè","La cioccolata calda densa",
    "La tisana allo zenzero","La tisana alla camomilla",
    "Il tè verde Sencha","Il tè Earl Grey","Il tè Oolong",
    "Il bubble tea","Il bubble tea al taro","L'acqua tonica premium",
    "L'acqua di cocco","L'acqua aromatizzata al cetriolo e menta",
    "La limonata fatta in casa","Il chinotto San Pellegrino",
    "L'aranciata amara","Il crodino","Il Sanbittèr",
    "La cedrata Tassoni","La gassosa al limone",
    "L'orzata siciliana","Il tamarindo","La spuma bionda",

    # ─── 4. COSE CHE SI COMPRANO ONLINE (~100) ───
    "Le recensioni Amazon","Le recensioni a 5 stelle sospette",
    "Il tracking del pacco","L'ansia da consegna",
    "Il pacco in giacenza","La consegna programmata",
    "Il locker Amazon","Il reso gratuito",
    "Lo shopping compulsivo online","Il carrello abbandonato",
    "La wishlist su Amazon","Amazon Prime","Amazon Prime Day",
    "Il Black Friday online","Il Cyber Monday",
    "Le offerte lampo di Amazon","I coupon sconto online",
    "I codici promozionali","Il cashback sugli acquisti online",
    "Comprare vestiti online senza provarli","La taglia che non corrisponde mai",
    "Le foto dei prodotti vs la realtà","I prodotti sponsorizzati su Amazon",
    "Comprare su Temu","Comprare su Shein","Comprare su AliExpress",
    "Comprare su Zalando","Comprare su Vinted","Vendere su Vinted",
    "Comprare su Subito.it","Trattare il prezzo su Subito.it",
    "Comprare su eBay","Le aste su eBay","Il dropshipping",
    "I prodotti ricondizionati","Il refurbished Apple",
    "Comprare il telefono online","Comprare il materasso online",
    "Comprare gli occhiali online","Comprare i farmaci online",
    "Comprare la spesa online","La spesa con consegna a domicilio",
    "Esselunga a casa","Glovo per la spesa","Gorillas e la spesa veloce",
    "Le box in abbonamento mensile","I cofanetti regalo Smartbox",
    "Comprare corsi online","Gli e-book vs i libri cartacei",
    "L'audiolibro su Audible","L'abbonamento Kindle Unlimited",
    "Le notifiche di calo prezzo","I comparatori di prezzo",
    "Trovaprezzi.it","Il prezzo dinamico di Amazon",
    "I prodotti Amazon's Choice","I prodotti bestseller su Amazon",
    "Comprare su Amazon Warehouse","I pacchi a sorpresa",
    "Le mystery box online","Il unboxing video",
    "Il pagamento a rate online","Klarna per pagare a rate",
    "PayPal per gli acquisti online","La carta prepagata per comprare online",
    "Le truffe negli acquisti online","I siti clone truffaldini",
    "L'assicurazione sulla spedizione","Il pacco smarrito",
    "Il corriere che non suona il campanello","Il corriere che lascia il pacco al vicino",
    "La consegna il giorno dopo","La consegna in giornata",
    "Il packaging eco-sostenibile","L'over-packaging di Amazon",
    "Le bolle d'aria nell'imballaggio","Lo scotch che non si stacca",
    "Comprare regali di Natale all'ultimo minuto online",
    "I regali personalizzati su Etsy","Comprare su Etsy",
    "L'artigianato su Etsy vs la produzione di massa",
    "I gadget tech inutili comprati online","Gli accessori per il telefono comprati online",
    "Le cover del telefono comprate online","I caricatori non originali",

    # ─── 5. TIPI DI CONTENUTO SOCIAL (~150) ───
    "I reel motivazionali","I reel di cucina veloce","I reel di trasformazione",
    "I prima e dopo","Le foto con filtro invecchiamento",
    "Le foto ricordo di Facebook","I post del lunedì motivazionale",
    "I post del venerdì","Le foto al tramonto","Le foto al caffè",
    "Le foto di piedi in spiaggia","Le foto col piatto gourmet",
    "I selfie in palestra","I selfie allo specchio","I selfie in ascensore",
    "I selfie con il filtro cane","I selfie senza filtri",
    "Le stories con la musica di sottofondo","Le stories con il countdown",
    "Le stories con il sondaggio","Le stories con il quiz",
    "Le stories con la domanda aperta","Le stories del buongiorno",
    "Le stories della buonanotte","Le stories dal ristorante",
    "Le stories dal concerto","Le stories dell'allenamento",
    "Le stories motivazionali col tramonto","Le dirette Instagram",
    "Le dirette TikTok","Le dirette Twitch","I live shopping su TikTok",
    "I video ASMR","I video di slime","I video oddly satisfying",
    "I video di pulizia della casa","I video di decluttering",
    "I video di organizzazione del frigo","I video di meal prep",
    "I video what I eat in a day","I video day in my life",
    "I video get ready with me","I video morning routine",
    "I video night routine","I video study with me",
    "I video di unboxing","I video di haul di vestiti",
    "I video di prova trucchi","I video di skincare routine",
    "I video tutorial di trucco","I video di nail art",
    "I thread su Twitter","I meme su Instagram","I meme su Reddit",
    "I meme su TikTok","Le pagine di meme italiane",
    "I video reaction","I video di prank","I video di challenge virali",
    "I video di scherzi telefonici","Le foto del cibo prima di mangiare",
    "Le foto dell'outfit del giorno","I post di outfit of the day",
    "I caroselli informativi su Instagram","Le infografiche su LinkedIn",
    "I post motivazionali su LinkedIn","I post di auto-celebrazione su LinkedIn",
    "Le storie di successo su LinkedIn","Il post del nuovo lavoro su LinkedIn",
    "Il post del licenziamento positivo su LinkedIn","I contenuti di crescita personale",
    "I guru del mindset sui social","I coach di vita sui social",
    "Gli influencer di finanza personale","Gli influencer di criptovalute",
    "I tiktoker di BookTok","I tiktoker di CleanTok","I tiktoker di FoodTok",
    "I tiktoker di GymTok","I tiktoker di SkinTok",
    "Le recensioni su TripAdvisor","Le recensioni su Google Maps",
    "I commenti negativi sotto i post","I commenti di hater",
    "I troll nei commenti","Le polemiche nei commenti",
    "I flame war sui social","Le shitstorm social",
    "Il cancel culture","Il virtue signaling","Il rage bait",
    "Il clickbait","I titoli acchiappaclick","Le fake news sui social",
    "I deepfake","Le foto ritoccate con Facetune","I filtri di bellezza",
    "La realtà vs Instagram","Le aspettative vs la realtà",
    "I post sponsorizzati degli influencer","I contenuti branded",
    "L'unboxing sponsorizzato","Il codice sconto dell'influencer",
    "Le collaborazioni tra influencer e brand","Il product placement nei video",
    "I podcast su Spotify","I podcast di true crime",
    "I podcast di attualità italiana","I podcast di chiacchiere",
    "I vlog su YouTube","I canali YouTube di divulgazione",
    "I canali YouTube di gaming","Le clip su YouTube Shorts",
    "I video compilazione su YouTube","I video essay su YouTube",
    "Le foto professionali su Instagram","Le foto casual su Instagram",
    "Il feed Instagram curato","Il feed Instagram a griglia",
    "Le note su Instagram","I canali broadcast su Instagram",
    "Le community su Reddit","I subreddit italiani",
    "I post virali su X/Twitter","I tweet polemici",
    "I tweet notturni","Il subtweeting",
    "I gruppi Facebook tematici","I marketplace di Facebook",

    # ─── 6. MARCHE DI AUTO SPECIFICHE (~100) ───
    "La Tesla Model 3","La Tesla Model Y","La Tesla Model S",
    "La Fiat 500X","La Fiat Tipo","La Fiat Panda ibrida",
    "La Fiat 500 elettrica","La Fiat 600 nuova","La Lancia Ypsilon nuova",
    "La Jeep Renegade","La Jeep Compass","La Jeep Avenger",
    "La Seat Ibiza","La Seat Leon","La Seat Arona",
    "La Skoda Octavia","La Skoda Kamiq","La Skoda Fabia",
    "La Cupra Formentor","La Cupra Born","La Cupra Leon",
    "La Peugeot 208","La Peugeot 2008","La Peugeot 308",
    "La Renault Clio","La Renault Captur","La Renault Mégane E-Tech",
    "La Dacia Duster","La Dacia Sandero","La Dacia Spring elettrica",
    "La Opel Corsa","La Opel Mokka","La Opel Astra",
    "La Citroën C3","La Citroën C3 Aircross","La Citroën C4",
    "La Volkswagen Golf","La Volkswagen Polo","La Volkswagen T-Roc",
    "La Volkswagen ID.3","La Volkswagen ID.4","La Volkswagen Tiguan",
    "La BMW Serie 1","La BMW Serie 3","La BMW X1",
    "La BMW iX3","La Mercedes Classe A","La Mercedes GLA",
    "La Mercedes EQA","L'Audi A3","L'Audi Q3",
    "L'Audi e-tron","La Volvo XC40","La Volvo C40 Recharge",
    "La Hyundai Tucson","La Hyundai i20","La Hyundai Kona Electric",
    "La Kia Sportage","La Kia Niro","La Kia EV6",
    "La Toyota Yaris","La Toyota Yaris Cross","La Toyota Corolla",
    "La Toyota RAV4 ibrida","La Toyota C-HR","La Honda Civic",
    "La Mazda CX-5","La Mazda 3","La Mazda MX-5",
    "La Nissan Qashqai","La Nissan Juke","La Nissan Leaf",
    "La Ford Puma","La Ford Fiesta","La Ford Kuga",
    "La MG ZS","La MG4 Electric","La BYD Atto 3",
    "L'Alfa Romeo Giulia","L'Alfa Romeo Tonale","L'Alfa Romeo Stelvio",
    "La Maserati Grecale","La Porsche Cayenne","La Porsche Macan",
    "La Mini Cooper","La Mini Countryman","La Smart fortwo",
    "La Smart #1 elettrica","Il SUV come auto di famiglia",
    "La station wagon vs il SUV","L'auto elettrica vs l'ibrida",
    "L'auto a noleggio lungo termine","Il leasing auto",
    "L'auto nuova vs l'usata","L'auto km zero",

    # ─── 7. PERSONAGGI DEI FUMETTI E MANGA (~100) ───
    "Goku vs Vegeta","Naruto vs Sasuke","Luffy di One Piece",
    "Zoro di One Piece","Sanji di One Piece","Nami di One Piece",
    "Levi di Attack on Titan","Eren Jaeger","Mikasa Ackerman",
    "Light Yagami","L di Death Note","Ryuk di Death Note",
    "Tanjiro di Demon Slayer","Nezuko di Demon Slayer","Zenitsu di Demon Slayer",
    "Gojo Satoru","Itadori Yuji","Sukuna di Jujutsu Kaisen",
    "Denji di Chainsaw Man","Makima di Chainsaw Man","Power di Chainsaw Man",
    "Anya Forger","Loid Forger","Yor Forger",
    "Spike Spiegel di Cowboy Bebop","Edward Elric di Fullmetal Alchemist",
    "Alphonse Elric","Gon Freecss di Hunter x Hunter","Killua Zoldyck",
    "Hisoka di Hunter x Hunter","Saitama di One Punch Man","Genos di One Punch Man",
    "Mob di Mob Psycho 100","Deku di My Hero Academia","All Might",
    "Bakugo di My Hero Academia","Todoroki di My Hero Academia",
    "Shinji Ikari di Evangelion","Asuka Langley","Rei Ayanami",
    "Sailor Moon","Goku Black","Freezer di Dragon Ball",
    "Vegito","Gohan di Dragon Ball","Piccolo di Dragon Ball",
    "Jotaro Kujo di JoJo","Dio Brando di JoJo","Giorno Giovanna di JoJo",
    "Monkey D. Dragon di One Piece","Shanks di One Piece","Barbabianca di One Piece",
    "Ken Kaneki di Tokyo Ghoul","Lelouch di Code Geass",
    "Guts di Berserk","Griffith di Berserk","Astro Boy",
    "Lupin III","Jigen di Lupin","Goemon di Lupin",
    "Fujiko Mine","L'ispettore Zenigata","Conan Edogawa",
    "Holly e Benji","Ken il Guerriero","Pegasus di Saint Seiya",
    "Andromeda di Saint Seiya","Totoro di Miyazaki",
    "Chihiro de La Città Incantata","Howl del Castello Errante",
    "San di Principessa Mononoke","Nausicaa della Valle del Vento",
    "Tex Willer","Dylan Dog","Diabolik","Eva Kant",
    "Corto Maltese","Valentina di Crepax","Nathan Never",
    "Zagor","Topolino vs Paperino","Paperone",
    "Qui Quo Qua","Gambadilegno","Lupo Alberto",
    "I Peanuts","Mafalda","Calvin e Hobbes",
    "Garfield","Snoopy","Spider-Man vs Batman",
    "Wolverine dei X-Men","Deadpool","Iron Man vs Captain America",
    "Thor vs Hulk","Thanos","Joker vs Harley Quinn",
    "Superman vs Goku","I manga shonen vs seinen",
    "I manga shojo vs josei","Gli anime doppiati vs sottotitolati",
    "I manga in italiano vs in originale",

    # ─── 8. COSE LEGATE ALLA GRAVIDANZA E NEONATI (~100) ───
    "Il baby shower","Il gender reveal","La lista nascita",
    "Il passeggino trio","Il seggiolino auto","Il fasciatoio",
    "La culla co-sleeping","Il ciuccio","Il biberon anticolica",
    "Lo sterilizzatore","Il baby monitor","La sdraietta",
    "Il box per bambini","Il marsupio neonato","La fascia porta bebè",
    "L'ovetto per l'auto","Il seggiolone Stokke","Il seggiolone IKEA",
    "I pannolini Pampers","I pannolini lavabili","I pannolini ecologici",
    "Le salviettine umidificate","La crema cambio pannolino",
    "L'olio di mandorle per il pancione","Le smagliature in gravidanza",
    "La nausea del primo trimestre","Le voglie in gravidanza",
    "L'ecografia morfologica","L'ecografia 3D","Il corso preparto",
    "Il parto naturale","Il parto cesareo","Il parto in acqua",
    "L'epidurale","Il parto indotto","La doula",
    "Il rooming-in in ospedale","L'allattamento al seno",
    "L'allattamento artificiale","Il tiralatte","La montata lattea",
    "Lo svezzamento tradizionale","L'autosvezzamento",
    "Le pappe biologiche","Gli omogeneizzati","I biscotti Plasmon",
    "La camomilla Plasmon","I pediatri che spaventano",
    "I consigli non richiesti sulla maternità","Le nonne che danno consigli sullo svezzamento",
    "Il sonno del neonato","Il metodo Estivill","Il co-sleeping",
    "La routine della nanna","Le notti insonni coi neonati",
    "I vestiti del neonato firmati","I vestiti del neonato usati",
    "Lo scambio vestiti tra mamme","Il corredino nascita",
    "La torta di pannolini","I fiocchi nascita sulla porta",
    "La scelta del nome del bambino","Il significato del nome",
    "I nomi italiani classici vs moderni","I nomi stranieri per i figli",
    "La cameretta del neonato","La giostrina sulla culla",
    "I giochi Montessori per neonati","I libri sensoriali",
    "Il tappetone da gioco","La palestrina per neonati",
    "I denti che spuntano","Il primo dentino","La febbre dei denti",
    "Le coliche del neonato","Il massaggio neonatale",
    "I primi passi","Le prime parole","Il primo compleanno",
    "La torta smash cake","Le foto mensili del neonato",
    "I servizi fotografici per neonati","Il battesimo",
    "Il rinfresco del battesimo","La bomboniera del battesimo",
    "Il nido vs la tata","L'asilo nido comunale",
    "L'asilo nido privato","La babysitter di fiducia",
    "L'inserimento al nido","Il distacco dalla mamma",
    "La depressione post-partum","Il congedo di maternità",
    "Il congedo di paternità","Il rientro al lavoro dopo la maternità",
    "La conciliazione lavoro-famiglia","Il senso di colpa materno",
    "La pressione sociale sulla maternità","Le mamme perfette su Instagram",
    "I papà moderni","Il papà che cambia i pannolini",

    # ─── 9. GIOCHI E PASSATEMPI DA SPIAGGIA (~100) ───
    "Le racchettoni","Le bocce da spiaggia","Il frisbee al mare",
    "Il beach volley improvvisato","I tuffi dagli scogli",
    "Fare snorkeling","Raccogliere conchiglie",
    "I castelli di sabbia elaborati","Seppellire qualcuno nella sabbia",
    "Il materassino gonfiabile","La ciambella gonfiabile",
    "Il salvagente a fenicottero","Il materassino a pizza",
    "Il materassino a unicorno","La canoa gonfiabile",
    "Il SUP (Stand Up Paddle)","Il pedalò","La banana boat",
    "Il gommone trainato","Lo sci nautico","Il wakeboard",
    "Il surf al mare","Il bodyboard","Lo snorkeling con le pinne",
    "Le immersioni con la bombola","La pesca subacquea",
    "La pesca dalla scogliera","La pesca col retino per bambini",
    "Il beach soccer","Il beach tennis","Il foot volley",
    "Il tamburello da spiaggia","Giocare a carte sotto l'ombrellone",
    "La briscola in spiaggia","Il burraco sotto l'ombrellone",
    "Il sudoku sotto l'ombrellone","Le parole crociate al mare",
    "I giochi con la palla in acqua","Il gavettone","La battaglia d'acqua",
    "Le pistole ad acqua","I secchielli e le palette",
    "Le formine per la sabbia","I canali nella sabbia",
    "Le buche profonde nella sabbia","Il bagnasciuga per passeggiare",
    "La camminata sulla battigia al tramonto","Il jogging sulla spiaggia",
    "Lo yoga in spiaggia all'alba","La meditazione al suono delle onde",
    "La lettura sotto l'ombrellone","L'audiolibro in spiaggia",
    "La musica col bluetooth in spiaggia","Il picnic in spiaggia",
    "Il pranzo al sacco in spiaggia","La focaccia in spiaggia",
    "L'anguria in spiaggia","La granita in spiaggia",
    "Il gelato in spiaggia","La birra ghiacciata in spiaggia",
    "Il cocktail al chiringuito","L'aperitivo al tramonto in spiaggia",
    "Il falò in spiaggia","La chitarra intorno al falò",
    "Le stelle cadenti in spiaggia","La notte in spiaggia",
    "I giochi notturni in spiaggia","La discoteca sulla spiaggia",
    "Il cinema all'aperto in spiaggia","La caccia al tesoro in spiaggia",
    "Il cerchio di biglie sulla sabbia","I birilli sulla sabbia",
    "Il kite surf","Il windsurf","Il kayak di mare",
    "La moto d'acqua","Il parasailing","Il flyboard",
    "Il banana ride","Il tubing in mare","Lo scivolo gonfiabile in acqua",
    "Il tappeto elastico in acqua","Il trampolino galleggiante",
    "Il campetto da beach volley fisso","Il torneo di racchettoni",
    "I giochi di società in spiaggia","Il Monopoly in spiaggia",
    "Le carte UNO in spiaggia","Il bingo da spiaggia",
    "La tombola estiva","Le bocce nell'acqua bassa",
    "Le gare di nuoto tra amici","Le gare di tuffi",
    "Chi fa il tuffo più bello","La sfida a chi resta più a lungo sott'acqua",
    "La sfida a chi nuota più lontano","Le capriole in acqua",
    "I gavettoni dal pedalò",

    # ─── 10. CONCETTI DI MODA MASCHILE (~100) ───
    "Il completo sartoriale","La cravatta sottile","La cravatta larga",
    "Il nodo alla cravatta Windsor","La pochette nel taschino",
    "I gemelli della camicia","Le bretelle","Il gilet sotto la giacca",
    "Il blazer con i jeans","La camicia con i polsini arrotolati",
    "I mocassini senza calzini","Le scarpe Oxford","Le scarpe Derby",
    "Le scarpe monk strap","I Chelsea boots","Gli stivaletti da uomo",
    "Le sneakers bianche minimali","Le sneakers chunky da uomo",
    "Le New Balance da uomo","Le Nike Air Max","Le Adidas Stan Smith",
    "Le Converse All Star da uomo","Le Vans Old Skool",
    "Il trench coat maschile","Il cappotto cammello","Il giaccone Barbour",
    "Il piumino leggero","Il bomber da uomo","La giacca di pelle",
    "La giacca in denim","Il giubbotto di velluto a coste",
    "Il maglione a collo alto","Il dolcevita nero da uomo",
    "Il maglione con lo scollo a V","La felpa con cappuccio",
    "La felpa oversize","La felpa con zip","Il cardigan da uomo",
    "La polo Ralph Lauren","La polo Lacoste","La camicia di lino",
    "La camicia Oxford button-down","La camicia a righe",
    "La camicia hawaiana","La t-shirt bianca basica",
    "La t-shirt con scollo a V","La canottiera estiva",
    "I jeans slim fit","I jeans regular fit","I jeans baggy",
    "I jeans dritti classici","I chinos","I pantaloni cargo",
    "I pantaloni in lino estivi","I bermuda al ginocchio",
    "I bermuda cargo","Il costume da bagno a pantaloncino",
    "Il costume da bagno a slip","Il costume da bagno fantasia",
    "L'orologio automatico vs al quarzo","L'orologio da polso classico",
    "Il Casio G-Shock","Lo Swatch","Il Rolex Submariner",
    "L'Omega Speedmaster","Il Seiko Presage",
    "Gli occhiali da sole Ray-Ban Aviator","Gli occhiali Ray-Ban Wayfarer",
    "Gli occhiali Persol","Gli occhiali Oakley sportivi",
    "La cintura in pelle","La cintura intrecciata",
    "Il portafoglio in pelle","Il portacarte minimalista",
    "Lo zaino da uomo elegante","La borsa messenger",
    "La ventiquattrore","Il borsone da weekend","Il profumo da uomo forte",
    "Il profumo da uomo fresco","L'acqua di colonia classica",
    "La barba curata","La barba lunga","La barba corta ben definita",
    "I baffi a manubrio","Il pizzetto","Lo shaving tradizionale con rasoio",
    "Il taglio di capelli sfumato","Il taglio undercut","Il ciuffo all'indietro",
    "I capelli lunghi da uomo","Il man bun","La skincare maschile",
    "Il contorno occhi da uomo","La crema idratante da uomo",
    "Il dopobarba","Le sopracciglia curate da uomo",
    "Il total black da uomo","L'outfit smart casual",
    "Il business casual","Il dress code da ufficio",

    # ─── 11. APP DI DATING E RELAZIONI (~100) ───
    "Tinder Gold","Bumble Premium","Hinge",
    "Happn","Once","The Inner Circle",
    "Raya","L'algoritmo di Tinder","Il profilo perfetto su Tinder",
    "Le bio divertenti su Tinder","Le foto profilo scelte bene",
    "Il super like","Il boost su Tinder","Lo swipe a destra",
    "Il match che non risponde","Il match che risponde dopo settimane",
    "La prima conversazione su Tinder","I messaggi copia-incolla su Tinder",
    "L'approccio creativo nel primo messaggio","Il ghosting dopo il match",
    "Il ghosting dopo il primo appuntamento","Il breadcrumbing",
    "Il benching","Lo zombieing","Il cushioning",
    "Il catfishing","Le foto vecchie di tre anni","Le foto con i filtri esagerati",
    "La foto con il pesce in mano","La foto in palestra",
    "La foto con la macchina","La foto col cane per fare colpo",
    "La foto di gruppo dove non si capisce chi è","La bio con la citazione filosofica",
    "La bio con altezza e segno zodiacale","La bio ironica su Tinder",
    "La bio vuota","Bumble dove scrive prima lei",
    "Le conversazioni che muoiono subito","Il primo appuntamento da Tinder",
    "L'ansia del primo appuntamento online","Incontrarsi dopo settimane di chat",
    "La delusione dal vivo rispetto alle foto","La chimica dal vivo",
    "Lo speed dating","Il dating al buio","Le agenzie matrimoniali",
    "I siti di incontri per over 50","Il dating app per relazioni serie",
    "Il dating app per avventure","Il poliamore sulle app",
    "Le relazioni nate su Tinder che funzionano","Il matrimonio nato da un'app",
    "Il matching basato sulla compatibilità","Il matching basato sulla posizione",
    "Le notifiche di chi ti ha messo like","Il profilo verificato",
    "La modalità incognito sulle app","Essere scoperti su Tinder da amici",
    "Trovare il tuo ex su Tinder","Trovare il tuo capo su Bumble",
    "Le app di dating per nicchie","Le app di dating per vegani",
    "Le app di dating per sportivi","Le app di dating per religiosi",
    "Il dating offline vs online","Conoscersi al bar vs su un'app",
    "Conoscersi tramite amici in comune","Il setup dell'amico che ti presenta qualcuno",
    "Il terzo incomodo al primo appuntamento","La friend zone",
    "Il dating multiplo (frequentare più persone)","La conversazione esclusività",
    "Il DTR (define the relationship)","Le red flag nel dating",
    "Le green flag nel dating","Il situationship",
    "Il slow dating","Il mindful dating",
    "Le cene al buio per single","Gli eventi per single",
    "I viaggi per single","Le crociere per single",
    "Il love bombing","Il gaslighting nelle relazioni",
    "L'ick improvviso","Il butterflies feeling",
    "La compatibilità zodiacale nel dating","L'oroscopo per capire la compatibilità",
    "Il manifesting dell'amore","La legge dell'attrazione in amore",

    # ─── 12. COSE DELL'ADOLESCENZA (~100) ───
    "Il primo motorino","La prima cotta","Il primo bacio",
    "Le feste del sabato sera","Il sabato sera in piazza",
    "Le serate al muretto","Le comitive di amici",
    "Le prime uscite senza genitori","La prima vacanza senza genitori",
    "La prima sigaretta","La prima birra","La prima sbornia",
    "Il diario segreto","La lettera d'amore scritta a mano",
    "Il bigliettino passato in classe","Gli SMS da 160 caratteri",
    "Le chiamate infinite al telefono fisso","Il credito del telefono che finisce",
    "La ricarica da 5 euro","Le suonerie personalizzate del telefono",
    "Il walkman e poi il lettore MP3","L'iPod pieno di canzoni",
    "Masterizzare CD per gli amici","Le compilation su cassetta",
    "Le raccolte di figurine","L'album Panini dei mondiali",
    "Le figurine da scambiare in cortile","I braccialetti dell'amicizia",
    "Le collane dell'amicizia divise in due","Le scritte sui diari",
    "Il poster nella camera","La camera piena di poster",
    "La cameretta condivisa col fratello","Litigare per il bagno",
    "Il coprifuoco dei genitori","Tornare a casa tardi di nascosto",
    "Le bugie ai genitori per uscire","La scusa del pigiama party",
    "Il pigiama party dalle amiche","Le serate a giocare ai videogiochi",
    "Le partite a FIFA col compagno","Le partite a PES con gli amici",
    "La PlayStation nella camera","La connessione internet lentissima",
    "MSN Messenger","Le faccine di MSN","Il profilo Netlog",
    "MySpace e la top 8 degli amici","La prima foto profilo su Facebook",
    "Tumblr e le citazioni tristi","Ask.fm e le domande anonime",
    "Il primo account Instagram","Il primo selfie","La prima storia Instagram",
    "Il primo TikTok","La musica emo e punk rock","Le Vans a scacchi",
    "I pantaloni a vita bassa","La felpa con le scritte enormi",
    "I jeans strappati","Le Superga bianche","Le All Star consumate",
    "Lo zaino Eastpak","Lo zaino Invicta","L'astuccio Smemoranda",
    "Il diario Smemoranda","Il diario Comix","La Smemoranda con le battute",
    "L'interrogazione a sorpresa","La versione di latino","Il compito di matematica",
    "Il tema di italiano","La tesina di terza media","L'esame di maturità",
    "La notte prima degli esami","I 100 giorni alla maturità",
    "Lo scherzo dell'ultimo giorno di scuola","La gita scolastica",
    "Il viaggio d'istruzione all'estero","La gita a Roma in terza media",
    "La foto di classe","L'annuario scolastico","Il professore preferito",
    "Il professore odiato","Il compagno di banco","Il secchione della classe",
    "Il bullo della scuola","Il rappresentante di classe",
    "L'assemblea d'istituto","L'occupazione della scuola",
    "La ricreazione di 15 minuti","Il panino della macchinetta",
    "La merenda dalla mamma","La paghetta settimanale",
    "Risparmiare la paghetta","Spendere tutto il primo giorno",
    "Il primo lavoretto estivo","Il primo stipendio",
    "La patente a 18 anni","L'esame di guida","La prima guida con il foglio rosa",
    "Prendere la macchina dei genitori di nascosto","Il primo incidente in macchina",
    "Le prime vacanze in campeggio con amici","Interrail a 18 anni",

    # ─── 13. CONCETTI DI CUCINA CASALINGA (~150) ───
    "La ricetta della nonna","Le ricette di GialloZafferano",
    "Le ricette di Benedetta Rossi","I tutorial di cucina su YouTube",
    "Il Bimby e le sue ricette","La planetaria per impasti",
    "Il forno a convezione","La padella in ghisa",
    "La padella antiaderente","Il wok","La pentola a pressione",
    "Il sottovuoto casalingo","La marinatura","La cottura a bassa temperatura",
    "Il sous vide","La friggitrice ad aria","Il microonde per cucinare",
    "Il forno a vapore","La cottura al cartoccio","La cottura alla griglia",
    "Il barbecue a carbone vs a gas","Il kamado","Il forno per pizza da giardino",
    "La pietra refrattaria per pizza","Il mattarello della nonna",
    "La spianatoia in legno","La mezzaluna per il battuto",
    "Il tagliere in legno d'olivo","Il coltello da chef giapponese",
    "Il coltello Victorinox","Il set di coltelli professionali",
    "Il robot da cucina","Il frullatore a immersione","Il mixer",
    "Lo spremiagrumi elettrico","La centrifuga","L'estrattore a freddo",
    "La macchina del pane","La gelatiera casalinga","La yogurtiera",
    "L'essiccatore per alimenti","La vaporiera","La tajine",
    "La pentola di coccio","La pentola in rame","La cocotte in ghisa",
    "Il dutch oven","Le teglie da forno antiaderenti","Le teglie in silicone",
    "La carta da forno","La pellicola trasparente vs il coperchio in silicone",
    "I contenitori in vetro per conservare","I barattoli Bormioli","I tupperware",
    "Fare la pasta in casa","Tirare la sfoglia a mano",
    "La macchina per la pasta","I ravioli fatti in casa",
    "I tortellini fatti in casa","Le lasagne della domenica",
    "Il ragù che cuoce per ore","Il sugo di pomodoro fresco",
    "La passata di pomodoro fatta in casa","Le conserve estive",
    "La giardiniera fatta in casa","Le melanzane sott'olio",
    "I pomodori secchi sott'olio","I peperoni arrostiti",
    "Le zucchine grigliate","La caponata siciliana fatta in casa",
    "Il pesto al mortaio","Il pesto fatto in casa vs comprato",
    "La besciamella fatta in casa","La maionese fatta in casa",
    "Il dado fatto in casa","Il brodo di carne della nonna",
    "Il brodo vegetale fatto in casa","Il soffritto base",
    "Fare il pane in casa","La lievitazione naturale",
    "Il lievito madre","La pizza fatta in casa","La focaccia fatta in casa",
    "I grissini fatti in casa","Le crostate fatte in casa",
    "Il tiramisù fatto in casa","La panna cotta fatta in casa",
    "Il budino fatto in casa","I biscotti fatti in casa",
    "I muffin fatti in casa","Le meringhe fatte in casa",
    "La torta di compleanno fatta in casa","La torta al cioccolato fatta in casa",
    "Il pan di Spagna fatto in casa","La crema pasticcera fatta in casa",
    "Le chiacchiere di Carnevale","Le castagnole","Le zeppole di San Giuseppe",
    "Il panettone fatto in casa","Il pandoro artigianale",
    "La colomba fatta in casa","Le uova di Pasqua artigianali",
    "Il meal prep della domenica","La schiscetta per l'ufficio",
    "Il pranzo preparato la sera prima","Le porzioni congelate",
    "Cucinare in batch","Gli avanzi della cena riciclati",
    "La frittata con gli avanzi","Le polpette con il pane raffermo",
    "La ribollita con il pane vecchio","La pappa al pomodoro",
    "Lo svuotafrigo","La cena improvvisata con quello che c'è",
    "La spesa al mercato rionale","La spesa dal contadino",
    "I prodotti a km zero","L'orto in giardino",
    "L'orto sul balcone","Le erbe aromatiche fresche",
    "Il basilico sul davanzale","Il rosmarino nell'orto",
    "Cucinare con le spezie","La curcuma in cucina",
    "Lo zenzero fresco","Il peperoncino calabrese",
    "L'aglio di Nubia","Il sale rosa dell'Himalaya",
    "Il sale nero di Cipro","L'aceto balsamico di Modena tradizionale",
    "L'olio extravergine nuovo","La spremitura a freddo dell'olio",
    "La degustazione di olio","Le ricette della tradizione regionale",
    "La cucina molecolare a casa","Il piatto impiattato come al ristorante",
    "La mise en place casalinga","L'apparecchiare la tavola per le feste",
    "Le tovagliette americane","I tovaglioli di stoffa",
    "I piatti di ceramica artigianale","I bicchieri da vino corretti",
    "La cantinetta per il vino","Il decanter",
    "I calici da degustazione","Abbinare vino e cibo",
    "La cena a tema","La cena con amici cucinando insieme",
    "Il potluck tra amici","La grigliata nel giardino",
    "La frittura di pesce fatta in casa","Il fritto misto alla piemontese",

    # ─── 14. TIPI DI ESPERIENZE (~200) ───
    "Il concerto in acustico","Il concerto sotto la pioggia",
    "Il festival al tramonto","La notte in tenda sotto le stelle",
    "L'alba vista dalla montagna","La cena a lume di candela sul mare",
    "Il picnic in vigna","La degustazione di olio d'oliva",
    "Il corso di ceramica","Il corso di pittura",
    "Il ritiro di yoga","Il weekend in monastero",
    "Il weekend alle terme","La spa con sauna finlandese",
    "Il bagno turco","La vasca idromassaggio all'aperto",
    "Il percorso Kneipp","I massaggi ayurvedici",
    "Il massaggio con le pietre calde","La floating experience",
    "La camera sensoriale","Il bagno nel bosco",
    "La forest bathing","La passeggiata tra i vigneti",
    "La vendemmia come esperienza","La raccolta delle olive",
    "La raccolta delle ciliegie","La raccolta dei tartufi",
    "La visita in cantina","La degustazione di vini",
    "La degustazione di birre artigianali","La degustazione di formaggi",
    "La degustazione di cioccolato","Il corso di pasticceria",
    "Il corso di cucina regionale","Il corso di sushi",
    "Il corso di mixology","Il corso di latte art",
    "Il corso di fotografia","Il corso di calligrafia",
    "Il workshop di lettering","Il corso di acquarello",
    "Il corso di scultura","Il corso di falegnameria",
    "Il corso di restauro mobili","Il corso di legatoria",
    "Il laboratorio di profumi","Il corso di saponificazione",
    "Il corso di candele artigianali","Il laboratorio di cioccolato",
    "Il tour gastronomico a piedi","Lo street food tour",
    "Il food truck festival","La sagra di paese",
    "La festa della birra","L'Oktoberfest","La festa del vino novello",
    "La notte bianca in città","La notte dei musei",
    "La visita al museo di notte","La mostra immersiva",
    "La mostra di arte contemporanea","La mostra fotografica",
    "Il vernissage","La galleria d'arte",
    "Lo spettacolo di teatro","Il teatro sperimentale",
    "Il teatro all'aperto","L'opera lirica all'Arena di Verona",
    "Il balletto classico","Lo spettacolo di danza contemporanea",
    "Il musical a teatro","Il concerto in piazza",
    "Il concerto in un club piccolo","Il concerto in uno stadio",
    "Il festival musicale di tre giorni","Il festival musicale con camping",
    "Il rave all'aperto","La silent disco","Il dj set al tramonto",
    "Il cinema all'aperto d'estate","Il drive-in cinema",
    "La maratona di film a casa","La maratona di serie TV",
    "L'escape room","L'escape room horror","L'escape room in realtà virtuale",
    "Il laser tag","Il paintball","Il softair",
    "Il go-kart","La pista di go-kart indoor",
    "Il bowling con gli amici","La serata karaoke",
    "La serata quiz al pub","Il pub crawl","L'aperitivo su una terrazza panoramica",
    "La cena in un ristorante stellato","La cena al buio",
    "La cena con delitto","La cena medievale",
    "La cena nel vigneto","La cena sul rooftop",
    "La cena in barca","Il brunch della domenica al ristorante",
    "L'afternoon tea all'inglese","La merenda sinoira piemontese",
    "La gita in barca a vela","Il giro in catamarano",
    "Il giro in yacht","La crociera nel Mediterraneo",
    "La crociera ai fiordi","Il traghetto per le isole",
    "Il volo in mongolfiera","Il paracadutismo",
    "Il bungee jumping","Il volo in parapendio",
    "Il volo in deltaplano","Il volo in elicottero",
    "Il lancio col paracadute in tandem","Lo zipline nella natura",
    "Il ponte tibetano","La via ferrata",
    "L'arrampicata su roccia","Il canyoning",
    "Il rafting","Il kayak nei fiumi","Il kayak nel mare",
    "La discesa in canoa","Il torrentismo",
    "L'orienteering nei boschi","La caccia al tesoro in città",
    "Il geocaching","La camminata sui sentieri storici",
    "Il Cammino di Santiago","La Via Francigena",
    "Il trekking sulle Dolomiti","Il trekking in Cinque Terre",
    "Il sentiero degli Dei in Costiera","Il giro del Monte Bianco",
    "L'alta via dei parchi","Il trekking notturno",
    "L'escursione con le ciaspole","La ciaspolata al chiaro di luna",
    "Lo sci di fondo nel bosco","La slitta trainata dai cani",
    "Il giro in slitta trainata dai cavalli","La passeggiata a cavallo",
    "L'equitazione in spiaggia","Il safari fotografico",
    "Il whale watching","Il bird watching","Il dolphin watching",
    "La visita a un santuario degli animali","La fattoria didattica",
    "Il weekend in agriturismo","Il glamping nella natura",
    "La notte in un faro","La notte in un castello",
    "La notte in un rifugio alpino","La notte in una casa sull'albero",
    "La notte in una bolla trasparente","La notte in un trullo",
    "La notte in una yurta","L'esperienza in un igloo",
    "Il viaggio in treno panoramico","Il viaggio in Orient Express",
    "Il viaggio in camper","Il road trip in macchina",
    "Il viaggio in moto","Il giro in Vespa per la Toscana",
    "Il giro in bicicletta nelle Langhe","La cicloturismo lungo il Danubio",
    "Il viaggio zaino in spalla","Il volontariato all'estero",
    "Il workaway in una fattoria","Lo scambio casa per le vacanze",
    "Il Couchsurfing","L'Airbnb Experience",
    "Il tour guidato della città","Il free walking tour",
    "Il tour in segway","Il tour in monopattino elettrico",
    "Il tour in bici elettrica","Il tour in Ape Calessino",
    "La visita ai mercatini di Natale","La visita ai mercati delle pulci",
    "La visita a un orto botanico","La visita a un giardino storico",
    "La visita a un parco avventura","Il parco divertimenti",
    "Il parco acquatico","Le terme naturali all'aperto",
    "Le sorgenti termali","Il bagno nelle cascate",
    "Il bagno nel lago di montagna","Il bagno nel fiume",
    "La piscina naturale","Il nuoto in acque libere",
    "La traversata a nuoto","La regata velica",
    "Il giro in gondola a Venezia","Il giro in vaporetto",
    "La gita alle isole della laguna","Il giro dell'isola in motorino",
    "Il giro in quad nell'entroterra","Il giro in jeep nel deserto",
    "Il trekking sul vulcano","La visita alle grotte",
    "La visita alle catacombe","Il tour dei fantasmi di notte",
    "La rievocazione storica","Il Palio di Siena dal vivo",
    "La partita di calcio allo stadio","La finale di Champions dal vivo",
    "Il Gran Premio di Formula 1 dal vivo","La maratona come partecipante",
    "La mezza maratona","La corsa a ostacoli tipo Tough Mudder",
    "La Spartan Race","L'ultratrail","Il triathlon",
]
