services:
  - type: web
    name: overunder
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: RESEND_API_KEY
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: REDIS_URL
        sync: false
      - key: PIXABAY_API_KEY
        sync: false
